### ISSUE TITLE
[FEAT]: Authentication - User Log In

### ISSUE THREAD

**Issue by Homoakin619** [hngprojects/hng_boilerplate_nestjs#10]
### Description
Implement a robust login feature to streamline user access and authentication processes. This feature should encompass secure user logins, password protection, and account security measures.
### Acceptance Criteria

- [x] The endpoint must return a 422 error for missing or invalid input with an appropriate error message.
- [x] A 401 status code should be returned for invalid credentials with an appropriate error message.
- [x] A successful login should return a 200 response with success message
- [x] User's credentials transmitted securely to the Backend
- [x] Once validation checks are passed, JWT token is generated for the user encoded using the user mail, user id, and first and last names and returned as part of the response payload

### Expected Outcome
- The user should be redirected to the subsequent page if successful, or receive an error message if unsuccessful
Users are informed of login activity.
### Requirements
**Corresponding database fields for:**
- Email Address
- Password
### **User Login [POST] `/api/v1/auth/login`**
1. Login Endpoint
- Given a request with valid user details (ie`email`, `password`), when the user logs in, then the system should return the user data, access and refresh token with a 200 success status code.
2. Incorrect credentials
- Given the input does not match with the credentials on the database, then the system should return a 400 bad request error status with an appropriate error message
**Request**
```
POST /api/v1/auth/login
{
  "email": String,
  "password": String
}
```
**Successful Response**
```
{
  "message": String,
  "data":
       "user": {
            "id": String,
            "email": String,
            "role": String,
            "signup_type": String,
            "is_active": Boolean,
            "is_verified": Boolean,
            "created_at": Date,
            "updated_at": Date,
            "last_login-at": Date
          },
      access_token: String,
      refresh_token: String
}
```
**Error Response**
```
{
  "message": String,
  "error": String,
  "status_code": Int,
}
```

**Comment by buka4rill** [comment]
remember to version this api

**Comment by cyber330d** [comment]
sorry to butt in but shouldn't there be email validation here?
before we even check if the provided credentials are correct in DB?
or will you allow any api request that potentially has incorrect email formats to hit DB?

**Comment by Timmy-id** [comment]
**Team Members**

@timmy95 - NestJs
@TeeR197 - Laravel
@Tayo Jubril - FastAPI

**Comment by tayo** [comment]
You have the wrong tayo.  @Timmy-id

**Comment by Timmy-id** [comment]
> You have the wrong tayo. @Timmy-id

No, it's the slack ID I used not GitHub username @tayo
