### ISSUE TITLE
[FEAT] Develop API Endpoints for Notification Settings - Backend

### ISSUE THREAD

**Issue by Benson-Ogheneochuko** [hngprojects/hng_boilerplate_nestjs#104]
## Description
Develop server-side logic to retrieve current notification settings.

## Acceptance Criteria
- The endpoint should be accessible at  `/api/v1/notification-settings`.
- The endpoint should accept HTTP POST requests.
- Requests to the endpoint must include a valid authentication token in the Authorization header. `Authorization: Bearer <token>`
- Given a POST request with user data (userId & token), the system should validate and sanitize the incoming data.

### Purpose
Provide a backend service that allows users to retrieve  their notification preferences securely.

### Requirements	

- [ ] Develop server-side logic to retrieve current notification preferences.
- [ ] Ensure user exists and is authorized for notification settings they want to retrieve.
- [ ] Retrieve and return user notification settings when user exists and is authorized.
- [ ] Return appropriate error codes and responses in error scenarios

### Expected Outcome
- Allow retrieving notification settings with appropriate validation and security measures.

### Status Codes
- 200: User settings data found
- 400: Bad Request
- 401: Unauthorized
- 404: User not found
- 500: A server error occurred

## Endpoint
`[POST] /api/v1/notification-settings`

### Request:
Headers:

```
{
  "Content-Type": "application/json",
  "Authorization": "Bearer <JWT_TOKEN>"
}
```

Body:
```
{
  "userId": "String"
}
```

### Responses:
Successful response
```
{
  "message": "string",
  "success": true,
  "status_code": 200,
  "data": {
    // JSON object containing user notification settings
  }
}

## Example User Settings
{
  "email": false,
  "push-notification": true
}

```

Error response
```
{
  "message": "string",
  "success": false,
  "status_code": int
}
```

## Testing
Write unit tests that cover

- [ ] Verifying user authentication and authorization to retrieve notification settings
- [ ] Appropriate response and status code is returned for various scenarios
- [ ] User notification settings data is fetched and returned correctly

**Comment by markessien** [comment]
this is not coherent

**Comment by Benson-Ogheneochuko** [comment]
List (Slack ID) of Team Members working on this issue

Nockk
Victoria
codewithKen
Uloamaka
batman.py

**Comment by Benson-Ogheneochuko** [comment]
Slack ID of Interns working on this issue.

Nockk
batman.py
