### ISSUE TITLE
[FEAT] Blog Post Deletion Endpoint - Backend

### ISSUE THREAD

**Issue by codeReaper0** [hngprojects/hng_boilerplate_nestjs#108]
## Description

_Develop an endpoint to handle requests to delete a blog post where it is only open to super admin. If the data is deleted successfully, it will be returned to the client with a '202' status. If an error occurs, an appropriate error status will be returned._

## Acceptance Criteria

- The endpoint deletes a blog post data.
- The endpoint can be called only by a super admin.
- Returns a `202` status code and the correct response body when blog is deleted successfully.
- Returns a `404` status code and the correct response body when blog is not found.
- Returns a `403` status code and the correct response body when a user that is not an admin tries to access the endpoint.
- Returns an appropriate error message when an error occurs.

### Requirements

- [ ] Implement API endpoint for deleting blog posts.
- [ ] Confirm deletion action to prevent accidental deletions.
- [ ] Make sure the endpoint can only be called by a super admin
- [ ] Ensure blog post safely deleted in the database.
- [ ] Handle unexpected errors and return the appropriate status code.

### Expected Outcome

- Super Admin should be able to send a request to the backend to delete a blog post, with data temporarily removed and confirmation provided.

### Endpoints

[DELETE] /api/v1/blogs/:id

- **Description**: Delete a Blog Data.
- **Path Parameters**:
  - `id`: The of the blog to be deleted. Default is `1`.
- **Success Response**:
  - Status: `202 OK`
  - Body:

    ```json
    {
    "message": "Blog successfully deleted",
    "status_code": 202
    }
    ```

- **Error Response**:
  - Status: `500 Internal Server Error`
  - Body:

    ```json
    {
        "message": "Internal server error.",
        "status_code": 500,
    }
    ```

- **Unauthorized User Response**:
  - Status: `403 Forbidden`
  - Body:

    ```json
    {
        "message": "You are not authorized to perform this action",
        "status_code": 403,
    }
    ```
- **Unauthorized User Response**:
  - Status: `404 Not Found`
  - Body:

    ```json
    {
        "message": "Blog with the given Id does not exist",
        "status_code": 404,
    }
    ```

- **Invalid Method Response**:
  - Status: `405 Method Not Allowed`
  - Body:

    ```json
    {
        "message": "This method is not allowed.",
        "status_code": 405,
    }
    ```

- **Bad Request Response**:
  - Status: `400 Bad Request`
  - Body:

    ```json
    {
        "message": "An invalid request was sent.",
        "status_code": 400,
    }
    ```

### Testing

**Test Scenarios**

1. **Successful Deletion of Blog Post**
   - Ensure that the endpoint successfully deletes a blog post.
   - Confirm that the status code is `202`.

2. **No Blog Post Found**
   - Simulate a scenario where no blog posts are present in the database.
   - Confirm that the status code is `404`.
   - Confirm that the response body contains an appropriate message.

3. **Insufficient Permission**
   - Simulate a scenario where an ordinary user wants to access this endpoint.
   - Confirm that the status code is `403`.
   - Confirm that the response body contains an appropriate message.

4. **Internal Server Error**
   - Simulate an internal server error to raise an exception.
   - Verify that the endpoint returns a `500 Internal Server Error` status code.
   - Confirm that the response body contains an appropriate error message.

5. **Invalid Id Parameters**
   - Send requests with invalid `id`  parameters (e.g., non existing obect Id).
   - Verify that the endpoint returns a `400 Bad Request` status code.
   - Confirm that the response body contains an appropriate error message.

6. **Invalid Method**
   - Send a request using an invalid HTTP method (e.g., POST) to the endpoint.
   - Verify that the endpoint returns a `405 Method Not Allowed` status code.

**Comment by markessien** [comment]
only open for superadmin, and you should soft delete

**Comment by buka4rill** [comment]
@codeReaper0 who are your teammates?

**Comment by codeReaper0** [comment]
codeReaper0 (Me)- FastAPI
kunmifab - Laravel
Iretoms - Go
etanami - NestJS


remaining one but these are their github username
