### ISSUE TITLE
[FEAT]: Authentication - Social Login

### ISSUE THREAD

**Issue by Homoakin619** [hngprojects/hng_boilerplate_nestjs#11]
### Description
Integrate social login functionality to provide users with the option to sign in using OAuth feature from their social media accounts. This feature should allow users to log in effortlessly and securely through platforms such as Google, Facebook, GitHub etc.
### Acceptance Criteria
- OAuth for authentication Implemented
- Authenticated user magic link requests created
- Backend logic for OAuth authentication implemented
### Expected Outcome
- Users should be able to log in using their social accounts.
### Requirements
- Design and implement an endpoint for social authentication
- Integrate OAuth for authentication.
### **User Social Login [GET] `/api/auth/social_login?social_auth=AuthType`**
1. Social Login Endpoint
- Given a request to login with socials, then the social authentication process should be implemented, the system should return the user data, access and refresh token with a 200 success status code.
2. Authentication Error
- Given the user cannot validate social login details, then the system should return a 400 bad request error status with an appropriate error message
**Successful Response**
```
{
  "message": String,
  "data":
      "user": {
          "message": String,
          "user": {
            "id": String,
            "email": String,
            "role": String,
            "signup_type": String,
            "is_active": Boolean,
            "is_verified": Boolean,
            "created_at": Date,
            "updated_at": Date,
            "last_login-at": Date
          },
      access_token: String,
      refresh_token: String
}
}
```
**Error Response**
```
{
  "message": String,
  "error": String,
  "statusCode": Int,
}
```

**Comment by markessien** [comment]
Split this into each type, e.g Google Auth, Facebook Auth

**Comment by daniell-olaitan** [comment]
@markessien  I wanted to ask if Github OAuth is part of the concept of the application. I'm currently without a team, and I'm considering working on the Github OAuth.

**Comment by daniell-olaitan** [comment]
@buka4rill I wanted to ask if Github OAuth is part of the concept of the application. I'm currently without a team, and I'm considering working on the Github OAuth.
