### ISSUE TITLE
[FEAT]: HELP CENTER - DELETE TOPIC

### ISSUE THREAD

**Issue by Daniel-Ojo-Williams** [hngprojects/hng_boilerplate_nestjs#111]
## Description

The help center contains topics that provide users with advice and assistance from the support team. This endpoint permanently deletes outdated or invalid topics (help guides) from the database.

## Acceptance Criteria

- Endpoint is protected.
- Topics can be deleted by superadmins only.

### Purpose

To delete a topic previously created

### Requirements	

- [ ] Authentication: This endpoint requires authentication.
   -  The authentication token (Bearer ey9hk3j4g...) must be sent in the request header as `Authorization`.
- [ ] Access Control: Only superadmins can access this endpoint.
- [ ] Path Parameter: The endpoint requires an ID (of the topic to be deleted) in the path parameter.
- [ ] Functionality: Only the topic with the specified ID will be removed.

### [DELETE] `/api/v1/help-center/topics/:id`
**Deletes a topic**

1. Endpoint Flow

- This endpoint deletes the topic with the ID specified in the path from the `help_center_topics`  table.

## Request

[DELETE] /api/v1/help-center/topics/:id

### Successful Response

**Status Code**: `200`

**Description:** Deleted successfully
```json
{
    "success": true,
    "message": Topic deleted successfully,
    "status_code": 200
}
```

### Error Response

**Status Code:** `403`

**Description:** Forbidden, Only SuperAdmins can access this endpoint.
```json
{
    "success": false,
    "message": Access denied,
    "status_code": 403
}
```

**Status Code:** `404`

**Description:** No topic ID matches the ID param provided.
```json
{
    "success": false,
    "message": Topic not found, please check and try again,
    "status_code": 404
}
```

**Status Code:** `500`

**Description:** Internal Server error
```json
{
    "success": false,
    "message": Something went wrong, please try again later or contact support it persists,
    "status_code": 500
}
```

## Validations
- The ID being passed must be a valid UUID formatted string

## Dependencies
- This endpoint depends on the Database setup task, as it involves interaction with the database.
- The create endpoint for help center topics must also be set up for this endpoint to be useful.
- Role-Based Access Control must be set up to properly access this endpoint as only SuperAdmins can delete a help center topic.

## Database Schema

**Table name: help_center_topics**

_id:_

- constraints: varchar(uuid), unique, primary-key, not null

_title:_

- constraints: varchar, unique, not null

_content:_

- constraints: text, not null,

_author:_

- constraints: varchar, unique, not null

_createdAt:_

- constraints: datetime

_updatedAt:_

- constraints: datetime

### Database diagram

![database diagram](https://drive.google.com/uc?export=view&id=13dnMIemT-CJu_Mo0Dqy9BBdYuC33M148)

### Testing

1. Unit Tests

- The topic with the ID provided only is deleted.
- Only superAdmin can access this endpoint.
- The returned response structure for the endpoint matches the documentation.

**Comment by Daniel-Ojo-Williams** [comment]
As requested by Mark [here](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/76#issuecomment-2232514038), this article has been separated to this functionality.

**Comment by markessien** [comment]
unclear what articles or topics are

**Comment by Daniel-Ojo-Williams** [comment]
Updated for consistent naming (topic) and hint on what topics are as about Help Center.

**Comment by Daniel-Ojo-Williams** [comment]
I've updated the description to include an explanation of what topics are in the context of the Help Center and what the endpoint does to manage them.

**Comment by markessien** [comment]
A "topic" is not clearly part of "help". Fix your route

**Comment by Daniel-Ojo-Williams** [comment]
Updated the route to `/api/v1/help-center/topics/:id` to provide clearer context and reflect how topics are nested under the help center page, explicitly showing that topics are part of the help center.

**Comment by highb33kay** [comment]
Update Message Responses

"message": String,

**Comment by highb33kay** [comment]
any dependencies on other tasks or systems.

**Comment by highb33kay** [comment]
Validations?

**Comment by Daniel-Ojo-Williams** [comment]
Message responses have been updated, and necessary dependencies and validations have been included as requested.
