### ISSUE TITLE
[FEAT] Update user API

### ISSUE THREAD

**Issue by scottandee** [hngprojects/hng_boilerplate_nestjs#112]
## Description
Develop API endpoint to update a user

## Acceptance Criteria
- The endpoint should be accessible at `/api/v1/users/:userId`
- The endpoint should accept HTTP `PATCH` requests.
- The endpoint should be secured to ensure that only authenticated users can update user
- The endpoint should check that the user has the appropriate permissions
- The endpont should validate all data passed in the body of the request 
- Requests to the endpoint must include a valid authentication token in the Authorization header. `Authorization: Bearer <token>`
- Given a request with a valid user ID, when the user is authenticated and authorized, the system should update the user with a status code of 200
- Given a request with an invalid or non-existent user ID, when the user is authenticated and authorised, the system should return a 404 Not Found status.

### Request
- **Endpoint**	
PATCH `/api/v1/users/:userId`

- **Request Body**
```bash
{
    "first_name": "String",
    "last_name": "String",
    "phone_number": "String"
}
```

- **Parameters:**
    - `userId`: string

### Expected Outcome
- **Successful Response**
    - Only the super admin and the user themselves can successfully update user details.
```bash
{
  "status": "success",
  "message": "User Updated Successfully",
  "user": {
    "id": "String",
    "name": "String",
    "phone_number": "String"
  }
}
```

- **Error Response**:

```bash
{
  "message": "string",
  "error": "string"
  "status_code": int,
}
```

### Purpose
Enable updating of user information from the user Details Page.

### Requirements
- Develop server-side logic to update a single user
- Ensure compliance with security standards for handling user information.

### Checklist
- [ ] Define API endpoint to update user details.
- [ ] Implement logic to update user information in the database.
- [ ]  Handle success and error responses.

### Unittests
- Successful response with valid id
- Invalid userId
- Missing userId
- Invalid request body

**Comment by scottandee** [comment]
Team members 
- [scottandee](https://github.com/scottandee) NodeJs 
- [Nixon-hk](https://github.com/Nixon-hk) Python 
- [utuedey](https://github.com/utuedey) Golang

**Comment by NdubuisiJr** [comment]
@scottandee follow the API route versioning pattern

**Comment by scottandee** [comment]
@NdubuisiJr I have modified it to fit the adopted versioning format `/api/v1`
