### ISSUE TITLE
[FEAT]: Create Organization Invitation Link -Backend

### ISSUE THREAD

**Issue by Goldyn19** [hngprojects/hng_boilerplate_nestjs#113]
### Description
Create an API endpoint to generate invitation links for inviting users to join an organization. This endpoint will validate the input data and generate a unique invitation link for the specified organization.
#### API Endpoint Implementation:
- The endpoint should be accessible at `/api/v1/invite/create`.
- The endpoint should accept HTTP POST requests.
#### Data Validation and Sanitization:
- The API should validate the request payload to ensure the required fields (organizationId, email) are present and valid.
#### Invitation Link Generation:
- Upon successful validation, the API should generate a unique invitation link for the specified organization.
- The generated invitation link should be stored in the database with an expiration date.
#### Email Sending:
- The API should send an email containing the invitation link to the specified email address.
- The email should contain a clear and concise message with the invitation link.
#### Response:
- On success, the API should return a 201 Created status code with the invitation link and a success message.
- On failure, the API should return a 400 Bad Request status code with appropriate error messages.
#### POST  /api/v1/invite/create
```json
{
  "organizationId": "string",
  "email": "string"
}
```
### Successful Response:
```json
{
  "message": "Invitation link created and sent successfully",
  "data": {
    "invitationLink": "string"
  },
  "status_code": 201
}
```
### Error Response:
```json
{
  "message": "Failed to create invitation link",
  "errors": [
    "Invalid organization ID",
    "Email format is incorrect"
  ],
  "status_code": 400
}
```
### Purpose
Provides a backend service to generate unique invitation links for inviting users to join an organization, ensuring the data is valid, storing the invitation link with an expiration date, and sending the invitation link via email.
### Requirements
- Develop server-side logic to handle invitation link creation.
- Validate and sanitize incoming data.
- Generate and store unique invitation links with expiration dates.
- Send the generated invitation link via email to the specified address.
### Expected Outcome
The API endpoint allows administrators to generate invitation links for inviting users to join an organization, ensuring the links are valid and stored with expiration dates.
### status_code
- **201**: Invitation link was successfully created.
- **400**:
  - Invalid organization ID
  - Email format is incorrect
- **500**: A server error occurred
### Testing
- Write unit tests to ensure the invitation link creation endpoint validates input correctly and generates unique invitation links.
- Perform load testing to ensure the endpoint can handle multiple requests.
- Test various scenarios for generating invitation links (e.g., valid organization ID, invalid organization ID, invalid email format, etc.).
- Test email delivery to ensure the invitation link is correctly sent to the specified email address.

**Comment by NdubuisiJr** [comment]
@Goldyn19 how will this generated link reach the user?
There should be a part that automatically sends an email to the invited user attaching the link.

**Comment by Goldyn19** [comment]
In the design there is a button to copy the link. The link is to be shared externally

**Comment by Goldyn19** [comment]
i have added a way to share link through email

**Comment by Shullyd7** [comment]
It is status_code, not status. Be consistent with the snake case

**Comment by Goldyn19** [comment]
> It is status_code, not status. Be consistent with the snake case

changes has been made

**Comment by hashkitti001** [comment]
Please can you add an isActivated field to the invitationLink database schema .To be able to deactivate the link when it's not in use @Goldyn19
