### ISSUE TITLE
[FEAT] HELP CENTER - CREATE TOPIC

### ISSUE THREAD

**Issue by elizase405** [hngprojects/hng_boilerplate_nestjs#116]
## Description
Backend logic to handle posting of a topic (Admin only)

## Acceptance Criteria
- Admin can create topics
- Users can view topics including the newly created one

### Purpose
Allows super admin to create a new topic

### Requirements	
- [ ] Only an authorized individual can post a topic
- [ ] Posted topic is added to database

### Expected Outcome
- New topics should reflect on the database
- Topics should reflect on the frontend when searched by a user

## EndPoints
**POST /api/v1/help-center/topics/**

**Authentication Required:** Yes (JWT Token)

**Authorization Required:** Yes (Admin Role)

Headers:
  - `Content-Type: application/json`
  - `Authorization: Bearer <JWT_TOKEN>`

Request:
  ```json
  {
    "title": "string",
    "content": "string",
    "author": "string"
  }
  ```
Response:
  - status: 201 created
  ```json
  {
    "success": true,
    "data": {
      "id": "string",
      "title": "string",
      "content": "string",
      "author": "string",
      "created_at": "datetime",
      "updated_at": "datetime",
    },
    "status_code": 201
  }
  ```
  - status: 401 Unauthorized (No token provided or token is invalid)
  ```json
  {
    "success": false,
    "message": "Access denied. No token provided or token is invalid",
    "status_code": 401
  }
  ```
  - status: 403 Forbidden (User does not have the required role of admin)
  ```json
  {
    "success": false,
    "message": "Access denied",
    "status_code": 403
  }
  ```
  - 422 Bad Request: Invalid input data.
  ```json
  {
    "success": false,
    "message": "Invalid input data",
    "status_code": 422
  }
  ```

 ## Database Schema

**Table name: articles_table**

_article_id:_

- constraints: string(uuid), unique, primary-key, not null

_title:_

- constraints: string, unique, not null, text

_content:_

- constraints: string, not null, text

_createdAt:_

- constraints: datetime

_updatedAt:_

- constraints: datetime

 ### Database Diagram
 [Database image](https://drive.google.com/file/d/17Qnkk9A0kxLiUxMQhnd124vFaaewh76a/view?usp=sharing)

### Testing

1. Unit Tests
- The return data for the `/api/v1/topics` matches the documentation.
- Ensure that Only authorized individuals can create an article
- Validate user input data
- On success, data is added to database

**Comment by elizase405** [comment]
As requested by Mark [here](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/76#issuecomment-2232514038), this article has been separated to this functionality.

**Comment by markessien** [comment]
inconsistent naming

**Comment by CFCIfe** [comment]
Please take note and update your route

https://github.com/hngprojects/hng_boilerplate_nestjs/issues/111#issuecomment-2235907567

**Comment by CollinDex** [comment]
Route has been updated as requested

**Comment by CollinDex** [comment]
Requesting 1st mentor approval from @markessien
