### ISSUE TITLE
[FEAT]: Get all Organization members -Backend

### ISSUE THREAD

**Issue by Goldyn19** [hngprojects/hng_boilerplate_nestjs#117]
### Description
Create an API endpoint to fetch all members in an organization. This endpoint will validate the input data and return a list of all members associated with the specified organization.
#### API Endpoint Implementation:
- The endpoint should be accessible at `/api/organization/{organizationId}/members`.
- The endpoint should accept HTTP GET requests.
- The endpoint should support pagination through query parameters page and page_size.
#### Data Validation and Authorization:
- The API should validate the organizationId to ensure it is valid.
- The API should ensure the requester has the necessary permissions to view the members of the organization.
#### Member Retrieval:
- Upon successful validation, the API should retrieve and return a list of all members in the specified organization.
#### Response:
- On success, the API should return a 200 OK status code with a list of members.
- On failure, the API should return a 400 Bad Request status code with appropriate error messages.
#### GET GET /api/organization/{organizationId}/members?page=1&page_size=10
No request body needed for this endpoint.
### Successful Response:
```json
{
  "status": "success",
  "message": "Organization members fetched successfully",
  "data": {
    "members": [
      {
        "userId": "string",
        "firstName": "string",
        "lastName": "string",
        "email": "string",
        "phone": "string"
      }
      // ... other members
    ],
    "pagination": {
      "currentPage": 1,
      "pageSize": 10,
      "totalPages": 5,
      "totalItems": 50
    }
  },
  "statusCode": 200
}
```
### Error Response:
```json
{
  "status": "fail",
  "message": "Failed to fetch organization members",
  "errors": [
    "Invalid organization ID",
    "Unauthorized access"
  ],
  "statusCode": 400
}
```
### Purpose
Provides a backend service to fetch and return a paginated list of members associated with an organization, ensuring the data is valid and the requester is authorized to access the information.
### Requirements
- [ ] Develop server-side logic to handle fetching organization members.
- [ ] Validate and authorize incoming requests.
- [ ] Retrieve and return a paginated list of members in the specified organization.
### Expected Outcome
The API endpoint allows authorized users to fetch and view all members in an organization in a paginated manner, ensuring the data is valid and securely retrieved.
### Status Codes
- **200**: Organization members were successfully fetched.
- **400**:
  - Invalid organization ID
  - Unauthorized access
- **500**: A server error occurred
### Testing
- Write unit tests to ensure the member retrieval endpoint validates input correctly and returns the correct paginated list of members.
- Perform load testing to ensure the endpoint can handle multiple requests.
- Test various scenarios for fetching organization members (e.g., valid organization ID, invalid organization ID, unauthorized access, different pagination scenarios, etc.).

**Comment by markessien** [comment]
needs pagination
