### ISSUE TITLE
[FEAT] Delete user API

### ISSUE THREAD

**Issue by scottandee** [hngprojects/hng_boilerplate_nestjs#119]
## Description
Develop API endpoint to soft-delete a single user

## Acceptance Criteria
- The endpoint should be accessible at `api/v1/users/:userId`
- The endpoint should accept HTTP `DELETE` requests.
- The endpoint should be secured to ensure that only authenticated users with a role of admin that can delete a user
- The endpoint should soft-delete the user
- Requests to the endpoint must include a valid authentication token in the Authorization header. `Authorization: Bearer <token>`
- If a valid id passed as a parameter, the system should soft-delete the user with the specified id and return a 200 success status code.
- If the user is not found, an error with a 404 status code should be returned.

### Request
- **Endpoint**	
DELETE `/api/v1/users/:userId`

- **Parameters:**
    - `userId`: string

### Expected Outcome
- **Successful Response**
    - Only Admin can delete a user details successfully.
```bash
{
  "status": "success",
  "message": "User Deleted Successfully",
  "user": {
    "id": "String",
    "name": "String",
    "phone_number": "String"
  }
}
```

- **Error Response**:

```bash
{
  "status":string,
  "message": string,
  "status_code":int
}
```

### Purpose
Enable soft-deletion of user records from the user Details Page.

### Requirements
- Develop server-side logic to soft-delete a single user
- Ensure compliance with security standards for handling user information.

### Checklist
- [ ] Define API endpoint to soft-delete a user.
- [ ] Implement logic to delete user information from the database.
- [ ] Handle success and error responses.

### Unittests
- Successful response with valid id
- Invalid userId
- Missing userId

**Comment by markessien** [comment]
make it clear what role can delete a user. Also, soft delete
