### ISSUE TITLE
[FEAT]: Authentication - Forget and Reset Password

### ISSUE THREAD

**Issue by Homoakin619** [hngprojects/hng_boilerplate_nestjs#12]
### Description
Develop a forgot password feature for our platform to enable users to reset their passwords securely in case they forget them. This feature should include a user-friendly password recovery process that guides users through resetting their passwords.
### Acceptance Criteria
- [ ]  Verified that the user actually exists on record
- [ ] Newly created password hashed
### Expected Outcome
- User should be able to initiate a 'reset password' request, and immediately receive a password reset link once the request is made
### Requirements
- Button / Link for 'Forgot Password'
- Notification for user to check their email for a reset link
- Verify user exists
- Encrypt new password
### **Forgot Password [POST] `/api/v1/auth/forgot-password`**
1. Forgot Password Endpoint
- Given a request with valid details (ie `email`), when the user clicks on Forgot Password, then the system should send a password reset link to the email provided with a 200 status code.
2. Incorrect Email
- Given a email does not exists, when the user tries to forget password, then the system should return a 400 bad request error status with an appropriate error message
**Request**
```
POST /api/v1/auth/forgot-password
{
  "email": String
}
```
**Successful Response**
```
{
  "message": String,
}
```
**Error Response**
```
{
  "message": String,
  "error": String,
  "status_code": Int,
}
```
### **Reset Password [POST] `/api/v1/auth/reset-password/{token}`**
1. Reset Password Endpoint
- Given a request with valid details (ie `password`), when the user Reset Password, then the system should respond with a 200 status code on successful password reset.
**Request**
```
POST /api/v1/auth/reset-password/{token}
{
  "password": String
}
```
**Successful Response**
```
{
  "message": String,
}
```
**Error Response**
```
{
  "message": String,
  "error": String,
  "status_code": Int,
}
```

**Comment by incredible-phoenix246** [comment]
## Team Members

| Slack ID    | GitHub Username   |
|---------------|---------------------------|
| osigie        | osigie                     |
| fransix66   | Gbohunmifrancis   |
| Temmy      | temmy669             |

**Comment by incredible-phoenix246** [comment]
@NdubuisiJr all changes has been effected
