### ISSUE TITLE
[FEAT] HELP CENTER - UPDATE TOPIC

### ISSUE THREAD

**Issue by elizase405** [hngprojects/hng_boilerplate_nestjs#121]
## Description
Backend logic to handle topic Updating (Admin only)

## Acceptance Criteria
- Admin can Update topics

### Purpose
Endpoint to allow superadmin to update existing topic

### Requirements	
- [ ] Only an authorized individual can update an topic
- [ ] updated topic replaces the old topic in the database

### Expected Outcome
- Updated topics should reflect on the database

## EndPoint
**PATCH /api/v1/help-center/topics/:id**

**Authentication Required:** Yes (JWT Token)

**Authorization Required:** Yes (Admin Role)

Headers:
  - `Content-Type: application/json`
  - `Authorization: Bearer <JWT_TOKEN>`

Request:
  ```json
  {
    "title": "string",
    "content": "string",
    "author": "string"
  }
  ```
Response:
  - status: 200 OK
  ```json
  {
    "success": true,
    "data": {
      "id": "string",
      "title": "string",
      "content": "string",
      "author": "string",
      "created_at": "datetime",
      "updated_at": "datetime",
    },
    "status_code": 200
  }
  ```
  - status: 401 Unauthorized (No token provided or token is invalid)
  ```json
  {
    "success": false,
    "message": "Access denied. No token provided or token is invalid",
    "status_code": 401
  }
  ```
  - status: 403 Forbidden (User does not have the required role of admin)
  ```json
  {
    "success": false,
    "message": "Access denied",
    "status_code": 403
  }
  ```
  - status: 404 Not-Found
  ```json
  {
    "success": false,
    "message": "Article not found",
    "status_code": 404
  }
  ```
  - 422 Bad Request: Invalid input data.
  ```json
  {
    "success": false,
    "message": "Invalid input data",
    "status_code": 422
  }
  ```

 ## Database Schema

**Table name: articles_table**

_article_id:_

- constraints: string(uuid), unique, primary-key, not null

_title:_

- constraints: string, unique, not null, text

_content:_

- constraints: string, not null, text

_createdAt:_

- constraints: datetime

_updatedAt:_

- constraints: datetime

 ### Database Diagram
 [Database image](https://drive.google.com/file/d/17Qnkk9A0kxLiUxMQhnd124vFaaewh76a/view?usp=sharing)

### Testing

1. Unit Tests
- The return data for the `/api/v1/help-center/topics/:id` matches the documentation.
- Ensure that Only authorized individuals can update a topic
- Validate user input data
- On success, data is updated in the database

**Comment by elizase405** [comment]
As requested by Mark [here](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/76#issuecomment-2232514038), this article has been separated to this functionality.

**Comment by elizase405** [comment]
As requested, Naming has been reviewed to a consistent format of 'topic'

**Comment by CFCIfe** [comment]
Please take note and update your route

https://github.com/hngprojects/hng_boilerplate_nestjs/issues/111#issuecomment-2235907567

**Comment by mufidat3250** [comment]
Hi pls update the testing route too

**Comment by CollinDex** [comment]
Testing route updated as requested
