### ISSUE TITLE
[FEAT] Create API Endpoints to Retrieve User Profile Settings

### ISSUE THREAD

**Issue by F0laf0lu** [hngprojects/hng_boilerplate_nestjs#122]
## Description
Create an API endpoint to allow users to view their profile settings. The user must be signed in to view their details.
## Acceptance Criteria
- **Authentication**
   - The user must be signed in and provide a valid token to access the view endpoint.
   - If a user is not authenticated, the API should return a 401 Unauthorized error.
- **View Profile**
   - The API should return a JSON object with the current user's profile settings.
   - The response should include the following fields:
      - profile_picture
      - username
      - pronouns
      - job_title
      - department_team
      - email
      - bio
      - social_links
   - If the profile settings are retrieved successfully, the API should return a 200 OK status.
- **Response Formats**
   - **Successful View Profile Response**
     ```json
     {
       "profile_picture": "url/to/profile/picture",
       "username": "johndoe",
       "pronouns": "he/him",
       "job_title": "Software Engineer",
       "department_team": "Engineering",
       "email": "[johndoe@example.com](mailto:johndoe@example.com)",
       "bio": "Passionate developer.",
       "social_links": {
         "twitter": "https://twitter.com/johndoe",
         "linkedin": "https://linkedin.com/in/johndoe"
       }
     }
     ```
- **Error Handling**
   - **Unauthorized Access**
     ```json
     {
       "status": "error",
       "message": "Unauthorized access. Please sign in.",
       "status_code": 401
     }
     ```
## Purpose
Provide an endpoint for users to view their profile settings.
## Requirements
- [ ] Implement an endpoint to retrieve user profile settings.
  - [ ] `GET /api/v1/profile` to retrieve the current user's profile settings.
- [ ]  Ensure the endpoint handles authentication securely with token-based authentication.
  - [ ] Require users to be signed in and provide a valid token to access the endpoint.
  - [ ] Return `401 Unauthorized` if the user is not authenticated.
- [ ] Handle responses and errors appropriately.
  - [ ] Return `200 OK` with the user's profile settings on successful retrieval.
  - [ ] Return all error responses in JSON format with an `error` field containing a descriptive message.
## Unit Tests
- **GET /api/v1/profile Endpoint:**
  - Test that the endpoint returns the user's profile settings correctly.
  - Mock the data access layer to simulate different scenarios.
  - Verify that the response includes all expected fields (profile picture, username, pronouns, job title, etc.)
 ## End-to-End Tests

- Authenticated User:
   - Setup: Authenticate a test user.
   - Action: Send a GET request to /api/v1/profile.
   - Assertions: Verify 200 OK status.
   - Verify the response includes all expected fields.

- Unauthenticated User:
  - Setup: Ensure no user is authenticated.
  - Action: Send a GET request to /api/v1/profile.
  - Assertions: Verify 401 Unauthorized status.
  - Verify the response contains the correct error message.

- Profile Data Integrity:
  - Setup: Create and authenticate a test user.
  - Action: Send a GET request to /api/v1/profile.
  - Assertions: Verify 200 OK status.
  - Verify the response data matches the stored profile data.

## Expected Outcome
An API endpoint that enables users to view their profile settings seamlessly.

**Comment by Shullyd7** [comment]
API should be protected

**Comment by Dev-wonderful** [comment]
In the first requirement, update the endpoint to follow the convention

**Comment by Shullyd7** [comment]
Be consistent in versioning your endpoints

**Comment by highb33kay** [comment]
Success Response formatting is not standard
