### ISSUE TITLE
[FEAT]Implement Pagination for Get All Users Endpoint

### ISSUE THREAD

**Issue by Okeke12nancy** [hngprojects/hng_boilerplate_nestjs#123]
## Description

Create pagination functionality for the "Get All Users" API endpoint to handle large datasets more efficiently and improve performance.

## Acceptance Criteria

The endpoint should be accessible at GET /api/users.
The endpoint should accept query parameters for pagination:
page (integer): The page number to retrieve.
limit (integer): The number of users per page.
The endpoint should return paginated results, including metadata about the pagination.

Request Example:

### Purpose
GET /api/users?page=1&limit=10

Response:

On a successful retrieval of paginated users, the API should return a 200 OK status code. The response body should contain the list of users and pagination metadata:
{
  "status": "success",
  "data": {
    "users": [
      {
        "id": 1,
        "name": "User One",
        "email": "userone@example.com"
      },
      ...
    ],
    "pagination": {
      "currentPage": 1,
      "totalPages": 10,
      "totalItems": 100,
      "itemsPerPage": 10
    }
  }
}
Validation:

If the page or limit query parameters are missing or invalid, the API should return a 400 Bad Request status code with appropriate validation error messages:
{
  "status": "unsuccessful",
  "message": "Page and limit query parameters must be provided and valid"
}

### Purpose:

Provides efficient data retrieval and improves performance when handling large datasets by implementing pagination for the "Get All Users" endpoint.

### Requirements

- Develop server-side logic to handle pagination for the "Get All Users" endpoint.
- Ensure the page and limit query parameters are validated and handled correctly.
- Implement logic to calculate and return pagination metadata.	

### Expected Outcome

API endpoint returns paginated results for the "Get All Users" request with appropriate validation and metadata.

Tasks:

Define the GET /api/users route to handle pagination query parameters.
Validate the page and limit query parameters.
Implement logic to retrieve the specified page of users from the database.
Calculate and include pagination metadata in the response.
Handle cases where the query parameters are missing or invalid, providing appropriate error messages.

### Testing:

Write unit tests to validate input validation and pagination logic.
Write integration tests to ensure end-to-end functionality.
Perform performance testing to ensure efficiency with large datasets.

**Comment by markessien** [comment]
The user listting should naturally have pagination, its not a separate ticket
