### ISSUE TITLE
[FEAT] Delete existing products ENDPOINT: BACKEND

### ISSUE THREAD

**Issue by Uzo-Felix** [hngprojects/hng_boilerplate_nestjs#125]
Description
Develop an API endpoint to delete existing products with proper authentication and validation

Acceptance Criteria
* The endpoint should be accessible at `/api/v1/organizations/{id}/products/{id}`.
* The endpoint should accept HTTP `DELETE` requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can delete products.
* Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header. `Authorization: Bearer <token>`
* ***Request***
* The product ID should be included in the URL path.
* No request body is required.
* ***Response***
* On successful deletion of a product, the API should return a 204 No Content status code.
* If the product is not found, the API should return a 404 Not Found status code.
Explain

```
{
  "status_code": 404,
  "message": "Product not found",
}
```

* ***Error Handling***
* If the user is not authenticated, return a 401 Unauthorized status code.
* If the user does not have permission to delete products, return a 403 Forbidden status code.
* If there's a server error, return a 500 Internal Server Error status code.
Explain

```
{
  "status_code": 403,
  "message": "You do not have permission to delete this product",
}
```

Purpose
Provides a backend service which allows authorized users to delete products from the system
Requirements
* Develop server-side logic to delete an existing product.
* Ensure only users with appropriate permissions can delete products.
* Implement proper error handling and status code responses.
Expected Outcome
* API endpoint allows deletion of existing products with appropriate authentication and error handling

###Task
* Create an endpoint `DELETE /api/v1/organizations/{id}/products/{id}` to delete a product.
* Implement server-side logic to handle successful and failed delete product requests.
* Ensure the user has the proper permissions to delete products.
* Implement proper error handling for various scenarios (product not found, unauthorized access, etc.).
* Write unit tests for the delete product functionality.
* Write integration tests for deleting a product.
* Perform security testing to ensure only authorized users can delete products.

##Testing
* Write unit tests for the delete product logic.
* Write integration tests for the end-to-end delete product flow.
* Test various scenarios:
  - Deleting an existing product
  - Attempting to delete a non-existent product
  - Attempting to delete a product without authentication
  - Attempting to delete a product without proper permissions
* Perform security testing to ensure only authorized users can delete products.

**Comment by nedssoft** [comment]
@Uzo-Felix the objects do not conform to the accepted conventions

**Comment by Uzo-Felix** [comment]
> @Uzo-Felix the objects do not conform to the accepted conventions

Fixed

**Comment by thegirlSynth** [comment]
I hope you know you're working on a duplicate issue?

@Uzo-Felix

**Comment by Uzo-Felix** [comment]
> I hope you know you're working on a duplicate issue?
> 
> @Uzo-Felix

Please point me to the duplicate issue
