### ISSUE TITLE
[FEAT]: Profile Picture Update API Endpoint

### ISSUE THREAD

**Issue by VictorIborTech** [hngprojects/hng_boilerplate_nestjs#128]
## Description
Create an API endpoint to allow users to update their profile picture, integrating with the Files Service and Images Service.

## Acceptance Criteria

- The API endpoint (/api/v1/users/{userId}/profile-picture) correctly handles the update request and returns the expected response format.
- Unauthorized users cannot update profile pictures of other users.
- The profile picture update process completes within 5 seconds under normal network conditions.
- The Files Service handles the initial file upload.
- The Cloudinary Images Service processes the uploaded image, including compression and formatting.
- Upon confirmation, the new profile picture is immediately visible across all relevant sections of the application.

### Purpose
To provide users with the ability to personalize their account by uploading and updating their profile picture, which will enhancing user engagement and profile completeness.

### Requirements	

- [ ] Create the API endpoint for profile picture update.
- [ ] Validate file types and sizes.
- [ ] Integrate with Files Service for file upload and storage.
- [ ] Integrate with Images Service for image processing (compression and formatting).
- [ ] Ensure proper error handling for invalid file types, sizes, and unauthorized access.

#### Endpoint 

- Method: PUT
#### Request Payload
```
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="profile_picture.jpg"
Content-Type: image/jpeg

(binary data of the image file)
------WebKitFormBoundary7MA4YWxkTrZu0gW--

{
  "file": "(binary data of the image file)"
}
```

##### Success

- Status Code: 200 OK

```
json


Status Code: 200 OK
{
  "success": true,
  "message": "Profile picture updated successfully",
  "data": {
    "profile_picture_url": "https://example.com/images/user123_profile.jpg"
  }
}
``` 
##### Error

- 400 Bad Request: Invalid file type or size
```
{
  "error": {
    "code": "INVALID_FILE_TYPE",
    "message": "The uploaded file type is not supported.",
    "details": {
      "supported_types": ["image/jpeg", "image/png", "image/gif"],
      "provided_type": "image/tiff"
    }
  }
}
``` 
- 401 Unauthorized: User not authenticated
```
{
  "error": {
    "code": "AUTHENTICATION_REQUIRED",
    "message": "You must be logged in to perform this action.",
    "details": {
      "authentication_url": "/api/v1/auth/login"
    }
  }
}
``` 
- 403 Forbidden: User doesn't have permission to update this profile
```
{
  "error": {
    "code": "PERMISSION_DENIED",
    "message": "You don't have permission to update this profile picture.",
    "details": {
      "required_permission": "UPDATE_OWN_PROFILE",
      "target_user_id": 12345
    }
  }
}
``` 
- 500 Internal Server Error: Server-side error
```
{
  "error": {
    "code": "INTERNAL_SERVER_ERROR",
    "message": "An unexpected error occurred while processing your request.",
    "details": {
      "support_email": "support@example.com"
    }
  }
}
``` 

### Expected Outcome

- Users can successfully upload and update their profile picture.
- The new profile picture is displayed correctly across all relevant sections of the application.
- The system handles errors gracefully, providing clear messages to the user.
- The feature performs well, with quick upload and processing times.

#### Additional Information

- [ ] Ensure that the feature complies with data protection regulations regarding user data and image storage.
- [ ] Coordinate with the Files Service and Images Service teams to ensure proper integration
- [ ] Consider implementing a caching mechanism

#### Testing

- Perform a manual test and test API endpoint response structure
- Perform security testing to ensure data protection and compliance:
- Write integration tests for the end-to-end profile picture update:

**Comment by phurhard** [comment]
Version your endpoint
What's the file service and image service?? 
Should there be a need for an error id??

**Comment by Shullyd7** [comment]
Show the request payload also

**Comment by phurhard** [comment]
Check this issues
#122 #83 #31 your all doing same thing?

**Comment by mjoghenemaega** [comment]
> Check this issues #122 #83 #31 your all doing same thing?

omo , seems, one has to create a new issue at this point
