### ISSUE TITLE
[FEAT] Implement Super Admin Management Endpoints

### ISSUE THREAD

**Issue by kingdavidHub** [hngprojects/hng_boilerplate_nestjs#130]
### Description

Implement features specific to super admin users, enabling them to manage all organizations and users across the system. This includes creating, updating, and deleting organizations and users, as well as viewing detailed information about them.

### Acceptance Criteria

1. Implement API endpoints for:
- [ ] Creating, updating, and deleting organizations
- [ ]  Creating, updating, and deleting users
- [ ]  Viewing detailed information about organizations and users

- [ ]  Ensure secure handling of super admin privileges.
- [ ] Implement robust error handling and logging.
- [ ] Provide comprehensive test coverage for all scenarios (e.g., successful operations, authorization errors). 

### Purpose

Allow super admin users to manage the system effectively, ensuring they can perform administrative tasks related to organizations and users.

### Requirements

**Requirements:**

1. **Super Admin Privileges:**
   - Verify super admin status before allowing access to these endpoints.
   - Implement secure handling of super admin credentials and permissions.

2. **API Endpoints:**

   - **POST v1/api/superadmin/organizations:** Create a new organization.
   - **PUT v1/api/superadmin/organizations/{organizationId}:** Update organization details.
   - **DELETE v1/api/superadmin/organizations/{organizationId}:** Delete an organization.
   - **GET v1/api/superadmin/organizations:** List all organizations.
   - **GET v1/api/superadmin/organizations/{organizationId}:** View details of a specific organization.
   
   - **POST v1/api/superadmin/users:** Create a new user.
   - **PUT v1/api/superadmin/users/{userId}:** Update user details.
   - **DELETE v1/api/superadmin/users/{userId}:** Delete a user.
   - **GET v1/api/superadmin/users:** List all users.
   - **GET v1/api/superadmin/users/{userId}:** View details of a specific user.

3. **Security and Compliance:**
   - Implement robust error handling and logging.
   - Ensure secure handling of sensitive information.

4. **Testing and Documentation:**
   - Write unit and integration tests.
   - Cover various scenarios (successful operations, authorization errors).
   - Update documentation with API usage and integration details.

#### Organizations

**Description:** Create a new organization  
**Endpoint:** `POST v1/api/superadmin/organizations`

**Request Body:**

```json
{
  "name": "string",
  "description": "string"
}
```

**Response (Success):**

```json
{
  "organizationId": "string",
  "status": "created",
  "status_code": 201
}
```

**Description:** Update organization details  
**Endpoint:** `PUT v1/api/superadmin/organizations/{organizationId}`

**Request Body:**

```json
{
  "name": "string",
  "description": "string"
}
```

**Response (Success):**

```json
{
  "status": "updated",
  "status_code": 200
}
```

**Description:** Delete an organization  
**Endpoint:** `DELETE v1/api/superadmin/organizations/{organizationId}`

**Response (Success):**

```json
{
  "status": "deleted",
  "status_code": 200
}
```

**Description:** List all organizations  
**Endpoint:** `GET v1/api/superadmin/organizations`

**Response (Success):**

```json
[
  {
    "organizationId": "string",
    "name": "string",
    "description": "string",
    "created_at": "timestamp"
  },
  ...
]
```

**Description:** View details of a specific organization  
**Endpoint:** `GET v1/api/superadmin/organizations/{organizationId}`

**Response (Success):**

```json
{
  "organizationId": "string",
  "name": "string",
  "description": "string",
  "created_at": "timestamp"
}
```

#### Users

**Description:** Create a new user  
**Endpoint:** `POST v1/api/superadmin/users`

**Request Body:**

```json
{
  "first_name": "string",
  "last_name": "string",
  "email": "string",
  "password": "string",
  "phone": "string"
}
```

**Response (Success):**

```json
{
  "userId": "string",
  "status": "created",
  "status_code": 201
}
```

**Description:** Update user details  
**Endpoint:** `PUT v1/api/superadmin/users/{userId}`

**Request Body:**

```json
{
  "first_name": "string",
  "last_name": "string",
  "email": "string",
  "phone": "string"
}
```

**Response (Success):**

```json
{
  "status": "updated",
  "status_code": 200
}
```

**Description:** Delete a user  
**Endpoint:** `DELETE v1/api/superadmin/users/{userId}`

**Response (Success):**

```json
{
  "status": "deleted",
  "status_code": 200
}
```

**Description:** List all users  
**Endpoint:** `GET v1/api/superadmin/users`

**Response (Success):**

```json
[
  {
    "userId": "string",
    "first_name": "string",
    "last_name": "string",
    "email": "string",
    "phone": "string",
    "created_at": "timestamp"
  },
  ...
]
```

**Description:** View details of a specific user  
**Endpoint:** `GET v1/api/superadmin/users/{userId}`

**Response (Success):**

```json
{
  "userId": "string",
  "first_name": "string",
  "last_name": "string",
  "email": "string",
  "phone": "string",
  "created_at": "timestamp"
}
```

#### Create Organization

**Test Case:** Create a new organization with valid data  
**Endpoint:** `POST v1/api/superadmin/organizations`

**Request Body:**

```json
{
  "name": "New Org",
  "description": "A new organization"
}
```

**Expected Response:**

```json
{
  "organizationId": "string",
  "status": "created",
  "status_code": 201
}
```

#### Update Organization

**Test Case:** Update organization details with valid data  
**Endpoint:** `PUT v1/api/superadmin/organizations/{organizationId}`

**Request Body:**

```json
{
  "name": "Updated Org",
  "description": "Updated description"
}
```

**Expected Response:**

```json
{
  "status": "updated",
  "status_code": 200
}
```

#### Delete Organization

**Test Case:** Delete an organization with a valid ID  
**Endpoint:** `DELETE v1/api/superadmin/organizations/{organizationId}`

**Expected Response:**

```json
{
  "status": "deleted",
  "status_code": 200
}
```

#### List Organizations

**Test Case:** List all organizations  
**Endpoint:** `GET v1/api/superadmin/organizations`

**Expected Response:**

```json
[
  {
    "organizationId": "string",
    "name": "string",
    "description": "string",
    "created_at": "timestamp"
  },
  ...
]
```

#### Create User

**Test Case:** Create a new user with valid data  
**Endpoint:** `POST v1/api/superadmin/users`

**Request Body:**

```json
{
  "first_name": "John",
  "last_name": "Doe",
  "email": "john.doe@example.com",
  "password": "securepassword",
  "phone": "1234567890"
}
```

**Expected Response:**

```json
{
  "userId": "string",
  "status": "created",
  "status_code": 201
}
```

#### Update User

**Test Case:** Update user details with valid data  
**Endpoint:** `PUT v1/api/superadmin/users/{userId}`

**Request Body:**

```json
{
  "first_name": "Jane",
  "last_name": "Doe",
  "email": "jane.doe@example.com",
  "phone": "0987654321"
}
```

**Expected Response:**

```json
{
  "status": "updated",
  "status_code": 200
}
```

#### Delete User

**Test Case:** Delete a user with a valid ID  
**Endpoint:** `DELETE v1/api/superadmin/users/{userId}`

**Expected Response:**

```json
{
  "status": "deleted",
  "status_code": 200
}
```

#### List Users

**Test Case:** List all users  
**Endpoint:** `GET v1/api/superadmin/users`

**Expected Response:**

```json
[
  {
    "userId": "string",
    "first_name": "John",
    "last_name": "Doe",
    "email": "john.doe@example.com",
    "phone": "1234567890",
    "created_at": "timestamp"
  },
  ...
]
```

### Implementation Notes

- Ensure to handle super admin authentication securely.
- Implement detailed logging for actions performed by super admins.
- Provide clear error messages and status codes for failed operations.
- Ensure compliance with data protection regulations when handling sensitive information.

**Comment by markessien** [comment]
out of scope
