### ISSUE TITLE
[FEAT]: Fetch Customer List Endpoint - Backend

### ISSUE THREAD

**Issue by EmmanuelOmoiya** [hngprojects/hng_boilerplate_nestjs#133]
## Description
Develop an API endpoint to fetch a list of customers.

## Acceptance Criteria
- The endpoint should be accessible at `/api/v1/customers?limit=10&page=1`.
- The endpoint should return a paginated response with an `array` of customer objects each containing `first_name`, `last_name`, `email`, `phone_number` and `organisations` array containing the organisations uuid.
- The endpoint should accept HTTP `GET` requests.
- The endpoint should be secured to ensure that only a user with an admin role can fetch the list of customers.
- Proper authentication mechanisms (e.g., JWT, OAuth2, SAML) should be implemented.
- Requests to the endpoint must include a valid authentication token in the Authorization header. `Authorization: Bearer <token>`
- Response (Success)
```sh
{
"status_code": 200,
"current_page": 1,
"total_pages": 20,
"limit": 10,
"total_items": 202,
"data":
[
  {
     "first_name": "Emmanuel",
     "last_name": "xxxxxxxxxxx",
     "phone_number": "xxxxxxxxxxx",
     "organisations": ["xxxxxxxxxxxx", "xxxxxxxxxxx", "xxxxxxxxxxxx"]
  }
  ...
]
}
```

- Response (Error)
```sh
{
  "status_code": 401,
  "message": "Unauthorized",
  "error": "Bad Request"
}
```

Internal Sever Error
```sh
{
  "error": Bad Request,
  "message": "Internal server error",
  "status_code": 500
}
```

### Purpose
To fetch the list of customers in the Database

### Requirements	
- [ ] User must be authenticated thereby having a `Authorization: Bearer <token>` header in the request body
- [ ] User must have the role of an admin
- [ ] User account must be active
- [ ] User must indicate the limit number and page number 

### Expected Outcome
- [ ] A paginated response with array of customers object where each customer object contains `first_name`, `last_name`, `email`, `phone_number` and `organisations` array containing the organisations uuid.

### Testing
1. Unit Tests
The systems should have unit tests covering:

 - [ ] Ensure data is fetched correctly from the database.
 - [ ] Test that the appropriate response and status code is returned

**Comment by Dev-wonderful** [comment]
Check the convention you were asked to follow

**Comment by EmmanuelOmoiya** [comment]
Updated as expected @Dev-wonderful

**Comment by EmmanuelOmoiya** [comment]
@NdubuisiJr
