### ISSUE TITLE
[FEAT] - External Dynamic pages - Job Listings - Retrieve All Job Listings

### ISSUE THREAD

**Issue by donfortune** [hngprojects/hng_boilerplate_nestjs#145]
### Description
Implement a feature to retrieve all job listings from the database. This endpoint should provide a list of all job listings, supporting pagination to handle large datasets.

### Acceptance Criteria

**Retrieve All Job listings Endpoint [GET] /api/v1/jobs**

**Retrieve All Job listings:**
- Given a request to retrieve all job listings, when the request is made, the system should return a paginated list of job listings.
- The response should include metadata for pagination such as total pages and current page.
- The response should be returned in a timely manner.

### Expected Outcome
The system should return a paginated list of all job listings, upon receiving a valid request.

### Request

**[GET] /api/v1/jobs?page=Int&size=Int**

### Successful Response
```json
{
  "message": "Job listings retrieved successfully.",
  "data": [
    {
      "title": "String",
      "description": "String",
      "location": "String",
      "salary": "String",
      "job_type": "String",
      
    },
    
  ],
  "pagination": {
    "current_page": "Int",
    "total_pages": "Int",
    "page_size": "Int",
    "total_items": "Int"
  }
}
```

### ErrorResponse
```json 
{
  "message": "Failed to retrieve job listings.",
  "error": "String",
  "status_code": "Int"
} 
```

**Comment by buka4rill** [comment]
@donfortune it's `status_code` not `statusCode`

**Comment by donfortune** [comment]
@buka4rill  fixed

**Comment by donfortune** [comment]
Team Members Who Are Working On This Issue:
[Donfortune](https://github.com/donfortune)  -> SlackID(@osowoayi obi) -> Python/FatApi
[Timiajayi](https://github.com/TimiAjayi) -> SlackID(@Timiajayi) -> PHP/Laravel
[Shedrack](https://github.com/Solution-Driver) -> SlackID(@shedrack Alita) -> Nodejs/Nextjs
