### ISSUE TITLE
[FEAT] Get Organisation by ID Endpoint

### ISSUE THREAD

**Issue by Okeke12nancy** [hngprojects/hng_boilerplate_nestjs#147]
## Description

Implement a 'Get Organization by ID' functionality where users can retrieve details of an organization they belong to by its ID

## Acceptance Criteria

The endpoint should be accessible at GET /api/v1/organisations/:orgId.
The endpoint should accept HTTP GET requests.
The endpoint should retrieve the organisation details from the database using the provided organisation ID.
The endpoint should return a 200 OK status code with the organisation details in the response body.
Request Example:

GET /api/v1/organisations/123

**Response:**

On a successful retrieval of the organisation details, the API should return a 200 OK status code. The response body should contain the organisation details:

```json
{
  "status": "success",
  "status_code": 200

  "data": {
    "id": 123,
    "name": "Organisation Name",
    "address": "123 Street, City, Country",
    "email": "contact@organisation.com",
    "created_at": "2023-01-01T12:00:00Z",
    "updated_at": "2023-06-01T12:00:00Z"
  }
}
```

**Validation:**

If the organisation ID is missing or invalid, the API should return a 400 Bad Request status code with appropriate validation error messages:

```json

{
  "status": "unsuccessful",
 "status_code": 400,
  "message": "Valid organisation ID must be provided"
}
```
If the organisation does not exist, the API should return a 404 Not Found status code with an appropriate message:

```json
{
  "status": "unsuccessful",
 "status_code": 404,
  "message": "Organisation not found"
}

```

### Purpose

Provides a secure backend service that allows users to retrieve organisation details by ID

### Requirements	
Develop server-side logic to retrieve organisation details by ID.
Securely handle the retrieval process and comply with security standards.
Ensure that the organisation ID is validated and handled correctly.

### Expected Outcome
API endpoint allows users to retrieve organisation details by ID with appropriate validation and security measures.

Tasks:

- Define the GET /api/v1/organisations/:orgId route in the server-side application.
- Validate that the organisation ID is provided and is in a valid format.
- Implement logic to retrieve the organisation details from the database using the provided ID.
- Return the organisation details in the response body if the ID is valid and the organisation exists.
- Handle cases where the organisation ID is invalid or the organisation does not exist, providing appropriate error messages.

### Testing
- Write unit tests to validate input validation and organisation retrieval logic.
- Write integration tests to ensure end-to-end functionality.
- Perform security testing to ensure data protection and compliance.

**Comment by markessien** [comment]
You can only retrieve org ids of orgs you are part of

**Comment by Okeke12nancy** [comment]
Okay, noted.

**Comment by buka4rill** [comment]
@Okeke12nancy look at [this](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/140) issue's description and compare it with yours

**Comment by jovialcore** [comment]
Can you do a little formatting for the Section that demonstrates the API returned?

**Comment by jovialcore** [comment]
```json
{
"status": "success",
"data": {
"id": 123,
"name": "Organisation Name",
"address": "123 Street, City, Country",
"email": "contact@organisation.com",
...
}
}
Validation:

If the organisation ID is missing or invalid, the API should return a 400 Bad Request status code with appropriate validation error messages:
{
"status": "unsuccessful",
"message": "Valid organisation ID must be provided"
}
If the organisation does not exist, the API should return a 404 Not Found status code with an appropriate message:
{
"status": "unsuccessful",
"message": "Organisation not found"
}

```

**Comment by jovialcore** [comment]
Something like this :

```json 

{
"status": "success",
"data": {
"id": 123,
"name": "Organisation Name",
"address": "123 Street, City, Country",
"email": "contact@organisation.com",
} 

```

**Comment by jovialcore** [comment]
![Screenshot_20240717-213816](https://github.com/user-attachments/assets/796ebdbb-7c6d-4792-a018-11bbc3f0d254)
Use this screenshot illustration for your markdown for json/code samples...

**Comment by jovialcore** [comment]
Check your spelling where you have requirements

**Comment by pesova** [comment]
@Okeke12nancy how about the versioning

**Comment by Okeke12nancy** [comment]
Hello @pesova @jovialcore @buka4rill , I have made the necessary corrections, please go through it again for the last time.

**Comment by jovialcore** [comment]
Seen. What about the status code ?

**Comment by mufidat3250** [comment]
I want to ask a question 
   I submitted this ticket for my group that we will be working on it 
   i want o ask if their is another group working on this

**Comment by Okeke12nancy** [comment]
@mufidat3250 , this group is working on it already

**Comment by Okeke12nancy** [comment]
@jovialcore , done

**Comment by mufidat3250** [comment]
what is the name of your group

**Comment by mufidat3250** [comment]
I mean your team

**Comment by Okeke12nancy** [comment]
> what is the name of your group

team 5

**Comment by mufidat3250** [comment]
is your  team name  on the exel sheet

**Comment by Okeke12nancy** [comment]
> is your team name on the exel sheet

yes, it is.

**Comment by jovialcore** [comment]
One more thing, add a timestamps: 

created_at
updated_at 

to as part of the response returned in the organisation's body

**Comment by Okeke12nancy** [comment]
@jovialcore Done

**Comment by Okeke12nancy** [comment]
Team Members:
Nancy(Team Lead) - Nest.js
Bisola Abdulsalam - Python
Otuekong Aniedi- Laravel
Moses Johnson  Oghenemaega-  C#
Nathaniel nwabueze- Golang
