### ISSUE TITLE
[FEAT] Implement API Endpoint for User Password Reset

### ISSUE THREAD

**Issue by kihuni** [hngprojects/hng_boilerplate_nestjs#150]
## Description
Develop a secure RESTful API endpoint for user password reset functionality.

## Purpose
Implement endpoints to facilitate secure password updates for users who have forgotten their passwords or suspect their credentials have been compromised.

## Requirements
1. Validate the format and strength of the new password to meet security criteria (e.g., minimum length, complexity).
2. Use a strong hashing algorithm like bcrypt to securely hash user passwords before storing them in the database.

### Authentication
- The user must provide a valid reset token to access the password reset endpoint.
- If the reset token is invalid or expired, the API should return a 400 Bad Request error.

### Password Reset
- The API should accept the user's email, new password, and reset token.
- The new password must meet the defined security criteria.

#### Successful Password Update Response
- **Status Code**: 200 OK
- **Message**: Password updated successfully.
- **Example**:
  ```json
  {
    "status": "success",
    "message": "Password updated successfully.",
    "status_code": 200
  }
  ```

#### Invalid Input or Token Response
- **Status Code**: 400 Bad Request
- **Message**: Invalid input or token.
- **Example**:
  ```json
  {
    "status": "error",
    "message": "Invalid input or token.",
    "status_code": 400
  }
  ```

#### User Not Found Response
- **Status Code**: 404 Not Found
- **Message**: User not found.
- **Example**:
  ```json
  {
    "status": "error",
    "message": "User not found.",
    "status_code": 404
  }
  ```

#### Server Error Response
- **Status Code**: 500 Internal Server Error
- **Message**: Server error during processing.
- **Example**:
  ```json
  {
    "status": "error",
    "message": "Server error during processing.",
    "status_code": 500
  }
  ```

### Input Validation
- Validate that all required fields (`email`, `newPassword`, `resetToken`) are present in the request body.
- Ensure the `newPassword` meets the defined strength criteria (e.g., minimum length, complexity).

### Token Validation
- Verify that the reset token is valid and not expired.
- Check that the reset token matches the user’s email.

### User Lookup
- Ensure the user exists in the database using the provided email.

### Password Hashing
- Use bcrypt to hash the new password.
- Ensure the bcrypt configuration (e.g., salt rounds) meets security standards.

### Password Update
- Update the user’s password in the database with the hashed password.

### Security Best Practices
- Implement HTTPS to secure data in transit.
- Implement rate limiting to prevent brute force attacks.
- Log and monitor password reset attempts for suspicious activity.

### Notifications and Logs
- Send an email notification to the user upon successful password update.
- Maintain audit logs of password reset requests for forensic purposes.

### POST /api/password-reset Endpoint
- Test that the endpoint processes the password reset request correctly.
- Mock the data access layer to simulate different scenarios.
- Verify that the response includes appropriate status codes and messages for various outcomes (successful update, invalid input, user not found, server error).

**Comment by markessien** [comment]
Read your ticket
