### ISSUE TITLE
[FEAT] COMMENT FUNCTIONALITY - BACKEND

### ISSUE THREAD

**Issue by samsmithKruz** [hngprojects/hng_boilerplate_nestjs#151]
## Description
Implement a feature that allows users to add comments to individual posts.

## Acceptance Criteria
1. **Database Schema**
   - Design and create a database schema for storing comments.
   - Ensure the schema links comments to respective contents using the model name.

2. **API Endpoints**
   - Create an endpoint to add a new comment accessible at `/api/v1/comments/add`.
   - The endpoint should accept POST requests to receive comment data.
   - Given a POST request with comment data, the system should validate and sanitize the incoming data.

3. **Validation Rules**
   - Required fields: `item_id`, `model_name`, `comment`.
   - `comment` should be a non-empty string.
   - `item_id` and `model_name` should be valid IDs and model name (table) referencing existing contents and users.

4. **Database Storage**
   - Given valid comment data, the endpoint should securely store the information in the database.

5. **Error Handling**
   - The system should handle errors gracefully and return appropriate status codes.

### Request Header
  ```json
  {
      "Authorization": "Bearer your_jwt_token_here"
  }
  ```
### Request Body

```json
{
  "item_id": 123,
  "model_name": "Blog | content | post",
  "comment": "This is a comment."
}
```

#### Successful Response (status code: 201)
```json
{
  "message": "Comment added successfully!"
}
```
#### Error Response
```json
{
  "message": "Invalid input data",
  "status_code": 400,
  "error": "Bad Request"
}
```

## Purpose
To enhance user engagement by allowing interaction through comments.

### Requirements
- Create a database schema for storing comments.
- Develop API endpoints for adding comments.
- Ensure comments are linked to respective contents and users.

### Expected Outcome
- Users can add comments on contents, posts and blogs.

### Testing
- Test that the endpoint returns a 201 status code with a success message on valid submissions.
- Test that invalid data triggers a 400 Bad Request response with an appropriate error message.
- Test that comments are correctly linked to their respective blog posts and users.
- Test that the rate-limiting works correctly and returns the appropriate status code when exceeded.

### Checklist
- Design and implement the comments database schema.
- Develop API endpoints for comment management.
- Write unit and integration tests for comment functionality.

**Comment by markessien** [comment]
Comments are to be generic and attachable to any model

**Comment by samsmithKruz** [comment]
Alright sir, I've updated the schema such that comments are now generic, the model or schema to which the comment is made will be passed in the "Request Body" as model_name

**Comment by MuthoniMN** [comment]
@highb33kay
@Ameenah-Ameenah
@highb33kay @prondubuisi

Please approve this ticket. Thank you
