### ISSUE TITLE
[FEAT] Role-Based Access Control (RBAC) 

### ISSUE THREAD

**Issue by Thelma101** [hngprojects/hng_boilerplate_nestjs#153]
**Description:**
Develop and integrate a minimalistic Role-Based Access Control (RBAC) system into the application to manage user permissions and access levels. This system will allow different roles to have specific permissions, ensuring that users can only access the resources and perform the actions they are authorized to.

**Acceptance Criteria:**
1. Define roles with permissions in the database.
2. Implement middleware to check user roles and permissions before accessing endpoints.
3. Create endpoints to manage roles and permissions.
4. Ensure that all existing endpoints are secured based on user roles and permissions.
5. Provide documentation for managing roles and using the RBAC system.

**Purpose:**
To enhance application security by ensuring that users have appropriate access levels. This prevents unauthorized access to sensitive resources and actions, improving overall system security and compliance.

**Requirements:**
- Define a database schema for roles with embedded permissions and user roles.
- Implement middleware for role and permission checks.
- Develop endpoints for managing roles and permissions.
- Update existing endpoints to include RBAC checks.
- Ensure proper error handling and feedback for unauthorized access attempts.
- Provide comprehensive documentation for the RBAC system.

**Expected Outcome:**
- Users have access only to the resources and actions they are authorized for.
- Administrators can manage roles and permissions easily.
- The application is more secure and compliant with access control best practices.
- Clear documentation is available for developers and administrators to use the RBAC system effectively.

**Define Roles and Permissions in the Database**

- Request

{
  "name": "admin",
  "permissions": ["create_user", "delete_user", "update_user", "view_user"
}

- Response

{
  "id": 1,
  "name": "admin",
  "permissions": ["create_user", "delete_user", "update_user", "view_user"],
  "created_at": "2024-07-17T12:00:00Z",
  "updated_at": "2024-07-17T12:00:00Z"
}

**Assign Role to a User**

- Request

{
  "user_id": 1,
  "role_id": 1
}

- Response
{
  "user_id": 1,
  "role_id": 1
}

**Comment by markessien** [comment]
This is a complex ticket that many other tickets are dependent on, and should be done by someone experienced

**Comment by highb33kay** [comment]
How are the permissions assigned?
How are the permissions created?

will there be an endpoint for all that?

Permission should use IDs and not names, meaning permission should have their own table in the data base with a structure such as Description, name, id etc. 

Then the permissions should be assigned to a specific role via an end point by calling the ID of that particular permission. 

`"permissions": [1, 2,3,4]`
