### ISSUE TITLE
[FEAT]: API Endpoint to Retrieve User's Organization 

### ISSUE THREAD

**Issue by Hardeezah** [hngprojects/hng_boilerplate_nestjs#154]
## Description
A backend API endpoint that allows users to retrieve all organizations they belong to by providing their user ID. This endpoint supports pagination to handle large lists of organizations. 
## Acceptance Criteria
1. Endpoint:

Method: GET
URL: /api/v1/users/:user_id/organisations
2. Request:

- The request must include a valid JWT token in the Authorization header.
- The user ID (user_id) should be specified as a URL parameter.
- Pagination:
- Query parameters for pagination:
    page (default: 1) - The page number to retrieve.
    limit (default: 10) - The number of organizations per page.

3. Response:

On success with organizations:

```
{
  "status": "success",
  "message": "Organizations retrieved successfully",
  "data": {
    "organisations": [
      {
        "org_id": "string",
        "name": "string",
        "description": "string"
      }
    ],
    "pagination": {
      "total_items": 100,
      "total_pages": 10,
      "current_page": 1,
      "page_size": 10
    }
  }
}
```
On success with no organizations:

```
{
  "status": "success",
  "message": "No organizations found for the user",
  "data": {
    "organisations": [],
    "pagination": {
      "total_items": 0,
      "total_pages": 0,
      "current_page": 1,
      "page_size": 10
    }
  }
}
```
On error (e.g., user not found, unauthorized access):

```
{
  "status": "error",
  "message": "Unauthorized access or user not found",
  "status_code": 404
}
```
4. Validation:

- Ensure the user_id exists and is valid.
- Validate the JWT auth token.
- Validate the page and limit query parameters.

5. Purpose:
To allow users to retrieve a list of all organizations they belong to, with support for pagination to handle large datasets. 

### Expected Outcome:
A fully functional backend API endpoint that allows users to retrieve all organizations they belong to by their user ID, with pagination support. If the user does not belong to any organizations, the response should reflect that no organizations were found.

### Tasks:

- Implement the GET endpoint to retrieve all organizations a user belongs to, with pagination support.
- Validate inputs and handle errors properly.
- Write unit tests for the endpoint to ensure it handles valid and invalid inputs correctly.

### Test Scenarios:

- Retrieve organizations successfully with valid user ID, JWT token, and pagination parameters.
- Successfully handle case where user belongs to no organizations.
- Fail to retrieve organizations with invalid user ID.

**Comment by markessien** [comment]
Is this not duplicated?

**Comment by Hardeezah** [comment]
no it is not

**Comment by ugberaeseac** [comment]
it is duplicated, we already worked on this and Mark Issue no #52

**Comment by Okeke12nancy** [comment]
@markessien , this is duplicated actually. I am worked on this already

**Comment by Hardeezah** [comment]
@Okeke12nancy what issue number?

**Comment by Hardeezah** [comment]
@Okeke12nancy what issue number?

**Comment by Okeke12nancy** [comment]
@Hardeezah what is the difference?

If I remove the id, it will return everything, so what's the difference?

**Comment by Shullyd7** [comment]
Seems you have a disagreement, have you settled it?

**Comment by Hardeezah** [comment]
yes i have

**Comment by Hardeezah** [comment]
This issue is not a duplicate of #147 
#147 retrieves details of a single organization by its ID and this retrieves a list of organizations a user belongs

**Comment by Shullyd7** [comment]
Okay, add versioning to your endpoint

**Comment by Hardeezah** [comment]
okay i will

**Comment by Hardeezah** [comment]
done @Shullyd7

**Comment by Hardeezah** [comment]
Team X
Slack Id: Hardeezah (team lead) - Nodejs
Slack Id: Myles- FastAPI
Slack Id: davistheweb -PHP
