### ISSUE TITLE
[FEAT] - Generate Timeline Graph From Product Information - Backend

### ISSUE THREAD

**Issue by Trojanhorse7** [hngprojects/hng_boilerplate_nestjs#155]
## Description

Develop an API endpoint to generate timeline graph from the product information

## Acceptance Criteria

- The endpoint should be accessible at api/v1/products/timeline-graph 
- The endpoint should accept HTTP POST requests.
- Only admins can create new teams.
- Proper authentication mechanisms (e.g. JWT) should be implemented.
- Requests to the endpoint must include a valid authentication token in the Authorization header. Authorization: Bearer <token>

### Request Parameters

  - productId (required): The ID of the product for which the timeline graph is to be generated.
  - startDate (required): The start date for filtering events.
  - endDate (required): The end date for filtering events.
  - description(optional): The description of the product.

- **Response**
**Success Response:**
On a successful generation of the timeline graph, the API should return a 201 OK status code with the timeline graph data.

```
{
  "status_code": 200,
  "timeline_graph": {
    "product_id": 1,
    "product_name": "Product Name",
    "description": "Product Description",
    "events": [
      {
        "date": "2024-01-01T00:00:00Z",
        "name": "Event Name",
        "description": "Event Description"
      },
      {
        "date": "2024-02-01T00:00:00Z",
        "name": "Another Event Name",
        "description": "Another Event Description"
      }
    ]
  }
}
```

- **Error Responses:**
**Validation Errors:**
If any required field is missing or invalid, the API should return a 422 status code with appropriate validation error messages.

```
{
  "status_code": 422,
  "error": [
    {
      "field": "product_name",
      "message": "Product Name is required"
    }
  ]
}
```

- **Unauthorized Access:**
If the user is not an admin, the API should return a 403 Forbidden status code.

```
{
  "status_code": 403,
  "error": "Forbidden",
  "message": "User does not have the required permissions to generate a product-timeline."
}
```

- Internal Server Error:
If an unexpected error occurs, the API should return a 500 Internal Server Error status code.

```
{
  "status_code": 500,
  "error": "Internal Server Error",
  "message": "An unexpected error occurred. Please try again later."
}
```

### Purpose

Provides a backend service that allows admins to generate product timeline from product information

### Requirements	

- Develop server-side logic to generate a timeline graph for a product within a specified date range.
- Securely retrieve product events and milestones from the database.
- Ensure compliance with security standards for handling user information.

### Expected Outcome

- API endpoint allows generating a product timeline graph with appropriate validation.
- Appropriate status codes and error messages are returned based on the outcome of the request.

### Task

- Create an endpoint GET api/v1/products/timeline-graph to generate a timeline graph for a specific product within a specified date range.
- Implement server-side logic to handle successful and failed timeline graph generation requests.
- Write unit tests for generating a timeline graph.
- Write integration tests for generating a timeline graph.
- Perform security testing to ensure data protection and compliance.

### Testing

**Successful Timeline Graph Generation:**

Ensure that the endpoint successfully generates a timeline graph for a product within the specified date range.
Verify that the response includes the product ID, name, description, and events.
Confirm that the status code is 200 OK.

**Validation Errors:**

Test scenarios with missing or invalid productId, startDate, or endDate in the request parameters.
Verify that the endpoint returns a 400 Bad Request status code with appropriate error messages.

**Unauthorized Access:**

Test scenarios where the user is not an admin.
Verify that the endpoint returns a 403 Forbidden status code.

**Internal Server Error:**

Simulate an internal server error to raise an exception.
Verify that the endpoint returns a 500 Internal Server Error status code.

### Database diagram
![db img](https://github.com/user-attachments/assets/473909a6-0f0c-410b-a4df-2497654cf200)

**Comment by markessien** [comment]
We do not have a concept like "teams" in this app

**Comment by markessien** [comment]
You need to be clear on what exactly will be graphed.
