### ISSUE TITLE
[FEAT] Implement User Profile Settings Update API Endpoint

### ISSUE THREAD

**Issue by Ukeme-Edet** [hngprojects/hng_boilerplate_nestjs#156]
### Description
Implement a RESTful API endpoint to handle partial updates of user profile settings. This endpoint will allow authenticated users to modify specific parts of their profile information, such as name, email, or preferences. User preferences will be stored as a JSON field in the user table of the database.

### Acceptance Criteria
API Endpoint Implementation:
* The endpoint should be accessible at `/api/v1/users/:id`.
* The endpoint should accept HTTP PATCH requests.

Data Validation and Authorization:
* Validate that the user making the request is authenticated.
* Validate the incoming data for correctness and security.

Updating User Profile:
* Upon successful validation, update the user's profile information in the database.
* Ensure that critical fields (e.g., email) trigger appropriate verification processes if changed.

Response:
* On success, return a 200 OK status code with the updated profile information.
* On failure, return appropriate error codes with descriptive messages.

#### Request Example:
PATCH `/api/users/profile`
```json
{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "preferences": {
    "newsletter": true,
    "darkMode": false
  }
}
```
Successful Response:
```json
{
  "message": "Profile updated successfully",
  "user": {
    "name": "John Doe",
    "email": "existing.email@example.com",
    "preferences": {
      "newsletter": true,
      "darkMode": false
    }
  },
  "status": 200
}
```
Error response:
- Unauthorised Response:
```json
{
  "message": "Authentication required",
  "status_code": 401
}
```
- Invalid Data:
```json
{
  "message": "Unable to update profile",
  "errors": [
    "Name must be at least 2 characters long"
  ],
  "status_code": 400
}
```
- Email Already in Use:
```json
{
  "message": "Unable to update profile",
  "errors": [
    "Email address already in use"
  ],
  "status_code": 409
}
```
Server Error:
```json
{
  "message": "Internal server error",
  "status_code": 500
}
```

#### Purpose
Provide a secure and efficient backend service for users to update specific parts of their profile settings, ensuring data validation and maintaining user information integrity.

#### Requirements
- [ ] Develop server-side logic to handle partial profile update requests.
- [ ] Implement data validation for incoming profile information.
- [ ] Update the user model to include a JSON field for storing preferences.
- [ ] Create database queries for updating only the provided user profile fields, including the JSON preferences field.
- [ ] Design and implement error handling for various scenarios.
- [ ] Ensure proper handling of sensitive information updates (e.g., email changes).

#### Database Schema
```sql
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    preferences JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);
```

![image](https://github.com/user-attachments/assets/048a8ae6-d802-48fe-a92d-342598b561f7)

#### Expected Outcome
A fully functional API endpoint that securely handles partial user profile updates, maintaining data integrity and providing clear feedback on the success or failure of update attempts.

#### Status Codes:
- 200: Profile updated successfully.
- 400: Bad request (e.g., invalid data format).
- 401: Unauthorized (user not authenticated).
- 409: Conflict (e.g., email already in use).
- 500: A server error occurred.

#### Testing
- [ ] Verify correct handling of authenticated and unauthenticated requests.
- [ ] Test successful partial updates of user profile information.
- [ ] Ensure proper error responses for invalid input data.

**Comment by markessien** [comment]
this is unclear how preferences are stored. Are they in a different table from the user model?

**Comment by Ukeme-Edet** [comment]
@markessien The preferences will be stored as a JSON field within the user table

**Comment by Ukeme-Edet** [comment]
@markessien The preferences will be stored as a JSON field within the user table

**Comment by jovialcore** [comment]
I assume that you are validating the input for preferences too ?

**Comment by Ukeme-Edet** [comment]
Yes @jovialcore  , The inputs will be validated... Thank you
