### ISSUE TITLE
[FEAT] Delete Customer API Endpoint

### ISSUE THREAD

**Issue by AMdabour** [hngprojects/hng_boilerplate_nestjs#157]
## Description
Create an API endpoint to soft delete a customer. This endpoint will handle the soft deletion of customer records by marking them as deleted and ensure proper validation and error handling.

## Acceptance Criteria
**API Endpoint Implementation**:
- The endpoint should be accessible at `api/v1/customers/{customerId}`.
- The endpoint should accept HTTP DELETE requests.

**Data Validation and Authorization**:
- The API should validate the customer ID to ensure it exists in the database.
- Only authenticated admins should be allowed to delete customer records.

**Response**:
- On success, the API should return a 200 OK status code with a success message.
- On failure, the API should return a 400 Bad Request status code if the customer ID is invalid or a 404 Not Found status code if the customer is not found.

## Request Example:
DELETE /api/customers/{customerId}

**Successful Response**:
```json
{
  "message": "Customer deleted successfully",
  "status_code": 200
}
```
**Error Response**:
```json
{
  "message": "provide a valid customer ID ",
  "status_code": 400
}
```
if a valid customer ID provided but no customer with this ID found in the database
```json
{
  "message": "Customer not found ",
  "status_code": 404
}
```

## Purpose
Provides a backend service to delete customer records securely, ensuring only authorized admins can perform this action.

## Requirements	

- Develop server-side logic to handle customer deletion requests.
- Validate the customer ID before attempting deletion.
- Implement authorization to ensure only admins can delete customers.
- Handle success and error responses appropriately.

## Expected Outcome
API endpoint allows admins to delete customer records securely, returning appropriate success and error responses.

## Status Codes
- 200: Customer was successfully deleted.
- 400: Invalid customer ID.
- 404: Customer not found.
- 500: A server error occurred.

## Testing
- Write unit tests to ensure the endpoint validates input correctly and handles deletion.
- Perform load testing to ensure the endpoint can handle multiple requests.
- Test various scenarios for deleting customers, including invalid IDs and unauthorized access.

**Comment by AMdabour** [comment]
@chukssomzzy 
i will wok on it but i don't have access on the repo so i couldn't add in progress label

**Comment by AMdabour** [comment]
@chukssomzzy
if you have access, could you add it for me please

**Comment by chukssomzzy** [comment]
Do you have nodejs or python dev on your team yet?

**Comment by AshadeSamson** [comment]
@Ahmed_Dabour - FastAPI
@Ashade_Samson - Nest.js

**Comment by AMdabour** [comment]
@FreemanBoss
could you label our issue to be in progress

**Comment by FreemanBoss** [comment]
Please sorry just seeing this. Should I still label it?

**Comment by AshadeSamson** [comment]
Yes please @FreemanBoss

**Comment by FreemanBoss** [comment]
Done!
