### ISSUE TITLE
[FEAT] Update A job post by Id

### ISSUE THREAD

**Issue by uloamaka** [hngprojects/hng_boilerplate_nestjs#158]
## Description
 Implement an Api endpoint to update a job post detail, incase of any omission in job details.

## Acceptance Criteria
- The endpoint should be accessible at api/v1/jobs/:id
- The endpoint should accept HTTP PATCH requests.
- The endpoint should check that the user has the appropriate permissions.
- The endpoint should validate all data passed in the body of the request
- Requests to the endpoint must include a valid authentication token in the Authorization header. Authorization: Bearer <token>
- Given a request with a valid job post ID, when the user is authenticated and authorized, the system should update the user with a status code of 200
- Given a request with an invalid or non-existent user ID, when the user is authenticated and authorised, the system should return a 404 Not Found status.
### Request
- Endpoint: api/v1/jobs/:id
- Request Body:
```json
{
  "title": "Job Title",
  "description": "Job Description",
  "location": "Job location",
  "salary": "String",
  "job_type": "String",
  "company_name": "String"
}
```
- Parameters: (jobpostId) id : string
### Expected Outcome
- Successful Response
```json
{
     "message": "Job details updated successfully",
     "status_code": 200,
     "data": {
           "title": "Job Title",
           "description": "Job Description",
           "location": "Job location",
           "salary": "String",
           "job_type": "String",
           "company_name": "String",
           "created_at": "Timestamp",
           "updated_at": "Timestamp"
         }
} 
```
- Error Response
```json
{
  "status_code": 400,
  "message": ["validation error message"],
  "error": "Bad Request"
} 
```
### Purpose
 Enable updating of a posted job details, incase of any error(typo, etc)

### Requirements
- Develop server-side logic to update a single job post
- Ensure compliance with security standards for handling user information.

### Checklist
- [ ] Define API endpoint to update job post details.
- [ ] Implement logic to update job post details in the database.
- [ ] Handle success and error responses.

### Unit tests
- Successful response with valid id
- invalid job post id
- Miissing job post id
- invalid request body
- Appropriate status code

**Comment by uloamaka** [comment]
**TEAM SISU:**
members slack name:
1.@Uloamaka === GO(gin)
2.@Akintola Olamilekan   === Nodejs(nest.js)
3.@Stephen Kihuni   === Python(fastApi)

**Comment by horlami228** [comment]
Let's go 💪🏽
