### ISSUE TITLE
 [FEAT] Comment Deletion Endpoint

### ISSUE THREAD

**Issue by sirlawglobal** [hngprojects/hng_boilerplate_nestjs#165]
## Description
Implement an endpoint that deletes a comment(s) from a post, and ensures error handling and safe deletion of the data. 

#### Endpoint
- The endpoint should be accessible at `api/v1/comments/:comment_id`. 
- It should accept HTTP `DELETE` request.

#### Authentication
- It should validate the tokens in the authorisation header to ensure only authenticated users can delete comments.
- The endpoint should validate the request to ensure the comment exists in the database.
- Data should be soft deleted by changing the delete attribute in the database to True.

#### Response Handling.
- It should return a `204 OK `status code, and success message upon successful deletion.
- It should return `404 Not Found` or `401 Unauthorized` status code and error message when an error occurs. 

## Endpoint Example

```
DELETE /api/v1/comments/:comment_id
Content-Type: application/json
Authorization: Bearer <token>
```

## Expected Successful Response
```

{
  "message": "Comment successfully deleted",
  "status_code": 204
}

```

## Expected Error Responses
```

{
  "message": "Comment Not Found",
  "error": "Invalid comment Id" 
  "status_code": 404
}

```
```

{
  "message": "Unable to delete comment",
  "error": "Unauthorized user" 
  "status_code": 401
}

```

### Purpose
A feature which allows for deletion of comments on a post.

### Requirements	
- [ ] Implement an endpoint that delete comments from the database
- [ ] Validate the comment id to ensure it exists.
- [ ] Validate only an authenticated user can delete their comment.
- [ ] Handle success and error responses.

### Expected Outcome
The endpoint should delete a user's comments from a post.

### Unit Testing
- Test endpoint for requests with invalid Id and unauthorized user.
- Test that the endpoint collects a valid comment id and safely deletes the data.

Participants Slack_id:

@Agnes Kariuki, fastApi
@Michelle Ndiangui , laravel
@akanji Lawrence, nodejs

**Comment by markessien** [comment]
comments are standalone and not under user

**Comment by sirlawglobal** [comment]
- Changes the API endpoint to [DELETE]  /api/v1/comment/:comment_id
- Added a database schema for the comment feature

**Comment by highb33kay** [comment]
{
  "message": "Comment successfully deleted",
  "status_code": 200
}


Status code for delete?

**Comment by highb33kay** [comment]
Mark needs to review first

**Comment by sirlawglobal** [comment]
@highb33kay 
@Ameenah-Ameenah 
@highb33kay @prondubuisi 

Please we need second approval!
