### ISSUE TITLE
[FEAT] User Self Delete Endpoint

### ISSUE THREAD

**Issue by jeffmaine240** [hngprojects/hng_boilerplate_nestjs#167]
## Description

A feature that allows  soft deletion functionality for user accounts to ensure users can initiate the deletion process but allow Admin user finalize the permanent removal from the system.

## Acceptance Criteria

-   The endpoint should be accessible at  `api/v1/users/:user_id`

-   The endpoint should accept HTTP DELETE requests.

-   The endpoint should be secured to ensure that only authenticated users can access the endpoint

-   Requests to the endpoint must include a valid authentication token in the Authorization header. Authorization: Bearer <token>

-   Upon successful soft deletion, return a status code of 204.

### Request

- **Endpoint** :
         DELETE    `api/v1/users/:user_id`

### Expected Outcome

Provide a JSON response confirming the soft deletion with the user's basic details.
- **successful response**

```
{
  "status": "success",
  "message": "Deletion in progress"
}

```

- **Error response**
  **Invalid Request (HTTP 400)**:

```
{
  "status": "error",
  "message": "Bad Request",
  "status_code": 400
}

```

### Purpose

- Retain soft-deleted accounts in the system for a predefined period .
- During this period, provide an option for users to recover their accounts if desired.

### Requirement:
- When a user initiates account deletion through the endpoint, mark the user's record as deleted in the database.
- Develop a logic to ensure all user-related data remains intact but is no longer accessible through regular operations.
- After soft deletion , logged  user out automatically
- Ensure compliance with security standards for handling user information.

### Checklist

- [ ]  Define API endpoint to soft delete a user.
- [ ] Validate and handle authentication token.
- [ ]  Implement logic to soft delete user information from the database.
- [ ]  Handle success and error responses.
- [ ]  Test Successful response

**Comment by nedssoft** [comment]
@jeffmaine240 following REST API convention that was shared, this endpoint should be named as thus:

`DELETE v1/api/users/:userId`

**Comment by jeffmaine240** [comment]
updated sir

**Comment by jeffmaine240** [comment]
> @jeffmaine240 following REST API convention that was shared, this endpoint should be named as thus:
> 
> `DELETE v1/api/users/:userId`

fixed sir

**Comment by jeffmaine240** [comment]
fixed sir

**Comment by nedssoft** [comment]
userId is not snake_case

**Comment by nedssoft** [comment]
@jeffmaine240 The delete should be soft delete at the first instance, and then it'll be eventually deleted from the system after a set period. But for this task, you should soft delete (you don't have to handle to final delete as that would need some admin decision), every other specs you have remains

**Comment by jeffmaine240** [comment]
> @jeffmaine240 The delete should be soft delete at the first instance, and then it'll be eventually deleted from the system after a set period. But for this task, you should soft delete (you don't have to handle to final delete as that would need some admin decision), every other specs you have remains

fixed the issue again sir

**Comment by nedssoft** [comment]
@jeffmaine240 I missed this earlier, you don't need to return the user info when an account is deleted, just status code and message

**Comment by jeffmaine240** [comment]
> @jeffmaine240 I missed this earlier, you don't need to return the user info when an account is deleted, just status code and message

fixed now sir
