### ISSUE TITLE
Implement Endpoints for CRUD Operations of FAQ

### ISSUE THREAD

**Issue by Horlarhyinka** [hngprojects/hng_boilerplate_nestjs#170]
# Description
Develop API endpoints to handle CRUD (Create, Read, Update, Delete) operations for Frequently Asked Questions (FAQs). This will allow admins to manage FAQ entries through the backend.

# Purpose
To provide admins with the ability to manage FAQ entries efficiently, improving the overall user experience by keeping the FAQ section up-to-date.

# Requirements
- Admin must be authenticated and authorized.
- Error handling
- Develop server-side logic to handle CRUD operations for FAQs.

# Expected Outcome
The backend should handle CRUD operations for FAQ entries efficiently and log responses and errors properly.

# Endpoints

1. **Create FAQ Entry:**
   - **Endpoint:** HTTP POST `/api/v1/faqs`
   - **Request Body:**
     ```json
     {
       "question": "String",
       "answer": "String",
       "category": "String"
     }
     ```
   - **Response (Success):**
     ```json
     {
       "id": "String",
       "question": "String",
       "answer": "String",
       "category": "String"
     }
     ```
   - **Response (Error - Invalid Request):**
     ```json
     {
       "message": "Invalid request data",
       "status_code": 400
     }
     ```
   - **Response (Authorization Error):**
     ```json
     {
       "message": "Unauthorized access",
       "status_code": 403
     }
     ```

2. **Read FAQ Entries:**
   - **Endpoint:** HTTP GET `/api/v1/faqs`
   - **Response (Success):**
     ```json
     [
       {
         "id": "String",
         "question": "String",
         "answer": "String",
         "category": "String"
       }
     ]
     ```
   - **Response (Error - Invalid Request):**
     ```json
     {
       "message": "Invalid request",
       "status_code": 400
     }
     ```

3. **Update FAQ Entry:**
   - **Endpoint:** HTTP PUT `/api/v1/faqs/{id}`
   - **Request Body:**
     ```json
     {
       "question": "String",
       "answer": "String",
       "category": "String"
     }
     ```
   - **Response (Success):**
     ```json
     {
       "id": "String",
       "question": "String",
       "answer": "String",
       "category": "String"
     }
     ```
   - **Response (Error - Invalid Request):**
     ```json
     {
       "message": "Invalid request data",
       "status_code": 400
     }
     ```
   - **Response (Authorization Error):**
     ```json
     {
       "message": "Unauthorized access",
       "status_code": 403
     }
     ```

4. **Delete FAQ Entry:**
   - **Endpoint:** HTTP DELETE `/api/v1/faqs/{id}`
   - **Response (Success):**
     ```json
     {
       "message": "FAQ entry deleted successfully"
     }
     ```
   - **Response (Error - Invalid Request):**
     ```json
     {
       "message": "Invalid request",
       "status_code": 400
     }
     ```
   - **Response (Authorization Error):**
     ```json
     {
       "message": "Unauthorized access",
       "status_code": 403
     }
     ```

# Acceptance Criteria
- [ ] Implement endpoints for creating, reading, updating, and deleting FAQ entries.
- [ ] Validate input data for each operation.
- [ ] Creating and updating FAQs should require admin authorization.
- [ ] Error Handling:
   - Log errors for invalid requests.
   - Display clear error messages for invalid inputs.
- [ ] Security Measures:
   - Validate user input on the server side.
   - Ensure only authenticated and authorized users can perform CRUD operations on FAQs.

**Comment by markessien** [comment]
This is not a supported feature

**Comment by Shullyd7** [comment]
Specify the errors and their status_code

**Comment by Shullyd7** [comment]
You have to specify the error message that required that status_code
