### ISSUE TITLE
[FEAT]: Retrieve the list and status of organisation invitations

### ISSUE THREAD

**Issue by olugbenga1** [hngprojects/hng_boilerplate_nestjs#172]
## Description
Develop an API endpoint to retrieve all invitations sent by an admin for users to join an organization. This endpoint should provide the status of each invitation, indicating whether it has been accepted, rejected or is still pending.

### API Endpoint Implementation
- The endpoint should be accessible at /api/v1/organisations/invitations.
- The endpoint should accept HTTP GET requests.
- The endpoint must be accessible only to admin users.

Response
- On success, the API should return a 200 OK status code with a success message
- On failure, the API should return a 400 Bad Request status code with an appropriate error message

Request Example 

    GET /api/v1/organisations/invitations

#### Success Response 

```
{
	“status_code”: 200
	“message”: “Request successful”,
	“data”: [
	{
		“email”: “[user@example.com](mailto:user@example.com)”,
		“org_id”: “aoalj-alhljkdshj345klhsd”,
		“status: “pending/approved/rejected”,
                "sent_at": "2023-06-23T00:00:00Z",
                "expires_at": "2023-07-23T00:00:00Z"
	}
      ]
}
```

#### Failure Response
```
{
	“error”: “Invalid request”,
	“message”: “User not authenticated or authorized”
}
```

### Purpose
Implement a backend service to manage and display all invitations sent by the admin for users to join an organization, including the status of each invite.

### Requirements

- [ ] Implement authentication logic to ensure the client is signed in
- [ ] Implement authorization logic to verify the client is an admin.
- [ ] Retrieve all user invitations sent by the admin.

### Expected Outcome

The API endpoint retrieves all invitations sent by the admin, along with their statuses

### Status Codes

- 200: Displays the list of all invitations that admin has sent 
- 400 
    - User not authenticated
    - User not authorized 
- 500: A Server error occurred 

### Testing 
- [ ] Ensure the endpoint correctly identifies if the client is signed in
- [ ] Confirm the endpoint verifies that the client is an admin
- [ ] Test the endpoint correctly fetches all invitations sent by the admin.

**Comment by Dev-wonderful** [comment]
Your success response should have `message` and `data`

**Comment by olugbenga1** [comment]
I have now revised the success response to reflect ```message``` and ```data```
Kindly review
