### ISSUE TITLE
[FEAT] COMPONENT THEME SWITCHER - TOGGLE DARK OR LIGHT MODE

### ISSUE THREAD

**Issue by ChibuikemMichaelIlonze** [hngprojects/hng_boilerplate_nestjs#177]
#### Description
Develop API endpoints that allow users to toggle between light and dark modes for the application. The user’s theme preference should be stored and retrieved from the existing `users` table.

#### Acceptance Criteria
- The endpoint `/api/v1/user/theme` is accessible via POST and GET requests.
- When a valid theme preference (`light` or `dark`) is provided, the endpoint updates the user's theme preference and returns a 200 OK status.
- When an invalid theme preference is provided, the endpoint returns a 400 Bad Request status.
- The endpoint should return the current theme preference for the user when accessed via a GET request.
- Ensure that all unit and integration tests for the theme switcher feature are comprehensive, accurate, and verify the functionality correctly.

#### Purpose
To provide users with the ability to switch between light and dark themes, enhancing user experience and accessibility.

#### Requirements
- Implement an endpoint to update and retrieve theme preferences.
- Store the theme preference in the existing `users` table.
- Handle situations where an invalid theme preference is provided.
- Ensure secure and efficient storage and retrieval of user preferences.

#### Expected Outcome
API endpoints that allow users to toggle between light and dark modes and store their preferences securely in the existing `users` table.

#### Tasks
- Add a `theme` column to the existing `users` table.
- Create an endpoint `/api/v1/user/theme` to update and retrieve user theme preferences.
- Implement server-side logic to handle theme preference updates and retrieval requests.
- Ensure all sensitive data is encrypted and secure.
- Implement logging for errors and theme preference update attempts.
- Write unit tests for the theme switcher endpoint.
- Write integration tests for the theme switcher logic.
- Perform security testing to ensure data protection and compliance.

#### Endpoint URL
**[POST] /api/v1/user/theme**

**Request Body:**
```json
{
  "user_id": "string",
  "theme": "string" // "light" or "dark"
}
```

**Successful Response:**
- Status code: 200 OK
  ```json
  {
    "message": "Theme preference updated successfully",
    "data": {
      "user_id": "string",
      "theme": "string"
    }
  }
  ```

**Error Response:**
- Status code: 400 BAD REQUEST
  ```json
  {
    "error": "Invalid theme preference"
  }
  ```

**[GET] /api/v1/user/theme**

**Successful Response:**
- Status code: 200 OK
  ```json
  {
    "data": {
      "user_id": "string",
      "theme": "string"
    }
  }
  ```

**Error Response:**
- Status code: 404 NOT FOUND
  ```json
  {
    "error": "User theme preference not found"
  }
  ```

#### Example Request

**Fetch Theme Preference:**
```sh
curl -X GET "https://<base_url>/api/v1/user/theme?user_id=12345"
```

**Update Theme Preference:**
```sh
curl -X POST "https://<base_url>/api/v1/user/theme" \
  -H "Content-Type: application/json" \
  -d '{
    "user_id": "12345",
    "theme": "dark"
  }'
```

#### Testing
**Test Scenarios**

1. **Successful Toggle**
   - Ensure that the toggle switch updates the integration state correctly.
   - Confirm that the status code is 200.
   - Verify that the response body confirms the state update.

2. **State Persistence**
   - Enable or disable an integration.
   - Reload the page and verify that the toggle state is correctly persisted.

3. **Invalid Theme Preference**
   - Send requests with an invalid theme preference (e.g., `invalid_theme`).
   - Verify that the endpoint returns a 400 Bad Request status code.
   - Confirm that the response body contains an appropriate error message.

4. **Unexpected Error Handling**
   - Simulate an unexpected error during the toggle process.
   - Verify that the endpoint returns a 500 Internal Server Error status code.

5. **Fetching Theme Preference**
   - Ensure the GET request retrieves the current theme preference correctly.
   - Confirm that the status code is 200.
   - Verify that the response body contains the correct theme preference.

**Comment by markessien** [comment]
You absolutely do not need a new table for this

**Comment by ChibuikemMichaelIlonze** [comment]
I closed it, because I opened another Ticket but it was not accepted.
I have made the necessary change as requested by the admin
