### ISSUE TITLE
[FEAT]:Delete Organization Api Implementation-BackendApi

### ISSUE THREAD

**Issue by mwihoti** [hngprojects/hng_boilerplate_nestjs#180]
## Description

Creates endpoints to delete organizations available.

## Acceptance Criteria

API endpoint to delete organizations by their {id}.
Functional API endpoint to support the Delete Organizations UI.
verify user has necessary permissions to delete an organization.

### Purpose
Functonality for deleting organinazations

### Requirements	

API endpoint to delete organizations.

### Endpoints

[DELETE] /api/v1/organizations/{id}

Will delete organization of the above id if it exists in the database otherwise return error response.

### Successful Response

Status code: 204
```
{
"message": Organization deleted successfully.
}
```

### Error response

status code 404

```
{
  "error": "Not Found",
  "message": "Organization not found."
}
```
### Unauthorized Access

Status Code: 403 Forbidden

```
{
  "error": "Forbidden",
  "message": "You do not have permission to delete this organization."
}
```
### Internal server error

Status code: 500

```
{
  "error": "Internal Server Error",
  "message": "An unexpected error occurred on the server side."
}

```
### Secure Endpoins

Authentication & Authorization:
Ensure the user is authenticated.
Verify the user has the necessary permissions to delete an organization.

### Write Tests
Unit Tests:
Test successful deletion of an organization.
Test deletion with a non-existent organization ID.
Test endpoint security (authentication and authorization).
Test for proper error handling.

**Comment by mwihoti** [comment]
@Moses-Oyelade

**Comment by markessien** [comment]
this appears to be a duplicate
