### ISSUE TITLE
[FEAT]: Product Listing API Endpoint 

### ISSUE THREAD

**Issue by nadduli** [hngprojects/hng_boilerplate_nestjs#182]
### Description
Implement an API endpoint to list products with filtering and pagination.

#### Acceptance Criteria
- [ ] **Endpoint**: The endpoint should be accessible at `/api/v1/products`
- [ ] **HTTP Method**: The endpoint should accept HTTP GET requests
- [ ] **Authentication**
  - The endpoint should be secured to ensure that only authenticated users can access product listings.
  - Proper authentication mechanisms should be implemented.
  - Requests to the endpoint must include a valid authentication token in the Authorization header.
  - Example:
    ```http
    Authorization: Bearer <token>
    ```

- **Query Parameters**:
  - The endpoint should accept the following query parameters for filtering and pagination:
    - `search` (string, optional): Search term to filter products by name, description, category, or tags.
    - `category` (string, optional): Filter products by category.
    - `page` (integer, optional): Page number for pagination.
    - `limit` (integer, optional): Number of results per page.

  - Example Request:
    ```http
    GET /api/v1/products?search=keyword&category=electronics&page=1&limit=10
    ```

- **Response**:
  - **Success (200 OK)**:
    - The response should include an array of products matching the search and pagination criteria.
    - Each product object should include:
      - `id`: The ID of the product.
      - `name`: The name of the product.
      - `description`: The description of the product.
      - `category`: The category of the product.
      - `price`: The price of the product.
      - `tags`: An array of tags associated with the product.

    - Example:
      ```json
      {
        "products": [
          {
            "id": 1,
            "name": "Product Name",
            "description": "Product Description",
            "category": "Electronics",
            "price": 19.99,
            "tags": ["tag1", "tag2"]
          }
        ],
        "total": 1,
        "page": 1,
        "limit": 10
      }
      ```

  - **Error**:
    - **401 Unauthorized**: If the request does not include a valid authentication token, the response should include:
      ```json
      {
        "status_code": 401,
        "message": "Authentication required",
        "error": "Unauthorized"
      }
      ```
    - **500 Internal Server Error**: If an unexpected error occurs on the server side, the response should include:
      ```json
      {
        "status_code": 500,
        "error": "Internal Server Error",
        "message": "An unexpected error occurred. Please try again later."
      }
      ```

#### Purpose
Provides a backend service to list products based on various criteria, enhancing product discovery and search capabilities for users.

#### Requirements
- Develop server-side logic to handle product listing based on search and pagination.
- Implement filtering and sorting based on product attributes.
- Secure the endpoint with proper authentication mechanisms.
- Ensure compliance with security standards for data handling.

#### Expected Outcome
- The API endpoint allows authenticated users to retrieve products based on search, category, and pagination.
- The response includes a list of products that match the specified criteria.

#### Testing
- Write unit tests for backend filtering and pagination logic.
- Write integration tests for end-to-end product listing scenarios.
- Test various scenarios, including different combinations of search parameters and pagination.

#### Example Request
```http
GET /api/v1/products?search=keyword&category=electronics&page=1&limit=10
Authorization: Bearer <token>
```
#### Example Response
* Success (200 OK):
```json
{
  "products": [
    {
      "id": 1,
      "name": "Product Name",
      "description": "Product Description",
      "category": "Electronics",
      "price": 19.99,
      "tags": ["tag1", "tag2"]
    }
  ],
  "total": 1,
  "page": 1,
  "limit": 10
}
```
* Error (401 Unauthorized):
```json
{
  "status_code": 401,
  "message": "Authentication required",
  "error": "Unauthorized"
}
```
* Error (500 Internal Server Error):
```json
{
  "status_code": 500,
  "error": "Internal Server Error",
  "message": "An unexpected error occurred. Please try again later."
}
```

**Comment by nadduli** [comment]
updated my endpoint

**Comment by markessien** [comment]
Confirm that this is not a duplicate

**Comment by sethdanny** [comment]
Yes it's not a duplicate

**Comment by EAZYLINK** [comment]
It's a duplicate, check the list product issue

**Comment by thenoblet** [comment]
@EAZYLINK and @sethdanny, it is a duplicate.
