### ISSUE TITLE
[FEAT] Profile Update API Endpoint - BACKEND

### ISSUE THREAD

**Issue by SamixYasuke** [hngprojects/hng_boilerplate_nestjs#185]
#### Description
Create an API endpoint to handle profile updates. This endpoint will allow users to update their profile information, including profile picture, username, pronouns, job title, department or team, email address, bio, and social links.

#### Acceptance Criteria
- **API Endpoint Implementation:**
  - The endpoint should be accessible at `/api/v1/settings/profile`
  - The endpoint should accept HTTP PATCH request
- **Response:**
  - On success, the API should return a 200 OK status code with a success message
  - On failure, the API should return a 400 Bad Request status code with appropriate error messages
- **Data Validation**
   - keys like pronouns should be enumerated to ensure data consistency. For example, pronouns should only accept predefined values like "he/him", "she/her", "they/them"
   - Social links should be validated to ensure they follow a correct URL format. Each social link should be validated against a regex pattern suitable for URLs
   - The email address should be validated to ensure it follows the correct email format

#### Request Example PATCH/api/v1/settings/profile
```json
{
  "profile_picture": "https://example.com/profile.jpg",
  "username": "samixx",
  "pronouns": "he/him",
  "job_title": "Backend Developer",
  "department": "Engineering",
  "email": "samueladekolu4@gmail.com",
  "bio": "passionate about backend development and open-source projects",
  "social_links": {
    "x": "https://x.com/samueladekolu",
    "github": "https://github.com/SamixYasuke"
  }
}
```

#### Successful Response
```json
{
  "message": "Profile updated successfully",
  "status_code": 200
}
```

#### Error Response
```json
{
  "message": "Validation error",
  "errors": [
    { "field": "email", "message": "Invalid email format" },
    { "field": "username", "message": "Username already taken" },
    { "field": "socialLinks.github", "message": "Invalid social link format" },
    { "field": "pronouns", "message": "Invalid pronoun value" }
  ],
  "status_code": 400
}
```

#### Purpose
Provides a backend service to handle profile updates for users, ensuring that all data is validated and sanitized before updating the user's profile information

#### Requirements
- Develop server-side logic to handle profile updates
- Validate and sanitize incoming profile data
- Ensure that updated data is stored correctly in the database

#### Expected Outcome
The API endpoint allows users to update their profile information via the provided endpoint and ensures the data is correctly validated, sanitized, and stored

#### Status Codes
- **200**: Profile was successfully updated
- **400**: Validation error due to invalid input data
- **500**: A server error occurred

#### Testing
- [ ] Write unit tests to ensure the profile update endpoint validates input correctly and updates user profile information
- [ ] Perform load testing to ensure the endpoint can handle multiple requests
- [ ] Test various scenarios for submitting profile updates (e.g., valid data, invalid email format, duplicate username, malformed social links, etc)

**Comment by SamixYasuke** [comment]
This issue already exists, but I believe this solves the problem better

**Comment by markessien** [comment]
Duplicate

**Comment by SamixYasuke** [comment]
I just checked, the duplicate issue has been closed by the person that created it. It's issue #163
