### ISSUE TITLE
[FEAT] Blog - Fetching a Blog Post by ID

### ISSUE THREAD

**Issue by Goketech** [hngprojects/hng_boilerplate_nestjs#187]
## Description

Develop an endpoint to handle requests to fetch and return data for a single blog post by its ID. If the data is fetched successfully, it will be returned to the client with a '200 OK' status. If an error occurs, an appropriate error status will be returned.

## Acceptance Criteria

* The endpoint fetches and returns blog post data including title, content, publish date, images, tags and author.
* Returns a `200 OK` status code and the correct response body when data is fetched successfully.
* Returns an appropriate error message when an error occurs.
* Endpoint is correctly versioned.

### Requirements

* [ ] Implement API endpoint for fetching a single blog post by its ID.
* [ ] Fetch and return blog post data including: Title, Content, Publish Date, Images, tags Author.
* [ ] Handle unexpected errors and return the appropriate status code.
* [ ] Endpoint is correctly versioned.

### Expected Outcome

* Users should be able to send a request to the backend to retrieve data for a single blog post by its ID.
* Users should receive appropriate status codes and responses based on the outcome of the request.

Endpoints

[GET] api/v1/blog-posts/{id}

* Description: Fetches a single blog post by its ID.

* Path Parameters:

  * `id`: The ID of the blog post to retrieve.

* Success Response:

  * Status: `200 OK`
  * Body:
    ```json
    {
      "title": "Blog Post Title",
      "content": "Full content of the blog post...",
      "publish_date": "2024-07-17T00:00:00Z",
      "author": "Author Name",
      "tags": ["tag1", "tag2" ],
      "images": ["Image URL", "Image2_URL"]
    }
    ```

* Error Response:

  * Status: `500 Internal Server Error`
  * Body:
    ```json
    {
      "error": "Internal server error."
    }
    ```

* Not Found Response:

  * Status: `404 Not Found`
  * Body:
    ```json
    {
      "error": "Blog post not found."
    }
    ```

* Invalid Method Response:

  * Status: `405 Method Not Allowed`
  * Body:
    ```json
    {
      "error": "This method is not allowed."
    }
    ```

* Bad Request Response:

  * Status: `400 Bad Request`
  * Body:
    ```json
    {
      "error": "An invalid request was sent."
    }
    ```

### Testing

Test Scenarios

1. Successful Retrieval of a Blog Post

  * Ensure that the endpoint successfully retrieves a blog post by its ID.
  * Verify that the response includes the title, content, publish date, images, tags and author of the blog post.
  * Confirm that the status code is `200 OK`.

2. Blog Post Not Found

  * Simulate a scenario where the blog post ID does not exist in the database.
  * Confirm that the response body contains an appropriate error message.

3. Internal Server Error

  * Simulate an internal server error to raise an exception.
  * Verify that the endpoint returns a `500 Internal Server Error` status code.
  * Confirm that the response body contains an appropriate error message.

4. Invalid Method

  * Send a request using an invalid HTTP method (e.g., POST) to the endpoint.
  * Verify that the endpoint returns a `405 Method Not Allowed` status code.
  * Confirm that the response body contains an appropriate error message.  

5. Bad Request

  * Send a request with an invalid blog post ID (e.g., non-integer value).
  * Verify that the endpoint returns a `400 Bad Request` status code.
  * Confirm that the response body contains an appropriate error message.

**Comment by highb33kay** [comment]
Update your response to fit approved structure
