### ISSUE TITLE
[FEAT] Edit User Products with Update Timestamp

### ISSUE THREAD

**Issue by CodewithSegNet** [hngprojects/hng_boilerplate_nestjs#188]
## Description

Develop an API endpoint to edit user  `product_name`, `price`, `description`, and `tag` and create a timestamp for updates.

## Acceptance Criteria

- The endpoint should be accessible at `/api/v1/organizations/{id}/products/{id}`

- The endpoint should accept HTTP `PUT` requests.

- The endpoint should be secured to ensure that only authenticated users can edit products.

- Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
Requests to the endpoint must include a valid authentication token in the Authorization header. Authorization: Bearer <token>

- **Request Body**:

```json
{
  "product_name": "Updated Product Name",
  "price": 600.0,
  "description": "Updated Product Description",
  "tag": "New Tag"
}
```

- **Response**:
  - On a successful update, the API should return a `200` OK status code.
  - The response body should contain the updated product details.

```json
{
  "id": 1,
  "product_name": "Updated Product Name",
  "price": 600.0,
  "description": "Updated Product Description",
  "tag": "New Tag",
  "created_date": "2024-07-17T12:34:56Z",
  "updated_date": "2024-07-18T14:20:00Z"
}
```

* **Validation**:
- If any required field is missing or invalid, the API should return a 400 Bad Request status code with an appropriate validation error message.

```json
{
  "status_code": 400,
  "message": ["product_name is required", "price must be a positive number"],
  "error": "Bad Request"
}
```

## Purpose

- Provides a backend service that allows users to edit their products, including updating the name, price, description, and tag. This is useful because users can have multiple products, and product details can change over time. The endpoint also enables users to see the specific time when a product was last updated.

## Requirements
- [ ] Endpoint: The API should expose an endpoint at `/api/v1/organizations/{id}/products/{id}`.
- [ ] Request Method: The endpoint should accept HTTP `PUT` requests.
- [ ] Authentication: Implement proper authentication mechanisms (e.g., JWT, OAuth2) to secure the endpoint.
- [ ] Authorization Header: Requests to the endpoint must include a valid authentication token in the Authorization header. 
- [ ] Authorization: Bearer <token>
- [ ] Request Body: Accept a JSON body with the fields `product_name`, `price`, `description`, and `tag`.

## Expected Outcome

- The API should update the product details based on the provided information.
The response should include updated product details such as `id`, `product_name`, `price`, `description`, `tag`, `created_date`, and `updated_date`.

## Testing

**Authentication Testing**:
  - Test the endpoint with a valid authentication token to ensure access is granted.
  - Test the endpoint without an authentication token or with an invalid token to ensure access is denied.

**Parameter Validation**:
  - Test the endpoint with valid fields to ensure it updates the product correctly.
  - Test the endpoint with missing or invalid fields to ensure it returns a `400` Bad Request status code with an appropriate error message.

**Response Verification**:
  - Test the endpoint with valid input values and verify that the response includes the updated product details.
  - Test the endpoint with an id that does not exist and verify that the response is appropriate (e.g., a `404` Not Found status code).

**Edge Cases**:
  - Test the endpoint with special characters and boundary values in the `product_name`, `description`, and `tag` fields to ensure the update functionality is robust.

**Comment by phurhard** [comment]
> This endpoint duplicates issue #97 . #97 has filtering as such name can be used to filter

Also you can check #120

**Comment by CodewithSegNet** [comment]
> This endpoint duplicates issue #97 . #97 has filtering as such name can be used to filter


how can we resolve this?? issue #97 list all product while  our endpoint aims to search products by name and also add a timestamp on when product was added(created) and updated

**Comment by phurhard** [comment]
And issue #120 ??

**Comment by CodewithSegNet** [comment]
> And issue #120 ??

okay, its duplicated. can we convert this endpoint to edit user products(name, price, description and tag) and create a timestamp for updates? I don't see any double approved issue on this for now. please we are just trying to avoid a duplicate issue this time around

**Comment by phurhard** [comment]
Yes, look for another issue to work on, confirm it hasn't been worked on by searching keywords to it in the issues to prevent duplication

**Comment by CodewithSegNet** [comment]
updated issue

**Comment by phurhard** [comment]
This is good, buh check #86

**Comment by CodewithSegNet** [comment]
new update on issue

**Comment by CodewithSegNet** [comment]
thanks boss

**Comment by CodewithSegNet** [comment]
TEAM MEMBER

- [ Olusegun Emmanuel ](https://github.com/CodewithSegNet)
-  [ Obi Ugochukwu Joseph ](https://github.com/ugojo)
-  [ onielsteve ](https://github.com/onielsteve2003)
