### ISSUE TITLE
[FEAT] Dashboard - Search Functionality

### ISSUE THREAD

**Issue by Benedict-arowo** [hngprojects/hng_boilerplate_nestjs#19]
## Description
Allow users to easily search through dashboard content.

## Acceptance Criteria

1. Search Bar:
   - A search bar is implemented at the top of the dashboard.
   - The search bar is easily accessible and user-friendly.

2. Real-Time Results:
   - Search results update in real-time as the user types.
   - The displayed results are relevant to the user's query.

3. Performance Optimized:
   - The search functionality is optimized to handle large amounts of data without lag.
   - Any performance issues or bottlenecks are identified and addressed.
   
### Requirements
1. Add a Search Bar:
   - Implement a search bar at the top of the dashboard.

2. Real-Time Search Results:
   - Ensure that the search results update in real-time as users type in the search bar.

3. Optimize Search Performance:
   - Ensure that the search functionality is optimized for performance to provide a seamless user experience.

### Expected Outcome
- [ ] Users can quickly search and find content on the dashboard.
- [ ] Real-time results are displayed as users type in the search bar.
- [ ] Search performance is optimized to handle large datasets efficiently.

### Testing

1. Unit Tests:
   - Implement unit tests for the search functionality to ensure accuracy and performance.
   - Test the real-time search functionality with various input lengths and types.
   - Ensure that the search results update correctly and promptly.
2. Performance Testing:
   - Test the search performance with large datasets.

**Comment by markessien** [comment]
This ticket does not clarify what is being searched. It cannot be approved - search is not related directly to dashboard, but is a broader ticket that requires an indexer like typesense.
