### ISSUE TITLE
CREATING MIGRATION SCRIPTS FOR THE USER TABLE

### ISSUE THREAD

**Issue by horlami228** [hngprojects/hng_boilerplate_nestjs#194]
## Description
Create a migration to add a User table to the database to store user-related information.

## Acceptance Criteria
- User table schema includes fields: Id, Name, Email, PasswordHash.
- Email column has a unique constraint.
- Migration script successfully creates the User table in the database.

### Purpose
To establish a structured database schema for storing user data securely.

### Requirements
- Define User table schema with fields: Id, Name, Email, PasswordHash.
- Ensure unique constraint on Email column.
- Generate and apply the migration script.

### User Table Schema

```sql
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE User (
    Id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL
);
```
### Checklist
- [ ] User table schema is defined and includes fields: `Id`, `Name`, `Email`, `PasswordHash`.
- [ ] Unique constraints are applied to the `Email` column.
- [ ] The migration script is generated and successfully applied.
- [ ] User table creation process is completed in the database.

### Expected Outcome

Upon executing the migration script, the User table will be successfully created in the database. It will adhere to the specified schema, including fields for `Id`, `Name`, `Email`, and `PasswordHash`, with appropriate constraints applied to ensure data integrity and security.

**Comment by markessien** [comment]
migration scripts are not tickets
