### ISSUE TITLE
[FEAT] API Endpoint to Retrieve Admin Activity Log

### ISSUE THREAD

**Issue by abnurkan** [hngprojects/hng_boilerplate_nestjs#195]
## Description
implement an Admin Activity Log feature to track all actions performed by administrators within the system. This log will help in auditing and troubleshooting administrator activities.

## Acceptance Criteria

-   The endpoint should be accessible at v1/api/admin/log/id.
-  The endpoint should accept HTTP GET requests.
-  The endpoint should be secured to ensure that only authenticated users with appropriate permissions can request administrative 
    action such as System Administrators, Security Administrators ,Auditors.
- Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
-  The endpoint should Ensure logging captures the timestamp, action type, administrator username, and affected resource details.
-  Implement logging of actions such as user creations, updates, deletions, and any other significant administrative actions.

- Requests to the endpoint must include a valid authentication token in the Authorization header. Authorization: Bearer <token>

 **Request**

- The user ID should be included in the URL path.

- Define the structure of the request body containing fields:

```
   {
  "action_type": "string",
  "username": "string",
  "resource_type": "string",
  "resource_id": "string",
  "details": "string"
   } 
```

- action_type: Type of action performed (e.g., "create", "update", "delete").
- username: Username of the administrator performing the action.
- resource_type: Type of resource affected (e.g., "user", "product").
- resource_id: ID of the affected resource (optional if applicable).
- details: Additional details about the action (optional).

**Responses:**
    Implement appropriate HTTP responses:
         -   200 OK on successful logging.
         -   400 Bad Request for invalid requests or missing parameters.
        
 **succesful response** 
       
       
 ```
{
  "message": "Activity logs retrieved successfully",
  "status_code": 200,
  "data": [    
    {
  "id": 1,
  "timestamp": "2024-07-18T14:25:10.456Z",
  "action_type": "string",
  "username": "string",
  "resource_type": "string",
  "resource_id": "string",
  "details": "string"
}
  ]
}

```
**unsuccessful response**

- If the user is not authenticated, return a 401 Unauthorized status code.
- If the user does not have permission to view admin logs, return a 403 Forbidden status code.
- If there's a server error, return a 500 Internal Server Error status code.

**Log Not Found:**
Response:

```
{
  "detail": "Log not found"
}

```

**Forbidden status response**

```
{
  "status_code": 403,
  "message": "You do not have permission to view this logs",
}


```
**server error response**

```
{
  "status_code": 403,
  "message": "You do not have permission to views this logs",
}
```

### Purpose
Provides a backend service which allows authorized users to delete products from the system

### Requirements	

- Develop server-side logic to view an admin logs.
- Ensure only users with appropriate permissions view logs.
- Implement proper error handling and status code responses.

### Expected Outcome

- Implement server-side logic to handle successful and failed logged admin action requests.
- Ensure the user has the proper permissions to retrieve admin logs.
- Implement proper error handling for various scenarios (admin logs not found, unauthorized access, etc.).
- Write unit tests for the admin logs functionality.
- Write integration tests for admin logs.
- Perform security testing to ensure only authorized users retrieve admin logs.

### Testing
Unit test the logging functionality to ensure actions are logged correctly.
Integration test the API endpoint v1/api/admin-activity/log/id  to verify correct request handling and response codes.
 Perform end-to-end tests to ensure logged data is stored securely and can be retrieved as needed.
Test various scenarios:
retrieve admin logs
Attempting to retrieve admin logs without authentication
Attempting to delete a product without proper permissions
Perform security testing to ensure only authorized users can retrieve admin logs.

**Comment by bolexs** [comment]
can link to main issue where admin do this things be provided

**Comment by markessien** [comment]
no need for this as a separate thing from the main activity log

**Comment by abnurkan** [comment]
okay let me look for another ticket
