### ISSUE TITLE
[FEAT] Newsletter Subscription

### ISSUE THREAD

**Issue by CaptainAril** [hngprojects/hng_boilerplate_nestjs#196]
## Description
Implement a feature that allows users to subscribe to the boilersplate's newsletter.

### User Subscription [POST] `/api/v1/newsletter/subscribe`
* ### Registration:
    * Given a request with valid detail (email) when the user subscribes, the system should create an entry of the users email into the newsletter table. On successful, return a `201` created status code.

* ### Email Validation:
    * When given an invalid email address format, the user system should return a `400` Bad Request status with the appropriate error message.

* ### Unique Email:
    * If a newsletter subscription already exists for the submitted email, the system should return a `400` bad request error status with an appropriate error message.

* ### Confirmation Email
    * On successful subcription, the system sends a confirmation email to the provided email address.

* ### Email Personalization
    * Implement email lookup to get the firstname of subcribers, for a more personalized newsletter email.

### Request

**[POST]** `/api/v1/newsletter/subscribe`

```
{
  "email": "user@example.com"
}
```
### Successful Response

```
{
    "statusCode": 201,
    "message": "Subscription successful. Please check your email to confirm your subscription.",
    "subscriber": {
        "email": "String",
        "subscribedAt": "DateTime"
        }
}
```

### Error Response
```
{
  "message": "Invalid email format",
  "statusCode": 400
}
```

```
{
  "message": "Email address already subscribed",
  "statusCode": 400
}
```

### Unit Test
    * Test for successful subscription with a valid email address
    * Test for subscription attempt with an invalid email format
    * Test for subscription attempt with an already subscribed email
    * Test that a confirmation email is sent on successful subscription

###

**Comment by markessien** [comment]
this seems like a duplicate, check that it is not

**Comment by Solomonuche** [comment]
It's a duplicate. We are already working on it. Issue #82
