### ISSUE TITLE
[FEAT] Implement Backend for Notification Settings

### ISSUE THREAD

**Issue by DOOMSDAY101** [hngprojects/hng_boilerplate_nestjs#20]
### Description:
Develop and implement the backend components necessary to manage user notification preferences. This includes creating the data models, database schema, API endpoints, and ensuring integration with existing services.

### Purpose:
To provide a robust and scalable backend solution for storing and managing user notification settings, facilitating efficient data handling and integration with other backend services.

### Requirements:
1. Design and create a database schema for storing notification preferences.
2. Develop API endpoints for managing notification settings.
3. Integrate the notification settings feature with existing user services.
4. Add authentication to ensure only authenticated users can access the endpoints.

### Expected Outcome:
A robust and scalable data model that accurately stores, retrieves, and manages user notification settings, integrated A comprehensive backend solution that supports the storage, retrieval, and management of user notification settings, integrated seamlessly with the current system architecture.

### Checklist:
- [ ] Define and implement the database schema for notification settings.
- [ ] Create and test database migration scripts.
- [ ] Develop and test database migrations scripts to apply the new schema.
- [ ] Implement secure and validated API endpoints for CRUD operations on notification settings.
- [ ] Add JWT authentication to the POST and GET endpoints for notification settings.
- [ ] Integrate the notification settings feature with existing user services.
- [ ] Write unit and integration tests for the new backend components.
- [ ] Update relevant technical documentation to reflect the new backend features and their integration points.

### API Endpoints
POST `/api/v1/settings/notification-settings` [PROTECTED]

Request:
``` json
{
    "user_id": johndoe@gmail.com,
    "email_notifications": true,
    "push_notifications": false,
    "sms_notifications": true
}
```

Response:
``` json
{
    "status": "success",
    "data": {
        "setting_id": 1,
        "user_id": johndoe@gmail.com,
        "email_notifications": true,
        "push_notifications": false,
        "sms_notifications": true
    }
}
```
Possible Status Code:

`200` OK: User is authenticated and settings are updated successfully.
`401` Unauthorized: JWT token is missing or invalid.
`400` Bad Request: Request payload is invalid.

Get Notification Settings:
GET `/api/v1/settings/notification-settings/:user_id` [PROTECTED]

Response:
``` json
{
    "status": "success",
    "data": {
        "setting_id": 1,
        "user_id": 1,
        "email_notifications": true,
        "push_notifications": false,
        "sms_notifications": true
    }
}
```
Possible Status Code:

`200` OK: User is authenticated and settings are updated successfully.
`401` Unauthorized: JWT token is missing or invalid.
`400` Bad Request: Request payload is invalid.

**Comment by markessien** [comment]
Designing a schema is not a user ticket

**Comment by DOOMSDAY101** [comment]
I have updated and refined the ticket to as instructed

**Comment by NdubuisiJr** [comment]
This looks good to me
