### ISSUE TITLE
[FEAT] Create a GET endpoint to Retrieve Client Testimonials

### ISSUE THREAD

**Issue by AsciencioAlex** [hngprojects/hng_boilerplate_nestjs#201]
## Description
Create an API  GET endpoint that allows users to retrieve client testimonials. 

## Acceptance Criteria
- [ ] The endpoint should support fetching all testimonials..
- [ ] The response should include testimonial metadata such as client name, designation, date, and rating.
- [ ] The endpoint requires user authentication.
- [ ] The response should be paginated to handle large numbers of testimonials efficiently.
- [ ] The endpoint  should be able to retrieve user ratings.
- [ ] Implement rate limiting to restrict the number of requests a user can make to the endpoint.
- [ ]  The response should be to limit 
- [ ] Proper error handling should be implemented for invalid requests.

### Purpose
The purpose of this endpoint is to provide a way for users to easily access and retrieve client testimonials from our database.

### Requirements	
- [ ] The endpoint should be a GET request to `/api/testimonials?page=1`.
- [ ]  The response should be in JSON format.
- [ ]  The response should include necessary metadata for each testimonial.
- [ ] The endpoint requires user authentication.
- [ ]  The response should be paginated  with a default page size of 3 testimonials.
- [ ] Implement API rate limiting (e.g., 100 requests per 10 minutes per user).
- [ ] The response should be able to capture the ratings where the minimum rate is 1 and the maximum is 5
- [ ]  Appropriate status codes should be returned for successful `200 ok` and unsuccessful requests `500 bad request` and `400 error`.

### Request Example
GET /api/testimonials?
###  Successful Response
```
{
  "message": "Testimonials retrieved successfully",
  "status_code": 200,
  "data": [
    {
      "id": 1,
      "client_name": "Jane Smith",
      "client_designation": "Freelance Designer",
      "testimonial": "Excellent service and support!",
      "rating": 5,
    
    }
   ]
 "pagination": {
    "current_page": 1,
    "per_page": 3,
    "total_pages": 5,
    "total_testimonials": 50
  }
}
```
### Unsuccessful Response
```
{
  "message": "Error retrieving testimonials",
  "status_code": 500
}

```
```
{
  "message": "Error retrieving testimonials",
  "errors": [
    "Invalid client name format",
    "Rating out of range (expected 1-5 stars)",
    "Invalid date format"
  ],
  "status_code": 400
}
```
## Unit Tests
- [ ] Test fetching all testimonials.
- [ ] Test pagination functionality.
- [ ] Test error handling for invalid requests.

## Expected Outcome

- [ ] The endpoint is able to return a list of client testimonials.
- [ ] The returned testimonials include all necessary metadata.
- [ ] The endpoint handles large datasets efficiently with pagination.
- [ ] The endpoint gracefully handles invalid requests with appropriate error messages.

![Copy of  HNG boilerplate (1)](https://github.com/user-attachments/assets/2d1da1c8-9abb-48ec-9e73-9ddf9f0f5415)

**Comment by AsciencioAlex** [comment]
Team Members:


<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">


Github   Name | Full Name | Slack ID | Email | Stack
-- | -- | -- | -- | --
AsciencioAlex | Alex Asciencio | Alex  Asciencio | asciencioalex@gmail.com | Laravel
kvngstar | Kingsley Okoronkwo | devmonk | kvngsley019@gmail.com | NestJs
chionz | Chidera Prince | Chidera Prince | chideraprince9@gmail.com | Python



</body>

</html>

**Comment by highb33kay** [comment]
Authentication?

**Comment by highb33kay** [comment]
Rate limiting?
Pagination?

**Comment by AsciencioAlex** [comment]
@highb33kay we have made the correction.

**Comment by highb33kay** [comment]
@Shullyd7 Can we get second approval?
