### ISSUE TITLE
[FEAT]: CREATE PRODUCTS API ENDPOINT

### ISSUE THREAD

**Issue by Habiba-halkano** [hngprojects/hng_boilerplate_nestjs#203]
**Description**
Implement a backend feature to allow the creation of new products in the database. This endpoint will facilitate adding new products with details such as name, description, price, and category.

**Acceptance Criteria**
- [ ] A `POST` endpoint is available at `/api/v1/organizations/{id}/products`.
- [ ] The endpoint successfully creates a new product and stores it in the database.
- [ ] Appropriate HTTP status codes are returned (e.g., `201 Created` for success, `400 Bad Request` for invalid input).
- [ ] Ensure validation of input data to prevent malformed or incomplete product entries.

### Purpose
Provide an API endpoint for creating new products to facilitate the addition of products to the system.

### Requirements
1. Create a backend endpoint to handle product creation requests.
2. Validate input data to ensure all necessary fields are provided and correctly formatted.
3. Ensure proper error handling and response statuses.
4. Update any related data or references accordingly.

### Data validation
**Input Validation:**
- Ensure all necessary fields (e.g., name, description, price, category) are provided and correctly formatted.
- Validate that `price` is a positive number.

**Output Validation:**
- Verify that the response includes the created product's details with correct data types.

### Authentication and Authorization
**Authentication:**
- Ensure the endpoint requires user authentication to create products.

**Authorization:**
- Implement role-based access control to ensure only authorized users can create products.

### Expected Outcome
- A `POST` endpoint at `/api/v1/organizations/{id}/products` that:
  - Accepts product data (e.g., name, description, price, category, etc.).
  - Validates the input data.
  - Inserts the new product into the database.
  - Returns a `201 Created` status with the created product details.
  - Returns appropriate error messages and statuses for invalid input or server errors.
  
 ### Successful Response (201 Created):
 ```json
 {
  "status": "success",
  "message": "Product created successfully",
  "data": {
    "id": 123,
    "name": "New Product",
    "description": "A description of the new product.",
    "price": 29.99,
    "category": "Electronics",
    "created_at": "2024-07-17",
    "updated_at": "2024-07-17"
  }
}
```
### Error Response (400 Bad Request):
```json
{
  "status_code": 400,
  "status": "Bad request",
  "message": "Invalid input data",
  "errors": {
    "name": "Name is required",
    "price": "Price must be a positive number"
  }
}
```
### Error Response (401 Unauthorized)
```json
{
  "status_code": 401,
  "status": "unauthorized",
  "message": "Unauthorized. Please log in."
}
```
### Error Response (500 Internal Server Error):
```json
{
  "status_code": 500,
   "status": "Internal server error",
  "message": "An unexpected error occurred. Please try again later."
}
```

### Testing Requirements
**Unit Tests:**
- Verify the need for unit tests to cover all functionality of the endpoint.

**Integration Tests:**
- Confirm the requirement for integration tests to ensure the endpoint works correctly with the overall system.

**Comment by markessien** [comment]
I think I have seen this before

**Comment by Habiba-halkano** [comment]
@markessien I've not seen anyone who has worked on it so far.

**Comment by Dev-wonderful** [comment]
Follow the set convention for your responses

**Comment by Habiba-halkano** [comment]
@Dev-wonderful updated.
