### ISSUE TITLE
[FEAT] Create Subscription Plan Feature Endpoint - BACKEND

### ISSUE THREAD

**Issue by Sidney2022** [hngprojects/hng_boilerplate_nestjs#205]
# Description
Develop a backend endpoint to handle requests for creating subscription plan features. The endpoint will accept a feature and a description. validate and sanitize the data, and then handle both successful and failed validations appropriately. If the data passes validation, they will be stored in the database and a 'success' response will be sent to the client. If validation fails, an error message will be returned.

# Acceptance Criteria
- Accepts and validates the data.
- Persist the data to the database.
- Return the appropriate response and status code
### Authentication
- The user must be signed in as a super admin to access the view endpoint.
- If a user is not authenticated as a super admin, the API should return a 401 Unauthorized error.
Requirements
 Implement API endpoint with data validation and sanitization
 Set up database integration and secure storage
Expected Outcome
The user input data should be successfully sent to the backend, or the user will receive an error message if unsuccessful
Status code

- 201: feature was successfully stored.
- 400: Invalid data .
- 401: data already exist.
- 500: A server error occurred.
### Endpoint
[POST] /api/v1/add-plan-feature

Requests:

headers:

content-type: application/json
```
{
    "feature": "string"
    "description": "string"
}
```
Responses:

Successful response

```
{
    "message": "string",
    "success": true,
    "status_code": int
}
```
Error response

```
{
    "message": "string",
    "success": false,
    "status_code": int
}
```
Database design
schema

Table name: features_table

id:

constraints: string(uuid), unique, primary-key, not null
feature:

constraints: string, not null, max-length(255)
Description:

constraints: string
Testing
Unit Tests
The systems should have unit tests covering:

- [ ]  Validates data and check for duplicate features.
- [ ]  Ensure only a super-admin can make the request
- [ ]  Ensure data is saved correctly to the database.
- [ ]  Test that the appropriate response and status code is returned

**Comment by markessien** [comment]
there are no /admin routes

**Comment by markessien** [comment]
also, this seems duplicated

**Comment by Sidney2022** [comment]
I've updated the route to /api/v1/add-plan-feature.

Regarding the duplicate issue, I believe you may be referring to the [[FEAT]: Create Subscription Plan API Endpoint - BACKEND #202](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/202) ticket, which I also created. This ticket handles the creation of plans but does not address the creation of features for those plans. Since some features will be used in multiple plans, I decided to separate them into two distinct endpoints (and also in the database schema).

**Comment by phurhard** [comment]
What of #55

**Comment by Sidney2022** [comment]
I actually didn't see that before even though I did a search before creating the issue. It seems I would have to close the other issue(#202 )
However, the issue #55 does not seem to have any feature for the created plans. Can I discuss with the creator to add it? Plans need features

**Comment by phurhard** [comment]
You can, and if the creator is not working on it again, Lemme know so it can be assigned to you.

**Comment by Sidney2022** [comment]
Alright thanks

**Comment by Sidney2022** [comment]
I've reached out to the creator of  issue #55 and it has now been modified. pls confirm. @phurhard
