### ISSUE TITLE
[FEAT]: add reactions-functionality endpoints

### ISSUE THREAD

**Issue by Jhonneto003** [hngprojects/hng_boilerplate_nestjs#210]
## Description
Implement a feature that allows users to react to posts with predefined emojis.

**## Acceptance Criteria**

1. Database schema design which includes tables for reactions for Reactions, BlogPosts, and Users.
2. Reactions are correctly linked to blogposts and users
3. API endpoints are created for :
      Adding a reaction to a blog post (POST /api/reactions).
      Editing a reaction (PUT /api/reactions/:reaction_id).
      Deleting a reaction (DELETE /api/reactions/:reaction_id).
     Retrieving reactions associated with a blog post (GET /api/reactions/:post_id).
4. API endpoints should handle errors e.g invalid inputs with appropriate HTTP status codes and error messages

### Purpose
To increase user interaction and provide quick feedback mechanisms.

### Requirements	
1. Develop a database schema to store reactions, linking them to a blog posts and users.
2. Create endpoints to add a reaction to a blog post, edit a reaction. delete and retrieve reactions relating with a blog post.

### Expected Outcome
Users can interact with blog posts by adding, viewing, editing or deleting reactions using API endpoints.

_**Request**_
**Add a reaction**: POST /api/reactions
success response
{
"emoji": "(the designated emoji)"
}

**Edit a reaction**: PUT /api/reactions/{reaction_id}
success response
{
"emoji": "(the emoji with the id appears")
}
error response
{
"error": "Reaction not found"
}

**Delete a reaction**: DELETE '/api/reactions/{reaction_id}'
success response
{
"message": "deleted successfully"
}
error response
{
"error": "Reaction not found"
}

***Retrieve a reaction****: GET '/api/reactions/{reaction_id}'
success response
{
"id": '(valid reaction id)',
"emoji": '(valid emoji stored)'
}
error response
{
"error": "Reaction not found"
}

### Testing
Unit tests are written for each API endpoint to verify its functionality.
Integration tests ensure that reactions interact correctly with the database and other system component.

**Comment by markessien** [comment]
this is out of scope

**Comment by Jhonneto003** [comment]
Pls I don't understand what you mean by this?
