### ISSUE TITLE
[FEAT]: Create Endpoints for Admin to Fetch All Organizations

### ISSUE THREAD

**Issue by salissadiq** [hngprojects/hng_boilerplate_nestjs#215]
## Description
Create an endpoint for admin to fetch all organisations from the system. This endpoint will allow only admins to retrieve a list of all available organisations efficiently and securely.

## Acceptance Criteria
- [ ] The endpoint should follow RESTful API standards.
- [ ] The operation should return the correct HTTP status code:
- [ ] Success: 200 OK
- [ ] The response body should match the provided example.
- [ ] The API should be secure, ensuring only admin users can access the list of organisations.

Fetch All Organisations

Endpoint: `GET /api/v1/organisations`

**Successful Response**

Status code: 200

```json
{
  "status": "success",
  "status_code": 200,
  "organisations": [
    {
    "id": 1,
    "name": "Organisation One",
    "description": "Description for organisation one.",
    "created_at": "2024-07-18T12:34:56Z"
  },
  {
    "id": 2,
    "name": "Organisation Two",
    "description": "Description for organisation two.",
    "created_at": "2024-07-18T12:34:56Z"
  }
    ...
  ]
}
```

**Error Response**

Status code: 401

**Unauthenticated.**

```json
{
  "status": "Unauthorized",
  "message": "Not authenticated",
  "status_code": 401
}
```
Status code: 403

**Forbidden.**

```json
{
  "status": "Forbidden",
  "message": "Don't have permission to access",
  "status_code": 403
}
```
### Purpose
The purpose of this endpoint is to allow admins to fetch a comprehensive list of all organisations available in the system. This will help admins to easily view and access organization details.

### Requirements	
- [ ] The request user must be authenticated with jwt token to retrieve the organisations
- [ ] The request user must have admin role to access the endpoint

### Expected Outcome
- [ ] Successful implementation of the fetch all organizations endpoint.
- [ ] An intuitive and secure way for admins to retrieve a list of organisations.
- [ ] Increased efficiency in accessing organisation-related information.
- [ ] Improved admin experience by providing easy access to organisation details.

### Unit Testing
- [ ] Ensure the endpoint correctly identifies if the requesting user is signed in
- [ ] Ensure the endpoint correctly identifies if the requesting user is an admin
- [ ] Test the endpoint to correctly fetch all the organisations

**Comment by markessien** [comment]
normal users do not need to, and do have the right to list all orgs

**Comment by salissadiq** [comment]
@markessien 
I have revisited the ticket and corrected it
