### ISSUE TITLE
[FEAT] Endpoint to Fetch FAQ

### ISSUE THREAD

**Issue by JumongComputers** [hngprojects/hng_boilerplate_nestjs#216]
## Description
Implement a new API endpoint that allows the front-end application to fetch frequently asked questions (FAQs) from the database. The endpoint should retrieve the FAQs, format the response in JSON, and implement appropriate error handling.

### Acceptance Criteria

1. An endpoint `/api/v1/faqs` that performs HTTP `GET` request
2.The endpoint returns a JSON response containing a list of FAQs with `id`, `question`, and `answer` fields.
3. Returns a `400` status code and the correct response body when the request data is invalid.
4. The response includes metadata (`totalItems`, `totalPages`, `currentPage`, and `faqs`).
5. Returns an appropriate error message when an error occurs.
6. Code review is performed and approved before merging the changes.

### Requirements	

- Create an API endpoint at `/api/v1/faqs`.
- The endpoint should support HTTP `GET` requests.
- The response should be in JSON format.
- Handle unexpected errors and return the appropriate status code.
-  The endpoint supports pagination with page and limit query parameters.

### Expected Outcome

- A functional and reliable GET `/api/v1/faqs` endpoint.

### Endpoints
##[GET]`/api/v1/faqs`

- **Description:** Fetch Frequently Asked Question.
-**Success Response**
    - Status: `200 Ok`
    - Body
  
```{
  "totalItems": 2,
  "totalPages": 1,
  "currentPage": 1,
  "faqs": [
    {
      "id": 1,
      "question": "What is your return policy?",
      "answer": "You can return any item within 30 days of purchase."
    },
    {
      "id": 2,
      "question": "How can I track my order?",
      "answer": "You can track your order using the tracking link sent to your email."
    }
  ]
}

```
-**Bad Response**
    - Status: `400 Bad response`
    - Body
 
 ```json
{
  "message": "Could not fetch FAQ",
  "status_code": 400
}
```

**Comment by Dev-wonderful** [comment]
Why does backend need to handle this

**Comment by JumongComputers** [comment]
> Why does backend need to handle this

It should be similar questions that has been answered by the admin that comes up often that will be fetched by this endpoint. Except you're suggesting that it will be a static set of questions and will not be updating
