### ISSUE TITLE
[FEAT] Develop a Pricing Display Page

### ISSUE THREAD

**Issue by kamaufnjeri** [hngprojects/hng_boilerplate_nestjs#22]
## Description:
Implement a dynamic pricing display page for all services that adheres to the Figma design specifications. This page will present comprehensive pricing information to users, enhancing their decision-making process.

## Acceptance Criteria:
- All service pricing information is retrieved from the backend and displayed accurately for all services.
- Discounts are correctly applied and displayed alongside original prices.
- The layout is fully responsive and usable on both mobile and desktop devices.
- All unit tests must pass, ensuring components render correctly with varying data states.
- Users can see fallback messages when there are errors in data retrieval.

### Purpose:
To provide users with clear visibility into the costs associated with each service offered, including details on any current discounts or promotional offers.

### Requirements:
- **Responsive Layout:** Design a mobile-friendly layout that maintains usability across different screen sizes.
- **Data Retrieval:** Integrate with the backend API to fetch real-time pricing data for all services, ensuring accuracy and consistency.
- **Pricing Information:** Display the following for each service:
  - Standard price
  - Discounted price (if applicable)
  - Description of the service
  - Any promotional offers
- **Error Handling:** Implement proper error handling for data retrieval failures, with fallback messages to ensure a smooth user experience.

### Expected Outcome:
Develop a fully functional pricing display page that presents accurate and up-to-date pricing information for all services. The page should effectively highlight any discounts or promotional offers, with clear distinctions between original and discounted prices. Users should navigate the page effortlessly, facilitating informed decisions regarding service selection.

### Checklist:
- [ ] **Frontend Development:** 
  - Implement the design and layout based on Figma specifications.
  - Create reusable components for service cards and pricing displays.
- [ ] **API Integration:** 
  - Fetch pricing data from the backend and handle state updates for all services.
- [ ] **Discounts Implementation:**
  - Include logic to determine and display discounts or promotional offers.
- [ ] **Testing:** 
  - Write unit tests, integration tests, and end-to-end tests to ensure functionality and robustness.
  
### Labels:
- Frontend
- Payment
- Pricing

### Testing:
- **Unit Tests:** Write unit tests for each component to ensure correct rendering of pricing information and conditional rendering for discounts.
- **Integration Tests:** Validate integration with the backend API, checking for accurate data retrieval and error handling.
- **End-to-End Tests:** Implement end-to-end tests to simulate user interactions with the pricing page, ensuring a smooth user experience from data fetching to display.

**Comment by markessien** [comment]
This is a backend repo, not a frontend repo
