### ISSUE TITLE
[FEAT] API Endpoint to Setup AI Integration for content generation (eg. OpenAI)

### ISSUE THREAD

**Issue by WaveGuide1** [hngprojects/hng_boilerplate_nestjs#221]
### Description:

Integrate the OpenAI API to enable content generation within the application. This feature allows users to generate content such as essays, articles, and other text-based materials using OpenAI's language models.

### Scope:

- Setup and configure the OpenAI API.
- Create API endpoints to handle content generation requests.
- Implement input and output validation.
- Ensure proper authentication and authorization.
- Handle errors and edge cases efficiently.
- Optimize performance and ensure security.
- Provide comprehensive documentation and testing.

### Acceptance Criteria
- API keys are obtained and securely stored using environment variables.
- The API client library is installed and configured.
- Endpoint `/api/v1/openai/content` is created and functional.
- Input and output data validations are implemented.
- Proper authentication and authorization are enforced.
 - Error handling for common and edge cases is implemented.
 - Comprehensive unit and integration tests are provided.
- API documentation is complete and clear.

### Data Validation

**Input Validation:**

- Ensure the request body contains valid and correctly formatted data.
- Validate the presence and type of required fields.

**Output Validation:**

- Ensure the response contains valid and correctly formatted data.
- Validate the structure and data types of the response.

### Authentication and Authorization

**Authentication:**

- The endpoint must require a valid API key for access.
- Use environment variables to securely manage API keys.

**Authorization:**

- Define rules to ensure only authorized users can access the endpoint.
- Implement role-based access control (RBAC).

### Endpoint Details
**Endpoint: POST /api/v1/openai/content**
- **Request body:**
```json
{
  "input": "text"
}
```
**Success Response:**
- **Status Code: 200**
- **Response Body:**
```json
{
  "status": "success",
  "data": {
    "generatedContent": "AI generated content"
  }
}
```
### Error Handling

**Error Responses:**

**Authentication Error:**
- **Status Code: 401**
- **Response Body:**
```json
{
  "status": "error",
  "message": "Authentication failed"
}
```
**Invalid API Key Error:**
- **Status Code: 403**
- **Response Body:**
```json
{
  "status": "error",
  "message": "Invalid API key"
}
```
**Data Validation Error:**
- **Status Code: 400**
- **Response Body:**
```json
{
  "status": "error",
  "message": "Invalid input data",
  "errors": [
    "Input text is required",
    "Input text must be a string"
  ]
}
```
**Other likely Failure Scenarios:**
- **Status Code: 500**
- **Response Body:**
```json
{
  "status": "error",
  "message": "Internal server error"
}
```
### Edge Cases:
- Consider and handle edge cases such as network failures, API timeouts, and unexpected data formats.

### Performance and Security

**Performance Considerations:**
- Optimize data retrieval and processing to ensure efficient performance.
- Implement caching strategies where applicable.

**Security Concerns:**
- Implement rate limiting to prevent abuse.
- Use HTTPS to secure data transmission.

### Documentation
**API Documentation:**
- Provide comprehensive documentation for the `/api/v1/openai/content` endpoint, including request and response examples.
- Document authentication and authorization requirements.

### Testing Requirements

**Unit Tests:**
- Implement unit tests to verify the functionality of individual components.
- Ensure tests cover both success and failure scenarios.

**Integration Tests:**
- Implement integration tests to verify the API works as expected with the rest of the system.
- Test the interaction between different components and services.

### Dependencies and Impact

**Dependencies:**
- Identify any dependencies on other tasks or systems, such as database configurations or external services.

**Impact Analysis:**
- Assess the potential impact on other features or components.
- Ensure the integration does not introduce conflicts.

### Database Design
- Database design is not needed unless stated otherwise by the team lead (Saving every generated content to database is not feasible and economical)

**Comment by WaveGuide1** [comment]
Poche
Esther Linus
Ancestor

**Comment by posh1001** [comment]
poche - Nest.js
Ancestor - FastAPI
Esther Linus - Java

**Comment by NecyNazy** [comment]
SLID: Esther Linus-Chinaza Esther Nwachukwu(Java Dev)

**Comment by phurhard** [comment]
This doesn't flow at all, like what's the scope.

**Comment by WaveGuide1** [comment]
Sir, The issue have been updated for second review.
@phurhard
