### ISSUE TITLE
[FEAT]: Product - Add Product Reviews

### ISSUE THREAD

**Issue by khayss** [hngprojects/hng_boilerplate_nestjs#224]
## Description
Develop an endpoint allowing users to submit product reviews and ratings. This feature should be robust, user-friendly, and integrate seamlessly with our current product pages.

## Acceptance Criteria

- [ ] A `POST` endpoint available at `/api/v1/products/:product_id/review`.
- [ ] Successfully handle processing and storing of reviews for a specified product.
- [ ] Users should be able to submit a review including a text comment and a rating from 1 to 5.
- [ ] Ensure validation of input data to prevent malformed or incomplete product entries.
- [ ] Appropriate HTTP status codes are returned (e.g., 201 Created for success, 400 Bad Request for invalid input).

### Purpose
- Enhance user engagement by allowing customers to share their experiences.
- Provide valuable feedback to other customers and our product team.
- Increase transparency and trust in our products.

### Requirements	
1. Create a backend endpoint to handle product review creation requests.
2. Validate input data to ensure all necessary fields are provided and correctly formatted.
3. Ensure proper error handling and response statuses.
4. Update any related data or references accordingly.

### Expected Outcome

- A `POST` endpoint at `/api/v1/products/:product_id/review` that:
  - Accepts product review data (e.g., rating, comment, userId, category, etc.).
  - Validates the input data.
  - Save the new product review into the database.
  - Returns a 201 Created status with the created product review.
  - Returns appropriate error messages and statuses for invalid input or server errors.

### Request Body:
```json
{
"user_id": "string",  // e.g. "ADCVS5566..."
"rating": "number",  // between a range of 1 - 5, e.g. 4.5
"comment": "string", // e.g "I like this product"
}
```

### Successful Response (status code: 201);

```json
{
"success": true,
"message": "string", // e.g. created successfully
"data": {
"user_id": "string",  // e.g. "ADCVS5566..."
"rating": "number",  // between a range of 1 - 5, e.g. 4.5
"comment": "string", // e.g "I like this product"
}
}
```

### Error Response (status code: 422):
```json
{
"success": false,
"status_code": 422,
"error": [
{"field": "string",  // e.g. "comment"
"message": "string" // e.g. "this field must be a string"
},
{"field": "string",  // e.g. "rating"
"message": "string" // e.g. "this field must be a number within 1 to 5"
}
]
}
```

### Error Response (status code: 401):
```json
{
"success": false,
"status_code": 401,
"error": "string" // e.g. "bad request"
}
```

### Error Response (status code: 404):
```json
{
"success": false,
"status_code": 422,
"error": "string" // e.g. "product not found"
}
```

### Error Response (status code: 500):
```json
{
"success": false,
"status_code": 500,
"error": "string" // e.g. "something went wrong"
}
```

**Comment by markessien** [comment]
We do not have the Reviews feature in our boilerplate
