### ISSUE TITLE
[FEAT] Fetch All Organisations Endpoint - Backend

### ISSUE THREAD

**Issue by SCCSMARTCODE** [hngprojects/hng_boilerplate_nestjs#225]
### Description

**Description:**
Create an endpoint to fetch all organisations from the system. This endpoint will allow users to retrieve a list of all available organisations efficiently and securely.

### Acceptance Criteria

**Title:**
Create Endpoint to Fetch All Organisations

---

**Acceptance Criteria:**

1. **RESTful Standards:**
   - The endpoint should follow RESTful API standards.

2. **HTTP Status Codes:**
   - Success: `200 OK`

3. **Response Body:**
   - The response body should match the provided example.

4. **Security:**
   - The API should be secure, ensuring only authorized users can access the list of organisations.

---

**Fetch All Organisations**

- **Endpoint:** `GET /api/v1/organisations`

---

**Successful Response:**

```json
{
  "status": "success",
  "status_code": 200,
  "organisations": [
    {
      "id": 1,
      "name": "Organisation One",
      "description": "Description for organisation one.",
      "created_at": "2024-07-18T12:34:56Z"
    },
    {
      "id": 2,
      "name": "Organisation Two",
      "description": "Description for organisation two.",
      "created_at": "2024-07-18T12:34:56Z"
    }
  ]
}
```

---

**Error Response:**

- **Status code:** `401 Unauthenticated`

```json
{
  "status": "Unauthorized",
  "message": "Unauthorized access.",
  "status_code": 401
}
```

---

**Purpose:**
The purpose of this endpoint is to allow users to fetch a comprehensive list of all organisations available in the system. This will help users to easily view and access organization details.

---

**Requirements:**
- [ ] User must be authenticated with a JWT token to retrieve the organisations.

---

**Expected Outcome:**
- Successful implementation of the fetch all organisations endpoint.
- An intuitive and secure way for users to retrieve a list of organisations.
- Increased efficiency in accessing organisation-related information.
- Improved user experience by providing easy access to organisation details.

---

**Unit Testing:**
- [ ] Ensure the endpoint correctly identifies if the user is signed in.
- [ ] Test the endpoint to correctly fetch all the organisations.
- [ ] Test that an error is thrown when an invalid or missing JWT token is provided

**Comment by ugberaeseac** [comment]
I think this has been worked on and approved

**Comment by SCCSMARTCODE** [comment]
Not at all

**Comment by markessien** [comment]
I have seen this ticket many times

**Comment by phurhard** [comment]
Check #215  are you doing same thing ??
