### ISSUE TITLE
[FEAT]: Implement Switch Organisation API Endpoint

### ISSUE THREAD

**Issue by Moses-Oyelade** [hngprojects/hng_boilerplate_nestjs#226]
## Description:
Develop API endpoint to handle requests to switch/change an autthorized user active organisation where it is only open to authorized/admin user. If the organisation is switched/changed successfully, it should return Status_code "201" to the client.

## Acceptance Criteria:

- The endpoint switches to another organisation as the authorized user's active organisation.
- If the user is not authenticated, the endpoint should return a 401 Unauthorized status with an appropriate error message.
- If user active organisation switch/changes is successful, it should return a 201 OK status code.
- Endpoint is [UPDATE/PUT] /api/v1/users/{user_id}/organisations/{organisation_id}

### Request Body application/json
{
    "active": boolean
}

### Success load
{
    "message": "organisation successful updated",
    "data": {
        "id": "string",
        "active": True,
        "update_at": "datetime"
    }
}

### Error load
{
    "message": "Unauthorized request",
    "status_code": 404
}

### Purpose:
Enable backend handling of organization switches to allow admin switch/change their active organization within the application.

### Requirements:

- [ ] Ensure the user is authenticated with a valid JWT token.
- [ ] Endpoint allows submission of switch to new active organization.
- [ ] Endpoint returns proper error messages for unauthorized access, validation errors and internal server errors.
- [ ] Athourized user must have an organisation set as active by default.

### Expected Outcome:

A fully functional API endpoint that allows authorized users to retrieve all organizations they belong to by their user ID and be able to SWITCH/CHANGE active organisation, If the user does not belong to any organizations, the response should reflect that no organizations were found.

### Test

- Write unit tests to ensure the endpoint correctly retrieves the particular organisation to be set active.
- Test that the endpoint returns 401 Unauthorized when the request is made by an unauthorized user.
- Test that the endpoint is accessible to authorized users alone.

**Comment by highb33kay** [comment]
Update your response to fit the approved response structure
