### ISSUE TITLE
[FEAT] Create Squeeze Page Endpoint 

### ISSUE THREAD

**Issue by mjoghenemaega** [hngprojects/hng_boilerplate_nestjs#229]
## Description
Create an API endpoint to allow users to create a new squeeze page. This endpoint will accept a JSON payload with the details of the squeeze page and return the created squeeze page information.

## Acceptance Criteria

- This endpoint (/api/v1/squeeze-pages/) correctly handles the POST request and creates a new squeeze page.
- The response includes the newly created squeeze page with all provided details.
- The system returns a 201 Created status code on successful creation.
- Proper error handling is in place for invalid requests or server errors.
- The endpoint should be optimized for efficient database interaction and response time.

### Purpose
To enable administrators to create and manage squeeze pages, allowing clients to capture leads and provide targeted content effectively.

### Requirements	
pages.
- [ ] Create the API endpoint for creating squeeze pages.
- [ ] Implement efficient database interaction to store squeeze page data.
- [ ] Ensure proper validation of input data to prevent invalid requests.
- [ ] Implement error handling for invalid requests or server-side issues.
- [ ] Return a 201 Created status code upon successful creation.
- [ ] Include a response body with the created squeeze page details.
- [ ] Optimize the endpoint for quick response times and efficient data handling.

## Endpoint Details

**Method: POST
Endpoint: /api/v1/squeeze-pages/**

**Request Body:**
```
{
  "title": "Exclusive Offer",
  "content": "<h1>Get Our Exclusive Offer!</h1><p>Sign up now to receive a special discount.</p>",
  "metadata": {
    "description": "A special offer for our new customers",
    "keywords": ["offer", "discount", "exclusive"]
  }
}
```

 **Success Response:**

- Status Code: 201 Created
- Response Body:
``` 
{
  “status_code”: 201,
  "status": "success",
  "message": "Testimonial created successfully",
  "data": 
      {
        "id": 1,
        "title": "Exclusive Offer",
        "content": "<h1>Get Our Exclusive Offer!</h1><p>Sign up now to receive a special discount.</p>",
        "metadata": {
          "description": "A special offer for our new customers",
          "keywords": ["offer", "discount", "exclusive"]
        }
      }
}

```

 **Error Responses:**

- Status Code: 400 Bad Request
   Reason: The request payload is invalid (e.g., missing required fields).
```
{
   "status_code": 400,
    "code": "INVALID_REQUEST",
    "message": "The request payload is invalid.",  
}

```
  

- Status Code: 500 Internal Server Error
   Reason: An unexpected error occurred on the server.
```
{
   "status_code": 500,
    "status": "INTERNAL_SERVER_ERROR",
    "message": " An unexpected error occurred while processing your request.",
}
```

### Expected Outcome

- Clients can successfully create a new squeeze page.

- The endpoint provides accurate and up-to-date information about the created squeeze page.

- The system handles errors gracefully, providing clear messages to the client.

- The feature performs well with quick response times.

 ### Additional Information

- Consider implementing input validation to ensure required fields are present.

- Plan for future scalability to handle a growing number of squeeze pages.

### Testing Requirements

- Perform manual tests to verify the API endpoint response structure and data accuracy.

- Write unit tests for the creation logic.

- Write integration tests to ensure proper database interaction and response formatting.

- Test error scenarios to ensure proper error handling and messaging.

**Comment by phurhard** [comment]
#80 #69 
Help your self and confirm your tickets are not duplicated

**Comment by mjoghenemaega** [comment]
> What's a squeeze page self? #80 #69 Help your self and confirm your tickets are not duplicated

yes boss , its not duplicated . and squeeze pages are pages used for promoting the main app or site ... they should be able to be added without touching the code .

**Comment by mjoghenemaega** [comment]
> What's a squeeze page self? #80 #69 Help your self and confirm your tickets are not duplicated

i don die ... hahaha ...

**Comment by coderoyalty** [comment]
@mjoghenemaega you can't do this.

**Comment by Shullyd7** [comment]
Looks like a duplicate
