### ISSUE TITLE
[FEAT] Loading Animation for Page Load

### ISSUE THREAD

**Issue by Benedict-arowo** [hngprojects/hng_boilerplate_nestjs#23]
## Description
This will help show some form of animation while the page is loading data from the backend or still loading the page.

## Acceptance Criteria

1. Loading Animation:
   - A skeleton loader is displayed when the page is initially visited.
   - A skeleton loader is displayed when the page is loading heavy data.

2. Stop Loading Animation:
   - The loading animation stops when the page is fully loaded.
   - The transition from the loading animation to the fully loaded page is smooth and user-friendly.

### Requirements
1. Show Animation While Page is Loading:
   - Implement a skeleton loader state when you just visit the page.
   - Implement a skeleton loader state when the page is loading heavy data.

2. Stop Loading Animation When Page is Fully Loaded:
   - Ensure the loading animation stops when the page is fully loaded.

### Expected Outcome
- [ ] A loading animation is displayed while the page is loading data from the backend or still loading.
- [ ] The loading animation stops once the page is fully loaded.

### Testing
1. Unit Tests:
   - Write unit tests to ensure the loading animation is displayed correctly.
   - Test various scenarios, including initial page load and loading heavy data, to verify the loading animation behavior.
2. Performance Testing:
   - Ensure the loading animation does not significantly impact page performance.
   - Test the transition from loading to fully loaded state to ensure it is smooth.

**Comment by markessien** [comment]
This is a backend repo, not a frontend repo
