### ISSUE TITLE
[FEAT] Implement API Endpoint to DELETE Subscription Plans: By Admin

### ISSUE THREAD

**Issue by thenoblet** [hngprojects/hng_boilerplate_nestjs#231]
## Description
Implement the endpoint to delete a specific plan.
This feature will enable administrators to manage existing subscription plans by allowing them to delete plans as necessary.

## Purpose
- To allow administrators to delete a specific plan by its ID.

### Delete Plan
- Delete a specific plan by its ID.
- Ensure authentication and authorization mechanisms for administrators.
- Return a success message upon successful deletion.
- Proper error handling for scenarios where the plan does not exist or deletion fails.

### Delete Plan
- Delete a specific plan by its ID.
- Ensure request is from authorized and authenticated admin.
- Return a success message upon successful deletion.
- Proper error handling for scenarios where the plan does not exist or deletion fails.

## Expected Outcome
- An endpoint to delete a plan.
- Appropriate success and error responses for the endpoint.

## Checklist
1. #### Delete Plan
- [ ] Implement `DELETE /api/v1/plans/{id}` endpoint
- [ ] Validate plan ID
- [ ] Secure endpoint with authentication and authorization for administrators.
- [ ] Handle and return errors

### Testing
- [ ] Write unit and integration tests for the endpoint
- [ ] Test successful delete operations.
- [ ] Test edge cases and error scenarios thoroughly.

### Documentation
- [ ] Document the endpoint, including request and response formats.
- [ ] Include information on error handling and possible scenarios.

### Delete Plan
**Description**: Delete a specific plan.  
**Endpoint**: `DELETE /api/v1/plans/{id}`  
**Authentication**: Required  
**Authorization**: Administrators only  
**Response (Success)**:
```json
{
  "message": "Plan deleted successfully.",
  "status_code": 200
}
```

**Response (Error: General Failure)**:
```json
{
  "message": "Failed to delete plan.",
  "status_code": 500
}
```

**Response (Error: Plan Not Found)**:
```json
{
  "message": "Plan not found.",
  "status_code": 404
}
```

**Comment by thenoblet** [comment]
Hello Mentors, this issue complements the existing issue **[[FEAT] Implement API Endpoints for Creating Subscription Plans](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/55).** While the existing issue focuses on creating subscription plans, my issue addresses the endpoints required for **reading**, **getting**, and **deleting** those subscription plans.

The goal is to complete the suite of **CRUD** operations for subscription plans, ensuring a comprehensive API that covers all necessary interactions with subscription data.

**Comment by phurhard** [comment]
Update your response to follow the given criteria

**Comment by thenoblet** [comment]
> Update your response to follow the given criteria

@phurhard I have updated it. Using the snake_case now.

**Comment by highb33kay** [comment]
This is 3 endpoints? @phurhard 

I think this should be separated into three tickets to allow better tracking

@thenoblet

**Comment by thenoblet** [comment]
> This is 3 endpoints? @phurhard
> 
> I think this should be separated into three tickets to allow better tracking
> 
> @thenoblet

@phurhard, 2 endpoints please. To retrieve and delete a subscription plan.

**Comment by highb33kay** [comment]
Yes, you do. Two tickets for easier tracking by PMS

**Comment by highb33kay** [comment]
Please create and attach second ticket here

**Comment by thenoblet** [comment]
@highb33kay and @phurhard, so I found out that there is an issue for RETRIEVE already. So I edited this endpoint for the DELETE operation only.

Existing issue for RETRIEVE:
