### ISSUE TITLE
[FEAT] Implement Endpoint to UPDATE About Page Content: settable from admin

### ISSUE THREAD

**Issue by thenoblet** [hngprojects/hng_boilerplate_nestjs#235]
## Description
Implement an endpoint to **UPDATE** the content of the About page, allowing administrators to modify the information efficiently.

---

## Purpose
- Enable administrators to update the content of the About page dynamically.

---

### Update About Page Content
- Update the content of the About page with new information provided by administrators.
- Return a success message upon successful update.
- Properly handle scenarios where the update fails.

---

### Update About Page Content
- Implement `PUT /api/v1/content/about` endpoint to update About page content.
- Validate incoming content to ensure it meets required criteria.
- Ensure authentication and authorization mechanisms for administrators.
- Handle and return errors gracefully, specifying different error conditions.

---

## Expected Outcome
- Implementation of the endpoint to update About page content.
- Clear and appropriate responses for success and error cases.
- Documentation and testing to ensure reliability and functionality.

---

## Checklist
1. #### Update About Page Content
- [ ] Implement `PUT /api/v1/content/about` endpoint.
- [ ] Validate incoming content and handle errors effectively.
- [ ] Secure endpoint with authentication for administrators.
- [ ] Document endpoint, including request and response formats.

### Testing 
- [ ] Write unit and integration tests covering various scenarios.
- [ ] Test successful update operations.
- [ ] Test edge cases and error scenarios thoroughly.

### Documentation:
- [ ] Document the endpoint, including request and response formats.
- [ ] Include information on authentication requirements and error handling.

---

## Endpoint

**Description**: Update the content of the About page.  
**Endpoint**: **`PUT /api/v1/content/about`**  
**Authentication**: Required  
**Authorization**: Administrators only  
**Request Body**:
```json
{
    "title": "More Than Just A BoilerPlate",
    "introduction": "Welcome to Hng Boilerplate, where passion meets innovation.",
    "custom_sections": {
      "stats": {
        "years_in_business": 10,
        "customers": 75000,
        "monthly_blog_readers": 100000,
        "social_followers": 1200000
      },
      "services": {
        "title": "Trained to Give You The Best",
        "description": "Since our founding, Hng Boilerplate has been dedicated to constantly evolving to stay ahead of the curve."
      }
    }
}
```

**Response (Success)**:
```json
{
  "message": "About page content updated successfully.",
  "status_code": 200
}
```
**Response (Error: Server Error)**:
```json
{
  "message": "Failed to update About page content.",
  "status_code": 500
}
```
**Response (Error: Unauthenticated)**:
```json
{
  "message": "Invalid authentication credentials",
  "status_code": 401
}
```

**Response (Error: Authenticated but Unauthorised)**:
```json
{
  "message": "You do not have permission to perform this action.",
  "status_code": 403
}
```

## Additional Notes:
- This endpoint is designed to complement the **RETRIEVE** operation described in the issue #265  . 
- Ensuring consistency with the UPDATE operation in issue #265 is crucial. Please review the request and response formats, validation rules, and authentication/authorization mechanisms stated in that issue.
- Consistent error handling is important for a seamless user experience. Align the error messages and status codes with those defined in issue #265 
- Documentation and testing should cover both endpoints thoroughly. Please refer to the documentation and test cases of the UPDATE operation to ensure all scenarios are addressed.
- Authentication and authorization are mandatory for this endpoint to restrict access to administrators only. Follow the same security protocols as described in issue #265 
- Keep the custom sections flexible and extendable. Future modifications should allow easy addition of new sections without major changes to the structure.

**Comment by markessien** [comment]
I suggest that you use a more generic key-value system and do not pre-define the individual pieces. This way people can add new sections to the about page

**Comment by thenoblet** [comment]
> I suggest that you use a more generic key-value system and do not pre-define the individual pieces. This way people can add new sections to the about page

Yessir! On it. 🫡

**Comment by thenoblet** [comment]
@markessien, I refined the issue, Sir.

### Updated Issue with Key-Value System
The updated issue uses a generic key-value system, which allows for a more dynamic and flexible approach to managing the About page content.

#### Updates Made
I added a **customSections** key that can hold any number of key-value pairs. This makes it easy to add, modify, or remove sections without changing the backend code.

Administrators can simply add a new key-value pair to the **customSections** object, such as **"history": "Our company was founded in..."**, without requiring any changes to the backend.

**Example: Adding a new "history" section**
**Endpoint**: `PUT /api/v1/about`
**Request Body**:
```json
{
  "content": {
    "title": "More Than Just A BoilerPlate",
    "introduction": "Welcome to Hng Boilerplate, where passion meets innovation.",
    "customSections": {
      "stats": {
        "yearsInBusiness": 10,
        "customers": 75000,
        "monthlyBlogReaders": 100000,
        "socialFollowers": 1200000
      },
      "services": {
        "title": "Trained to Give You The Best",
        "description": "Since our founding, Hng Boilerplate has been dedicated to constantly evolving to stay ahead of the curve."
      },
      **"history": "Our company was founded in 2010..."**
    }
  }
}
```

**Comment by highb33kay** [comment]
More than one endpoints. Please break it up and focus on one specific endpoint for easy tracking 

@thenoblet

**Comment by highb33kay** [comment]
Response doesnt follow org structure. 

```
{
  "content": {
    "title": "More Than Just A BoilerPlate",
    "introduction": "Welcome to Hng Boilerplate, where passion meets innovation.",
    "customSections": {
      "stats": {
        "yearsInBusiness": 10,
        "customers": 75000,
        "monthlyBlogReaders": 100000,
        "socialFollowers": 1200000
      },
      "services": {
        "title": "Trained to Give You The Best",
        "description": "Since our founding, Hng Boilerplate has been dedicated to constantly evolving to stay ahead of the curve."
      }
    }
  },
  "updatedAt": "2024-07-18T12:00:00Z",
  "statusCode": 200
}
```

**Comment by thenoblet** [comment]
@highb33kay, I have refined it to include authorisation & authentication, broken them into specific endpoints, and changed the Response to follow org structure.

RETRIEVE operation issue #265

**Comment by githukueliud** [comment]
Hello

**Comment by nadduli** [comment]
Hello

**Comment by thenoblet** [comment]
@markessien, @highb33kay

**An Afterthought (DB schema):**
Whilst implementing this, I realised it'd be cool to track which admin made changes to the content of the About Page. So, I'll need to extend the database schema and application logic to include user information for auditing purposes.

Is that something I can do, please? The DB and Auth guys are not really coming to through for us. Painful.

@nadduli and @githukueliud, guys look out for the response here.
