### ISSUE TITLE
[FEAT] MUB-016 Rename  API 

### ISSUE THREAD

**Issue by mwihoti** [hngprojects/hng_boilerplate_nestjs#239]
## Description 

Create API endpoints and request schema to rename teams.

## Acceptance Criteria
- Allow admins to rename teams through rename action.
- Provide API endpoint for renaming teams.
- Handle success and error responses for rename.
- Write tests for  endpoint.

  
### Endpoints
[PATCH] /api/v1/team/{teamId}/rename

Renames the team with the specified ID.

### Request Body

```
{ "newName": "string" }
```
### Successful

Status code: 200

```
{ 
"message": "Team renamed successfully.",
"teamId": 123, "newName": 
"New Team Name"
 }
```

### Error Response

Status code: 400

```
{
"error": "Bad Request", 
"message": "Invalid name provided."
}
```

Status code: 404
```
{
"error": "Not Found",
"message": "Team not found."
}
```

Status code: 403

```
{
"error": "Forbidden", 
"message": "You do not have permission to delete this team."
}
```

## Secure Endpoints

Authentication & Authorization:
- Ensure the user is authenticated.
- Verify that the user has the necessary permissions to perform management actions on teams.
- 
## Write Tests
Unit Tests:
- Test successful renaming of a team.
- Test invalid requests with missing or incorrect data.
- Test for non-existent team ID.
- Test for proper handling of permissions.

**Comment by mwihoti** [comment]
@mufidat3250

**Comment by markessien** [comment]
No such concept as teams in this app

**Comment by mwihoti** [comment]
> No such concept as teams in this app

Thank you for pointing that out. I have revised the ticket

**Comment by markessien** [comment]
Person is unable to understand the problem after multiple feedback attempts.
