### ISSUE TITLE
[FEAT] Implementing Organization Deletion API

### ISSUE THREAD

**Issue by kehman18** [hngprojects/hng_boilerplate_nestjs#244]
## Description
Develop an API endpoint that allows super admins to delete an organization from the system, ensuring proper validation, permission checks, and cascading deletions of related entities such as users and projects. This feature will help maintain the integrity and cleanliness of the organizational data within the system.

## Acceptance Criteria
1. Deletion Endpoint

- Given a request with a valid organization ID and appropriate permissions, when the super admin deletes an organization, the system should delete the organization along with its dependent records and return a 200 OK status code.

2. Invalid Organization ID

- Given an invalid organization ID, when the super admin tries to delete an organization, the system should return a 404 Not Found status with an appropriate error message.

3. Permission Check

- Given a request from a user without super admin permissions, when the user tries to delete an organization, the system should return a 403 Forbidden status with an appropriate error message.

4. Cascading Deletion

- Given an organization with associated users and projects, when the super admin deletes the organization, the system should also delete all related users and projects.

### Expected Outcome

Request 

`DELETE /api/organizations/{organizationId}
`
```
{
  organization_Id: String (UUID),
  Authorization: Bearer <token>
}
```

Successful Response 

- Valid organization ID and appropriate permissions.

```
{
  "message": "Organization and related entities successfully deleted",
  "status_code": 200
}
```

- Deleting an organization with associated users and projects.
```
{
  "message": "Organization and related entities successfully deleted",
  "status_code": 200
}

```
Error Response

- When the Organisation ID does not exist
```
{
  "message": "Organization not found",
  "status_code": 404
  "error": "Not Found"
}

```

- When a user without super admin permissions tries to delete an organization
```
{
  "message": "Forbidden: You do not have the necessary permissions to perform this action",
  "status_code": 403
  "error": "Bad Request"
}
```

### Purpose
Implement a backend service used by the super admin to delete an organization using the organizationId

### Requirements	

- Implement authentication logic to ensure the client is signed in and has a valid token.

- Implement authorization logic to verify the client has super admin permissions to delete the organization.

- Validate the organization ID to ensure it exists in the system.

- Implement cascading deletion logic to delete all users, projects, and any other dependent entities associated with the organization.

- Handle errors by returning appropriate error messages for invalid organization ID, insufficient permissions, and other potential issues.

- Provide a success response with a message and status code when the organization and its related entities are successfully deleted.

### Testing

1. Unit Testing 

- Attempt to delete an organization with an invalid ID.

- Attempt to delete an organization by a user without super admin permissions.

**Comment by highb33kay** [comment]
I am closing this issue as duplicate issue #126
