### ISSUE TITLE
[FEAT] Implement Endpoints for Efficient Image Serving (Upload, Retrieve, and Compression)

### ISSUE THREAD

**Issue by thenoblet** [hngprojects/hng_boilerplate_nestjs#247]
## Description
Implement endpoints to serve images in an efficient manner, ensuring fast delivery and optimized performance. This includes handling image compression, resizing, and caching.

## Purpose
To provide a seamless and fast experience for users accessing images on the platform by optimizing image delivery.

---

### Image Serving
- Serve images efficiently from the server.
- Implement image compression and resizing.
- Support multiple image formats (e.g., JPEG, PNG, WebP).

### Image Upload
- Implement an endpoint to upload images.
- Validate and store uploaded images.
- Generate different sizes of the image for various use cases.

### Image Retrieval
- Implement an endpoint to retrieve images by ID.
- Support query parameters for specifying image size and format.

---

### Image Compression and Resizing
- Compress images to reduce file size without compromising quality.
- Resize images to different dimensions as needed.
- Generate multiple versions of an image (e.g., thumbnail, medium, large).

### Security
- Validate image uploads to prevent malicious files.
- Secure endpoints to ensure only authorized users can upload images.

---

## Expected Outcome
- [ ] Efficient and optimized image delivery.
- [ ] Endpoints to upload and retrieve images with support for different sizes and formats.
- [ ] Enhanced user experience with fast-loading images.

---

### Image Upload and Serving/Retrieval:
1. #### Upload Image
   - [ ] Implement POST /api/v1/images/upload endpoint
   - [ ] Validate image type
   - [ ] Handle image compression and resizing.
   - [ ] Document endpoint, including request and response formats.

2. #### Retrieve Image
   - [ ]  Implement GET /api/v1/images/{id} endpoint
   - [ ] Support size and format query parameters

### Testing:
- [ ] Write unit and integration tests for the upload endpoint.
- [ ] Test image upload, validation, and resizing.
- [ ] Test edge cases and error scenarios thoroughly.

### Documentation:
- [ ] Document the endpoint, including request and response formats.

---

### Upload Image
**Description**: Upload an image to the server.  
**Endpoint**: `POST /api/v1/images/upload`  
**Request (Body)**: `multipart/form-data`
```json
{
  "image": "File"
}
```

**Response (Success)**:
```json
{
  "message": "Image uploaded successfully.",
  "imageId": "String",
  "statusCode": 201
}
```

**Response (Error)**:
```json
{
  "message": "Failed to upload image.",
  "statusCode": 500
}
```

### Retrieve Image
**Description**: Retrieve an image by ID, with optional query parameters for size and format.
**Endpoint**: `GET /api/v1/images/{id}`
**Query Parameters**:
- size (optional): Specify the size of the image (thumbnail, medium, large).
- format (optional): Specify the format of the image (jpeg, png, webp).

**Response (Success)**:
```
HTTP/1.1 200 OK
Content-Type: image/jpeg

<binary data of the image>
```

**Response (Error)**:
```json
{
  "message": "Failed to retrieve image.",
  "statusCode": 500
}
```

**Comment by markessien** [comment]
This feature should be discussed with me before implementation. It is not well spec'd out, and this should be revised

**Comment by highb33kay** [comment]
Need more details about how this interacts at application level?

Are images not going to be fetched with the specific endpoints like User profile?

@thenoblet

**Comment by thenoblet** [comment]
> Need more details about how this interacts at application level?
> 
> Are images not going to be fetched with the specific endpoints like User profile?
> 
> @thenoblet

@highb33kay, Mark suggested this endpoint be created. So I thought images would be stored on the server or a CDN, then served using efficient techniques like caching (which a friend raised a separate issue for #252 after discussing with him) and compression.

For caching, if images are stored on the server, appropriate cache headers must be set to allow browsers and CDNs to cache them.
If images are stored in an S3 bucket, with CloudFront, they can be cached based on their unique slugs reducing the load on the origin server(s).
