### ISSUE TITLE
[FEAT] : API Endpoint for Retrieving All Subscription Plan Features

### ISSUE THREAD

**Issue by Sidney2022** [hngprojects/hng_boilerplate_nestjs#250]
## Description
Create endpoints to allow for the retrieval of every subscription/billing plan feature This will help users get to know the different perks(features) attached to any particular plan, helping them make better choices when choosing a subscription plan.

## Acceptance Criteria
 Retrieve a list of all available billing plans features
Get a single plan feature detail

### Requirements	
The user must provide a valid feature_id to access a single feature object

### Endpoints
Get All Billing Plan Features ` [GET] /api/v1/plan-features`
Get A Single  Billing Plan Feature ` [GET] /api/v1/plan-features/{feature_id}`

### Example Requests and Responses
Request: Get All Plan Features
```
GET /api/v1/plan-features

Content-Type: application/json
```

Success Response: Get All Features for Subscription Plans
```
HTTP/1.1 200 OK
Content-Type: application/json


{
  "status": 200,
  "features": [
    {
      "id": 1,
      "feature": "first feature",
      "description": "a little text",
    },
    {
      "id": 2,
      "feature": "second feature",
      "description": "short desciption"
    }
  ]
}
```

Request: Get Billing Plan  Feature Details
```
 [GET] /api/v1/plan-features/{feature_id}
Content-Type: application/json
```
Success Response: Get Billing Plan  Feature Details
```
HTTP/1.1 200 OK
Content-Type: application/json

{
  "status": 200,
  "feature": {
    "id": 1,
    "feature": "you get some feature",
    "deacription": "a short description",
  }
}
```

Invalid Feature_id Errror Response: Get Billing Plan Feature Details
```
HTTP/1.1 404 Not Found
Content-Type: application/json

{
  "status": 404,
  "message":"invalid feature_id"
}
```

Server Error response:
```
{
    "status": 500
    "message": "an error occurred",
    
}
```
### Tasks

- [ ]  Create an endpoint (`HTTP GET /api/v1/plan-features`) to get all subscription plan features.
- [ ]  Create an endpoint (`HTTP GET /api/v1/plan-features/{feature_id`) to get a single plan feature.

**Comment by markessien** [comment]
Not a ticket so far I can tell. Plan read is not a super admin feature

**Comment by Sidney2022** [comment]
I've removed the authentication requirements. pls confirm

**Comment by highb33kay** [comment]
@Sidney2022 Please break this down into two endpoints/tickets. 

And share the second ticket here

**Comment by highb33kay** [comment]
Why do we need an end point for features of a plan? @Sidney2022 ?

**Comment by Sidney2022** [comment]
so the SubscriptionPlan Table would be something like
SubscriptionPlan:
id int
name str
price int
description str
features (this would be a many-to-many field to the features table that would contain the benefits(feaures) attached to each plan)

or is there another way to do it? at least that is how I thought about it. @highb33kay

**Comment by highb33kay** [comment]
How about a JSON field in the DB for features?

**Comment by highb33kay** [comment]
I dont think we are expecting up to 20 features/plan? are we?

**Comment by highb33kay** [comment]
@Sidney2022

**Comment by Sidney2022** [comment]
no. probably not

**Comment by highb33kay** [comment]
Can you fix it then? The documentation and also have it fixed on the Schema?

**Comment by Sidney2022** [comment]
The person doing the SubscriptionPlan already has the schema for it. #55 . should I stil add it here? Also, I just  have to seperate the tickets right?

**Comment by highb33kay** [comment]
Since features will now be stored on the subscription table, there is no need for an additional ticket. 

Please link the create subscription here let's find the person working on it and have the schema changed

**Comment by Sidney2022** [comment]
ok.  @davidolanrewaju  is the person working on it. issue #55
that means I'll have to close this then
