### ISSUE TITLE
[FEAT]: Database Setup

### ISSUE THREAD

**Issue by nadduli** [hngprojects/hng_boilerplate_nestjs#251]
### Description
Set up a database for the chosen framework’s ORM, allowing configuration for any database but defaulting to Postgres. Follow migrations, models, and service patterns to ensure a robust and flexible database setup.

#### Acceptance Criteria

1. **Database Configuration**:
    - Set up the database for the chosen framework’s ORM.
    - The setup should allow configuration for any database, with Postgres as the default.
    - Follow migrations, models, and service patterns.

2. **Validation**:
    - Create the following tables and constraints:
        - **Users**: A user has one profile.
        - **Profiles**: A user has one profile.
        - **Organisations**: A user belongs to many organisations. An organisation has many users.
        - **Products**: A user has many products.
    - Seed the tables with the following data:
        - At least 2 users.
        - At least 2 products per user.
        - At least 3 organisations.
        - User one belongs to 2 of the organisations.
        - User two belongs to all 3 organisations.

#### Example Data

1. **Tables and Constraints**:
    - Users table
    - Profiles table
    - Organisations table
    - Products table
    - Relationships:
        - A user has one profile.
        - A user has many products.
        - A user belongs to many organisations.
        - An organisation has many users.

2. **Table Seeding**:
    - Users: At least 2 users.
    - Products: At least 2 products per user.
    - Organisations: At least 3 organisations.
    - User one belongs to 2 of the organisations.
    - User two belongs to all 3 organisations.

#### Example Endpoints

- **[GET] api/v1/users/user_one_id**
    - Sample Response:
    ```json
    {
      "name": "John Doe",
      "id": "some-user-id",
      "email": "johndoe@example.com",
      "profile": {
        "first_name": "John",
        "last_name": "Doe",
        "phone": "1234567890",
        "avatar_url": "http://example.com/avatar.jpg"
      },
      "organisations": [
        {
          "org_id": "some-org-id-1",
          "name": "Some Org",
          "description": "Some Org Description"
        },
        {
          "org_id": "some-other-org-id-2",
          "name": "Some Other Org",
          "description": "Some Other Org Description"
        }
      ],
      "products": [
        {
          "product_id": "some-product-id",
          "name": "Some Product",
          "description": "Some Product Description"
        },
        {
          "product_id": "some-other-product-id",
          "name": "Some Other Product",
          "description": "Some Other Product Description"
        }
      ]
    }
    ```

- **[GET] api/v1/users/user_two_id**
    - Sample Response:
    ```json
    {
      "name": "John Doe",
      "id": "some-user-id",
      "email": "johndoe@example.com",
      "profile": {
        "first_name": "John",
        "last_name": "Doe",
        "phone": "1234567890",
        "avatar_url": "http://example.com/avatar.jpg"
      },
      "organisations": [
        {
          "org_id": "some-org-id-1",
          "name": "Some Org",
          "description": "Some Org Description"
        },
        {
          "org_id": "some-other-org-id-2",
          "name": "Some Other Org",
          "description": "Some Other Org Description"
        },
        {
          "org_id": "some-other-org-id-3",
          "name": "Some Other Org",
          "description": "Some Other Org Description"
        }
      ],
      "products": [
        {
          "product_id": "some-product-id",
          "name": "Some Product",
          "description": "Some Product Description"
        },
        {
          "product_id": "some-other-product-id",
          "name": "Some Other Product",
          "description": "Some Other Product Description"
        }
      ]
    }
    ```

#### Implementation

1. Clone the boilerplate for your framework.
2. Create a branch named `chore/database-setup` from the base branch.
3. Implement the database setup as described above.

### Expected Outcome
- The database is set up with the required tables and relationships.
- The tables are seeded with the provided sample data.
- The specified endpoints return the expected responses.

#### Testing
- Validate the database setup by ensuring the tables and relationships are correctly created.
- Verify the data seeding by querying the database.
- Test the endpoints to ensure they return the correct data.

#### Notes
- Ensure compliance with security standards for data handling.
- Write unit tests and integration tests to validate the database setup and endpoints.

**Comment by markessien** [comment]
DB setup tasks will not be accepted as tickets
