### ISSUE TITLE
[FEAT]: Implement Image Caching

### ISSUE THREAD

**Issue by nadduli** [hngprojects/hng_boilerplate_nestjs#252]
### Description
Implement an image caching system with authentication, utilizing slugs for image access.

#### Acceptance Criteria
- [ ] **Endpoint**: The endpoint should be accessible at `/api/v1/images/:slug`.
- [ ] **HTTP Method**: The endpoint should accept HTTP GET requests.
- [ ] **Authentication**:
  - The endpoint should be secured to ensure that only authenticated users can access the cached images.
  - Proper authentication mechanisms should be implemented.
  - Requests to the endpoint must include a valid authentication token in the Authorization header.
  - Example:
    ```http
    Authorization: Bearer <token>
    ```
- **Request Parameters**:
  - The request URL should include a slug representing the image.
  - Example:
    ```
    /api/v1/images/sample-image-slug
    ```
- **Caching**:
  - Implement a caching mechanism to store and retrieve images efficiently.
  - Cache should be invalidated when an image is updated or deleted.
- **Response**:
  - **Success (200 OK)**:
    - The response should include the cached image.
    - Example:
      ```http
      Content-Type: image/jpeg
      <binary image data>
      ```
  - **Error**:
    - **400 Bad Request**: If the slug is invalid, the response should include:
      ```json
      {
        "status_code": 400,
        "message": "Invalid slug provided",
        "error": "Bad Request"
      }
      ```
    - **401 Unauthorized**: If the request does not include a valid authentication token, the response should include:
      ```json
      {
        "status_code": 401,
        "message": "Authentication required",
        "error": "Unauthorized"
      }
      ```
    - **404 Not Found**: If the image is not found in the cache or database, the response should include:
      ```json
      {
        "status_code": 404,
        "message": "Image not found",
        "error": "Not Found"
      }
      ```
    - **500 Internal Server Error**: If an unexpected error occurs on the server side, the response should include:
      ```json
      {
        "status_code": 500,
        "error": "Internal Server Error",
        "message": "An unexpected error occurred. Please try again later."
      }
      ```

#### Purpose
Provides a backend service to cache images, ensuring efficient retrieval and access control through authentication. Utilizing slugs enhances the readability and usability of the URLs.

#### Requirements
- Develop server-side logic to handle image caching and retrieval.
- Validate and sanitize incoming slugs.
- Implement authentication mechanisms to secure the endpoint.
- Ensure compliance with security standards for handling image data.
- Cache images and handle cache invalidation appropriately.

#### Expected Outcome
- The API endpoint allows authenticated users to access cached images using slugs.
- The response includes the cached image data, ensuring efficient retrieval and proper validation.

#### Testing
- Write unit tests for backend validation and caching logic.
- Write integration tests for the end-to-end image retrieval process.
- Test various scenarios, including invalid slugs, missing authentication, and successful image retrieval.
- Test authentication to ensure only authenticated users can access the endpoint.

#### Example Request
```http
GET /api/v1/images/sample-image-slug
Authorization: Bearer <token>
```
#### Example Response
* Success (200 OK):
```json
Content-Type: image/jpeg
<binary image data>
```
* Error (400 Bad Request):
```json
{
  "status_code": 400,
  "message": "Invalid slug provided",
  "error": "Bad Request"
}
```
* Error (401 Unauthorized):
```json
{
  "status_code": 401,
  "message": "Authentication required",
  "error": "Unauthorized"
}
```
* Error (404 Not Found):
```json
{
  "status_code": 404,
  "message": "Image not found",
  "error": "Not Found"
}
```
* Error (500 Internal Server Error):
```json
{
  "status_code": 500,
  "error": "Internal Server Error",
  "message": "An unexpected error occurred. Please try again later."
}
```

**Comment by thenoblet** [comment]
This looks good @nadduli

**Comment by markessien** [comment]
this does not describe how the cache would work, in particular how it would integrate with nginx to serve cached images
