### ISSUE TITLE
[FEAT]  Implement API Endpoint for Sending Email Requests

### ISSUE THREAD

**Issue by PcNerd9** [hngprojects/hng_boilerplate_nestjs#253]
### Description
Develop an endpoint to handle requests for sending emails using pre-defined templates. The emails should be placed in a database queue for sending to ensure the application remains responsive. The endpoint should handle variable substitution, replacing placeholders in the templates with actual data.

### Acceptance Criteria
- The endpoint should receive requests to send emails using specific templates.
- The endpoint should handle variable substitution to replace placeholders with actual data.
- The email sending request should be stored in a database queue.
- The endpoint should return appropriate status codes and responses based on the outcome of the request.
- Endpoints should be correctly versioned.

### Data Validation
- **Input Validation:** Validate that `template_id`, `recipient`, and `variables` fields are provided and correctly formatted.
- **Output Validation:** Ensure the response contains the correct status and message.

### Authentication and Authorization
- **Authentication:** Ensure the endpoint requires valid user authentication.
-  **Authorization:** Verify that the user has permission to send emails using the specified template.
### Error Handling
- **Error Responses:** Define error responses for scenarios such as missing template, invalid input, and internal server errors.
- **Edge Cases:** Consider edge cases such as template not found, invalid email format, and missing variables.

### Performance and Security
- **Performance Considerations:** Ensure the email request queuing system is efficient and does not degrade application performance.
- **Security Concerns:** Address security considerations such as data sanitization, input validation, and protection against injection attacks.

### Documentation
- **API Documentation:** Provide comprehensive API documentation for the endpoint, including request and response formats.
- **Technical Notes:** Include any additional technical notes or considerations for implementing the endpoint.

### Testing Requirements
-  **Unit Tests:** Implement unit tests to verify the functionality of the endpoint.
- **Integration Tests:** Develop integration tests to ensure the endpoint works correctly with other system components.

### Dependencies and Impact
- **Dependencies:** Identify any dependencies on other tasks or systems, such as the database queue implementation.
- **Impact Analysis:** Assess the potential impact on other features or components of the application.

### Requirements
- Implement an API endpoint for sending emails using templates.
- Handle variable substitution for placeholders in the email templates.
- Store email sending requests in a database queue.
- Handle unexpected errors and return the appropriate status codes.
- Ensure endpoints are correctly versioned.

### Expected Outcome
- Users should be able to send requests to the backend to enqueue emails using templates.
- Users should receive appropriate status codes and responses based on the outcome of the requests.
- Emails should be queued for sending without blocking the main application flow.

### Endpoints
**[POST] /api/v1/send-email**

- **Description**: Enqueues an email request using a specified template.
- **Request Body**:
  ```json
  {
    "template_id": 1,
    "recipient": "john.doe@example.com",
    "variables": {
      "name": "John Doe",
      "product": "Wireless Headphones",
      "order_number": 12345
    }
  }
**Success Response:**
*Status Code: `202 Accepted`*
*Body:*
```json
{
  "message": "Email sending request accepted and is being processed in the background."
}
```
**Error Responses:**
*Status Code: `500 Internal Server Error`*
*Body:*
```json
{
  "error": "Internal server error."
}
```

*status Code: `404 Not Found`*
*Body:*

```json
{
  "error": "Template not found."
}
```

*Status Code: `405 Method Not Allowed`*
*Body:*
```json
{
  "error": "This method is not allowed."
}
```

*Status Code: `400 Bad Request`*
*Body:*
```json
{
  "error": "An invalid request was sent."
}
```
#### Test Scenarios

1. **Successful Email Sending Request**
   - Ensure that the endpoint accepts a request to send an email using a template.
   - Verify that the response indicates the request is being processed in the background.
   - Confirm that the status code is `202 Accepted`.

2. **Template Not Found**
   - Simulate a scenario where the specified email template ID does not exist.
   - Confirm that the response body contains an appropriate error message.
   - Confirm that the status code is `404 Not Found`.

3. **Internal Server Error**
   - Simulate an internal server error to raise an exception.
   - Verify that the endpoint returns a `500 Internal Server Error` status code.
   - Confirm that the response body contains an appropriate error message.

4. **Invalid Method**
   - Send a request using an invalid HTTP method (e.g., GET) to the endpoint.
   - Verify that the endpoint returns a `405 Method Not Allowed` status code.
   - Confirm that the response body contains an appropriate error message.

5. **Bad Request**
   - Send a request with invalid data (e.g., missing required fields) to the endpoint.
   - Verify that the endpoint returns a `400 Bad Request` status code.
   - Confirm that the response body contains an appropriate error message.

##LINKS
 link to the issue that implement the sending of the email in the background using `Celery` and `RabbitMq` https://github.com/hngprojects/hng_boilerplate_nestjs/issues/254#issue-2418183784

**Comment by markessien** [comment]
Appears VERY duplicated

**Comment by PcNerd9** [comment]
you commented on the previous issue created for this feature that the issue should be divided into two:
1. The email is placed in a db queue for sending
2. The email is retrieved from queue and dispatched. 
So that's issue was closed and i created two new issues to fit this requirements. One of the issues is this issue.
I had gone through all the issues that's been created and accepted before creating this issue to avoid duplicate. In short, this issue is not a duplicate sir

**Comment by highb33kay** [comment]
Can you link both issues and I will review asap

**Comment by PcNerd9** [comment]
https://github.com/hngprojects/hng_boilerplate_nestjs/issues/254#issue-2418183784

link to the issue that implement the sending of the email in the background using `Celery` and `RabbitMq`

**Comment by highb33kay** [comment]
I have seen both. Can you explain the difference because I dont see it? @PcNerd9

**Comment by PcNerd9** [comment]
### The  simple explanation of the first issue:
- It retrieve the email template from the db
- Parse the email template by doing variable substitution
- Save the email request in the db queue

### Simple explanation of the second issue:
- Write Celery Code that  actually sends the email using a particular email service
- Celery fetches the request from the db queue using rabbitMQ
- Celery process the request in the background
