### ISSUE TITLE
[FEAT]: Implement Cross-Platform Compatible Logging System with PII Obfuscation

### ISSUE THREAD

**Issue by chukssomzzy** [hngprojects/hng_boilerplate_nestjs#258]
## Description
Design and implement a centralized, asynchronous logging system that can be easily adapted for multiple programming languages and frameworks including but not limited to FastAPI (Python), NestJS (TypeScript), Spring Boot (Java), ASP.NET Core (C#), and Laravel (PHP). The system should capture user activities, API requests/responses, database queries, and system events, with a focus on PII (Personally Identifiable Information) detection and obfuscation.

### Purpose
- To provide a standardized logging architecture that can be implemented across various technology stacks, ensuring consistent logging practices throughout different boilerplate applications.
- To ensure user privacy and regulatory compliance (GDPR, CCPA) through automatic PII detection and obfuscation in logs, regardless of the underlying technology.

### Requirements
1. Design a language-agnostic logging architecture:
   - Define a common log structure (JSON-based) that all implementations must adhere to.
   - Specify a standard set of log levels (DEBUG, INFO, WARNING, ERROR, CRITICAL) with clear usage guidelines.
   - Create a platform-independent PII detection and obfuscation algorithm, implementable in multiple languages.

2. Implement the logging system for the following platforms (minimum):
   - Python (FastAPI)
   - TypeScript (NestJS)
   - Java (Spring Boot)
   - C# (ASP.NET Core)
   - PHP (Laravel)

3. For each implementation, include:
   - Asynchronous logging capabilities appropriate to the language/framework.
   - Integration with the platform's native HTTP request/response cycle.
   - Database query logging adapted to common ORMs for each platform.
   - File rotation and compression logic, standardized across implementations.

4. Develop a common PII detection and obfuscation module:
   - Create a set of regex patterns for common PII (e.g., email addresses, phone numbers, SSNs, credit card numbers) that can be easily translated to different regex engines.
   - Implement a language-agnostic algorithm for detecting and obfuscating names and addresses.
   - Ensure consistent obfuscation output across all implementations.

5. Standardized log storage:
   - Define a common log file naming convention and directory structure.
   - Implement a 30-day retention policy consistently across all platforms.

6. Create a configuration mechanism to dynamically adjust log levels at runtime, adaptable to each platform's configuration management system.

7. Implement comprehensive request/response logging:
   - Log all incoming HTTP requests with headers (excluding Authorization header) and body.
   - Log all outgoing HTTP responses with status codes and body (truncate bodies longer than 1000 characters).
   - Ensure consistency in logged information across all platforms.

8. Standardize authentication and authorization logging:
   - Define a common format for logging authentication attempts and authorization failures.
   - Ensure consistent obfuscation of sensitive data (like usernames) across platforms.

9. Error logging:
   - Develop a common error logging format that includes a unique error ID and basic error information.
   - Implement platform-specific logic to capture stack traces in development environments.

10. Develop a set of common log enrichment fields to be included in all log entries across platforms:
    - Request ID (UUID generated for each request)
    - User ID (if authenticated)
    - API version
    - Environment name (e.g., production, staging, development)

11. Performance considerations:
    - Implement a maximum log message size of 5KB across all platforms.
    - Develop platform-specific bounded queue implementations for async logging to prevent unbounded memory growth.

### Expected Outcome
1. A comprehensive logging system design document detailing the architecture, data formats, and implementation guidelines for each supported platform.
2. Fully functional reference implementations for each specified platform (Python, TypeScript, Java, C#, PHP).
3. Consistent log output and PII obfuscation across all implementations, verified through automated cross-platform log analysis.
4. Performance overhead of less than 5ms added latency per request for each implementation.
5. A suite of cross-platform tests to verify consistency and functionality across implementations.
6. Documentation for each platform implementation, including setup guides and best practices.

**Comment by markessien** [comment]
Out of scope
