### ISSUE TITLE
[FEAT]Implement API Endpoint to store session or user cookie preference

### ISSUE THREAD

**Issue by max-out-oluwadara** [hngprojects/hng_boilerplate_nestjs#260]
## Description
- Develop an endpoint that allows authenticated users to store their preferences, such as theme, notification settings, and language. These preferences will be used to personalize the user experience across the application.

## Purpose
- The purpose of this endpoint is to enable authenticated users to store and manage their personal preferences, such as theme, notification settings, and language. By saving these preferences, the application can deliver a customized and enhanced user experience tailored to each individual's choices

## Scope

- The endpoint will accept a JSON payload containing the user preferences and store them in the database. It will validate the input, ensure the user is authenticated, and handle any potential errors gracefully.

### Completeness 
- [ ] It must validate the input data.
- [ ] It must save the preferences to the database.
- [ ] It must respond with a success message upon successful storage.
- [ ] It must handle and respond with appropriate error messages for invalid input or server errors.

### Measurable
- [ ] The endpoint should return a 200 status code for successful requests.
```
{
  "statusCode": 200,
  "message": "Preferences saved successfully."
}
```

- [ ] It should return a 400 status code for invalid input data.
```
{
  "statusCode": 400,
  "message": [
    "Theme must be either 'light' or 'dark'.",
    "Notifications must be a boolean value.",
    "Language must be a valid language code ('en' or 'fr')."
  ],
  "error": "Bad Request"
}
```

- [ ] It should return a 500 status code for server errors.
```
{
  "statusCode": 500,
  "message": "Internal Server Error"
}

```

### Data Validation
**Input Validation**:
- [ ] Ensure `theme` is either "light" or "dark".
- [ ] Ensure `notifications` is a boolean.
- [ ] Ensure `language` is a valid language code (e.g., "en", "fr").

**Output Validation**:
- [ ] The response should confirm that preferences were saved, including a status message and possibly the saved preferences.

### Authentication and Authorization
**Authentication**:
- [ ] Only authenticated users can access this endpoint.
- [ ] Verify the user’s identity via a token or session.

**Authorization**:
- [ ] Ensure the user has the appropriate role or permissions to update their preferences.

### Error Handling
**Error Responses**:
- [ ] Return a 400 status code with a message for invalid input data.
```
{
  "statusCode": 400,
  "message": [
    "Theme must be either 'light' or 'dark'.",
    "Notifications must be a boolean value.",
    "Language must be a valid language code ('en' or 'fr')."
  ],
  "error": "Bad Request"
}
```

- [ ] Return a 401 status code for unauthorized access.
```
{
  "statusCode": 401,
  "message": "Unauthorized"
}
```

- [ ] Return a 500 status code for internal server errors.
```
{
  "statusCode": 500,
  "message": "Internal Server Error"
}
```

**Edge Cases**:
- [ ] Handle cases where the database is down.
```
{
  "statusCode": 500,
  "message": "Database connection error"
}
```

- [ ] Handle cases where required fields are missing from the input.
```
{
  "statusCode": 400,
  "message": [
    "Theme is required.",
    "Notifications is required.",
    "Language is required."
  ],
  "error": "Bad Request"
}
```

### Performance and Security
**Performance Considerations**:
- [ ] Optimize database queries for saving preferences.
- [ ] Ensure the endpoint can handle concurrent requests efficiently.

**Security Concerns**:
- [ ] Sanitize all inputs to prevent SQL injection.
- [ ] Implement rate limiting to prevent abuse.
- [ ] Ensure secure communication over HTTPS.

### Documentation
**API Documentation**:
[URL] POST:  /auth/cookie-preferences

**Header**
```
{
  "Authorization": "Bearer <token>",
  "Content-Type": "application/json"
}
```

**Request Body**
```
{
  "theme": "light or dark",
  "notifications": true,
  "language": "en or fr"
}
```

**Technical Notes**:
- [ ] Database Schema: The Preferences model defines the structure for storing user preferences.
- [ ] Authentication: JWT strategy for authentication.
- [ ] Integration Test: Updated to include cases for handling missing required fields, unauthorized access, and database connection errors.

### Testing Requirements
**Unit Tests**:
- [ ] Mocks the service and authentication guard.
- [ ] Tests that the controller is defined.
- [ ] Tests the happy path for saving preferences.
- [ ] Tests input validation by attempting to pass invalid data.

**Integration Tests**:
- [ ] Mocks the service and authentication guard: The PreferencesService is mocked with the setPreferences method, and the AuthGuard is overridden to always allow access.
- [ ] Tests that the controller is defined: The first test checks that the application is defined.
- [ ] Tests the happy path for saving preferences: The second test sends a valid request to save preferences and checks for a successful response.
- [ ] Tests input validation by attempting to pass invalid data: The third test sends an invalid request and checks for validation error messages in the response.

### Dependencies and Impact
**Dependencies**:
- [ ] Requires a user authentication system to verify user identity.
- [ ] Depends on the database for storing preferences.

**Impact Analysis**:
- [ ] Assess potential impact on the user authentication system.
- [ ] Ensure the preferences data model does not conflict with existing database schemas.

**Comment by max-out-oluwadara** [comment]
Team DataFlow
SlackID
@is_oluwadara nest_js
@Bami -Fast api

Mentors pls help review 
@AviOfLagos 
@prondubuisi

**Comment by markessien** [comment]
Duplicate
