### ISSUE TITLE
 [FEAT]: Integration Search Functionality

### ISSUE THREAD

**Issue by ChibuikemMichaelIlonze** [hngprojects/hng_boilerplate_nestjs#262]
### Description
Implement a search functionality for the integration settings page. This feature will allow users to search for specific integrations by name, making it easier to find and manage them.

### Acceptance Criteria
- A search input field is added to the top of the integration settings page.
- Users can type keywords into the search field to filter integration options.
- The integration list dynamically updates to show only the items that match the search query.
- If no matching integrations are found, a message is displayed indicating no results.
- The search functionality is responsive and works across all devices.

### Requirements
- Add a search input field at the top of the integration settings page.
- Implement the search functionality to filter the integration options based on user input.
- Ensure the integration list updates in real-time as the user types.
- Style the search input field and results to match the website’s design guidelines.
- Handle unexpected errors and display appropriate messages to the user.

### Expected Outcome
- Users should be able to type keywords into the search field and see a filtered list of integration options that match their query.
- Users should receive a message if no integrations match their search query.

### Form Structure
- **Field**:
  - `search` (string): The user's search query (optional).

### Success Response:
- **Status**: 200 OK
- **Body**:
  ```json
  {
    "message": "Integration search results",
    "status_code": 200,
    "data": [
      {
        "name": "String",
        "enabled": "Boolean"
      }
    ]
  }
  ```

### No Results Response:
- **Status**: 200 OK
- **Body**:
  ```json
  {
    "message": "No integrations match your search",
    "status_code": 200,
    "data": []
  }
  ```

### Error Response:
- **Status**: 500 Internal Server Error
- **Body**:
  ```json
  {
    "message": "An error occurred while processing your request",
    "status_code": 500
  }
  ```

### Testing
**Test Scenarios**
1. **Successful Search**
  - Ensure that the search input field filters integration options based on user input.
  - Confirm that the status code is 200.
  - Verify that the response body contains the filtered integration options.

2. **No Results Found**
  - Enter a search query that does not match any integration options.
  - Verify that the endpoint returns a 200 OK status code with a message indicating no results.

3. **Unexpected Error Handling**
  - Simulate an unexpected error during the search process.
  - Verify that the endpoint returns a 500 Internal Server Error status code.
  - Confirm that the response body contains an appropriate error message.

**Comment by markessien** [comment]
out of scope
