### ISSUE TITLE
[FEAT]: Implement Fuzzy Search Endpoint  for User Lookup

### ISSUE THREAD

**Issue by chukssomzzy** [hngprojects/hng_boilerplate_nestjs#264]
## Description
Develop an API endpoint that implements fuzzy search functionality to find users within an organization based on various user information fields such as name, ID, email, and full name. This endpoint will enhance user discovery and management within the Slack-like organizational structure of our application.

### API Endpoint Implementation
- The endpoint should be accessible at `/api/v1/organisations/{org_id}/users/search`.
- The endpoint should accept HTTP GET requests.
- The endpoint must be accessible only to authenticated users within the specified organization.

### Request Parameters
- `query` (required): The search string to match against user fields.
- `fields` (optional): Comma-separated list of fields to search (default: name,id,email,fullname).
- `limit` (optional): Maximum number of results to return (default: 10, max: 50).

### Response
- On success, the API should return a 200 OK status code with a success message and search results.
- On failure, the API should return an appropriate error code (400, 401, 403, or 500) with an error message.

### Request Example
```
GET /api/v1/organisations/org123/users/search?query=john&fields=name,email&limit=5
```

### Success Response
```json
{
    "status_code": 200,
    "message": "Search completed successfully",
    "data": [
        {
            "id": "user123",
            "name": "John Doe",
            "email": "john.doe@example.com",
            "fullname": "John Michael Doe",
            "match_score": 0.95
        },
        {
            "id": "user456",
            "name": "Johnny Smith",
            "email": "johnny.smith@example.com",
            "fullname": "Jonathan Smith",
            "match_score": 0.82
        }
    ]
}
```

### Failure Response
```json
{
    "status_code": 400,
    "error": "Invalid request",
    "message": "Invalid search parameters provided"
}
```

## Purpose
Implement an API endpoint to perform fuzzy searches on user data within an organization, allowing for efficient user discovery and management in our Slack-like application structure.

## Requirements
1. Implement authentication logic to ensure the client is signed in.
2. Implement authorization logic to verify the client belongs to the specified organization.
3. Develop a fuzzy search algorithm that can match partial and misspelled inputs.
4. Apply the search across specified user fields (name, ID, email, full name).
5. Implement proper indexing on the user collection to optimize search performance.
6. Return results sorted by relevance (match score).
7. Ensure the endpoint adheres to RESTful principles.

## Expected Outcome
The API endpoint performs a fuzzy search on user data and returns matching results, enhancing user discovery within the organization.

## Status Codes
- 200: Successfully retrieved search results
- 400: Invalid request parameters
- 401: User not authenticated
- 403: User not authorized to access the organization
- 500: A server error occurred

## Testing
1. Ensure the endpoint correctly authenticates the client.
2. Confirm the endpoint verifies that the client belongs to the specified organization.
3. Test the endpoint with various search queries, including partial matches and misspellings.
4. Verify the search works across all specified fields (name, ID, email, full name).
5. Check that the results are properly sorted by relevance.
6. Test the limit parameter to ensure it correctly restricts the number of results.
7. Perform load testing to ensure the endpoint can handle multiple concurrent requests.

**Comment by markessien** [comment]
too specific
