### ISSUE TITLE
[FEAT] Implement Endpoint to RETRIEVE About Page Content: settable from admin

### ISSUE THREAD

**Issue by thenoblet** [hngprojects/hng_boilerplate_nestjs#265]
## Description
Implement an endpoint to retrieve the content of the About page, allowing administrators to view the current information efficiently.

---

## Purpose
- Enable administrators to retrieve the current content of the About page.

---

### Retrieve About Page Content
- Retrieve the current content of the About page.
- Ensure resource is accessible to authorised and authenticated admins only.
- Return a structured response with the current content and last update timestamp.
- Handle scenarios where retrieval fails appropriately.

---

### Retrieve About Page Content
- Implement **GET /api/v1/content/about** endpoint to retrieve About page content.
- Ensure authentication and authorization mechanisms for administrators.
- Handle and return errors gracefully, specifying different error conditions.

---

## Expected Outcome
- Implementation of the endpoint to retrieve About page content.
- Clear and appropriate responses for success and error cases.
- Documentation and testing to ensure reliability and functionality.

---

## Checklist
1. #### Retrieve About Page Content
- [ ] Implement **GET /api/v1/content/about** endpoint.
- [ ] Secure endpoint with authentication for administrators.
- [ ] Document endpoint, including request and response formats.

### Testing 
- [ ] Write unit and integration tests covering various scenarios.
- [ ] Test successful retrieval operations.
- [ ] Test edge cases and error scenarios thoroughly.

### Documentation:
- [ ] Document the endpoint, including request and response formats.
- [ ] Include information on authentication requirements and error handling.

---

### Retrieve About Page Content
**Description**: Retrieve the current content of the About page.  
**Endpoint**: **`GET /api/v1/content/about`**  
**Authentication**: Required  
**Authorization**: Administrators only  
**Response (Success)**:
```json
{
    "title": "More Than Just A BoilerPlate",
    "introduction": "Welcome to Hng Boilerplate, where passion meets innovation.",
    "custom_sections": {
      "stats": {
        "years_in_business": 10,
        "customers": 75000,
        "monthly_blog_readers": 100000,
        "social_followers": 1200000
      },
      "services": {
        "title": "Trained to Give You The Best",
        "description": "Since our founding, Hng Boilerplate has been dedicated to constantly evolving to stay ahead of the curve."
      }
    },
  "status_code": 200,
  "message": "Retrieved About Page content successfully"
}
```

**Response (Error: Server Issue)**:
```json
{
  "message": "Failed to retrieve About page content.",
  "status_code": 500
}
```

**Response (Error: Unauthenticated)**:
```json
{
  "message": "Invalid authentication credentials",
  "status_code": 401
}
```

**Response (Error: Authenticated but Unauthorised)**:
```json
{
  "message": "You do not have the necessary permissions to access this resource",
  "status_code": 403
}
```

---

## Additional Notes:
- This endpoint is designed to complement the UPDATE operation described in the issue [[FEAT] Implement Endpoint to UPDATE About Page Content: settable from admin](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/235). 
- Ensuring consistency with the UPDATE operation in issue #235 is crucial. Review the request and response formats, validation rules, and authentication/authorization mechanisms outlined in that issue.
- Consistent error handling is important for a seamless user experience. Align the error messages and status codes with those defined in issue #235 .
- Documentation and testing should cover both endpoints thoroughly. Refer to the documentation and test cases of the UPDATE operation to ensure all scenarios are addressed.
- Authentication and authorization are mandatory for this endpoint to restrict access to administrators only. Follow the same security protocols as described in issue #235
- Keep the custom sections flexible and extendable. Future modifications should allow easy addition of new sections without major changes to the structure.

**Comment by highb33kay** [comment]
Please update this to follow the convention

{
    "title": "More Than Just A BoilerPlate",
    "introduction": "Welcome to Hng Boilerplate, where passion meets innovation.",
    "custom_sections": {
      "stats": {
        "years_in_business": 10,
        "customers": 75000,
        "monthly_blog_readers": 100000,
        "social_followers": 1200000
      },
      "services": {
        "title": "Trained to Give You The Best",
        "description": "Since our founding, Hng Boilerplate has been dedicated to constantly evolving to stay ahead of the curve."
      }
    },
  "status_code": 200
}****

Retiurn Response should be 

data:
status_code
message

**Comment by Popsicool** [comment]
Update this, show the error response when an unauthenticated user or authenticated but unauthorized (non administrator) users use this endpoint.
Also update the response using the convention stated above by @highb33kay

**Comment by markessien** [comment]
it would be better to use a generic content endpoint - e.g /content/about, where about is a category. I think all these types of pages should be consolidated into a single such endpoint group

**Comment by thenoblet** [comment]
@highb33kay, @Popsicool and @markessien, all suggestions and changes has been made, Mentors.

Please review again. Hopefully, it is exactly what you expect.
