### ISSUE TITLE
[FEAT]Databsae setup - Migration, Seeding and Model

### ISSUE THREAD

**Issue by posh1001** [hngprojects/hng_boilerplate_nestjs#268]
## Description
Establish a secure and flexible database schema using Object-Relational Mapping (ORM) with PostgreSQL as the primary database backend, while ensuring the architecture supports easy migration to other database types. The focus will be on creating tables for users, profiles, and organizations, following best practices for Nest.js projects.

### Database Configuration:
- ***Support for Multiple Databases***: Implement a configuration mechanism that allows switching between different databases (e.g., PostgreSQL, MySQL, SQLite) based on configuration settings.
- ***Default to PostgreSQL***: Ensure PostgreSQL is set as the default database if no other configuration is provided.

### ORM Integration:

- ***Selecting the ORM***: Choose and configure the ORM provided by the framework (e.g., SQLAlchemy for Python, - Hibernate for Java) that supports the chosen database configurations.
- ***ORM Configuration***: Set up ORM connections and mappings to handle database interactions seamlessly.

### Migrations Setup:

- ***Migration Tool Selection***: Select a migration tool compatible with the chosen ORM (e.g., Alembic for SQLAlchemy) to manage database schema changes.
- ***Initial Migration***: Create an initial migration script to set up the basic database schema including necessary tables, indexes, and relationships.

#### Install Required Packages
Make sure you have `class-validator` and c`lass-transformer` installed in your NestJS project. If not, you can install them using npm or yarn:

#### Create an Entity Class
Create your entity class where you want to apply validation. For example, let's create a simple User entity:

#### Apply Validation Pipes
In NestJS, you use pipes to handle validation. There's a built-in `ValidationPipe` that integrates with `class-validator` to automatically validate incoming request payloads.

#### Validate DTOs (Data Transfer Objects)
It's a good practice in NestJS to use DTOs for data validation and transformation between clients and your application. Here’s an example of a DTO with validation:

#### Handle Validation Errors
When validation fails, NestJS automatically throws a `BadRequestException` with details of the validation errors. You can customize the error handling by catching exceptions globally using custom filters or handling them within specific controllers.

## Table Seeding
- ***Create Seed Data***: Define the data you want to seed into your tables. This can include basic records, relationships between tables, or even complex data structures.

- ***Write Seeders***: In many frameworks and ORMs (Object-Relational Mappers), there are specific mechanisms for writing seeders. These scripts or classes are responsible for inserting data into your database tables.

- ***Run Seeders***: Execute the seeders to populate your database. This is often done through command-line tools, scripts, or through an admin interface provided by your framework.

## Setup Endpoint
`[GET] api/v1/users/user_one_id`

- Generate a controller inside the users module to handle user-related endpoints.
- Inside `users.controller.ts`, define the endpoint to fetch user data based on `user_one_id`
- Access the endpoint GET `api/v1/users/user_one_id` using a tool like Postman or curl. Replace `user_one_id` with the actual user ID to get the corresponding user data.

### Outcome
{
  name: 'John Doe',
  id: 'some-user-id',
  email: 'johndoe@example.com',
  profile: {
    first_name: 'John',
    last_ame: 'Doe',
    phone: '1234567890',
    avatar_url: '<http://example.com/avatar.jpg>',
    },
    organisations: [
      {
         org_id: 'some-org-id-1',
         name: 'Some Org',
         description: 'Some Org Description',
      },
       {
          org_id: 'some-other-org-id-2',
          name: 'Some Other Org',
          description: 'Some Other Org Description',
        },
  ],
    products: [
       {
           product_id: 'some-product-id',
           name: 'Some Product',
           description: 'Some Product Description',
       },
         {  
              product_id: 'some-other-product-id',
              name: 'Some Other Product',
             description: 'Some Other Product Description',
         },
  ],
}

**Comment by markessien** [comment]
No db ticket will be accepted
