### ISSUE TITLE
[FEAT]: API ENDPOINT TO UPDATE USER'S ROLE IN AN ORGANISATION

### ISSUE THREAD

**Issue by olamstevy** [hngprojects/hng_boilerplate_nestjs#269]
## Description
Develop an API endpoint that allows only superadmins or admins including organisation owner to update the roles of other active users in an organisation. Users can only have a role such as admin, guest, or member

## Purpose
The endpoint provides superadmins and admins, including organistion owners with the right to update roles of users in an organisation.

## Acceptance Criteria
- [ ] The endpoint should be accesible at  `/api/v1/organisations/{org_id}/users/{user_id}/roles`.
- [ ] The endpoint should accept HTTP PATCH request for updating roles.
- [ ] Only superadmins, admins and owners are authorized to update a users' role in an organisation.
- [ ] The endpoint should ensure that a new role is provided in the request.
- [ ] The `role`, `user_id` and `org_id` fields must be validated.
- [ ] A 200 OK status code must be returned when the request is sucessful.
- [ ] Handle cases where the provided data is not valid.
- [ ] Handle all failed request with the appropriate error messages and status code.

## Requirements
- Superadmins, admins and owners must be authenticated and authorized.
- The organisation ID and user ID must be provided.
- The new role to be added for the user with the specified user ID must be provided.

## Database Schema
In this schema, the `role_name` field is a string of enumerated options
```
Table Roles {
    "id": String,
    "user_id": String,
    "organization_id": String,
    "role_name": String,
    "created_at": Timestamp,
    "updated_at": Timestamp,
}
```

### Requests
Update the role of a user in an organisation
Method: `PATCH`
Endpoint URL: `/api/v1/organisations/{org_id}/users/{user_id}/roles`
Authorization Header: `"Authorization": "Bearer abc123ABC123abd...."`
Request Body:
```
{
    "role": String
}
```
### Responses
Successful Response when a user role is updated.
```
{
    "message": "[firstName] [lastName] role has been successfully changed to [role]",
    "status_code": 200,
    "data": {
        "user": {},
        "org": {}
        "role": "[role]"
    }
}
```

Failed Validation Response
```
{
    "message": "Invalid data",
    "status_code": 422,
    "data": [
        {
            "field": String,
            "validationMessage": String
        },
    ]
}
```

Failed Authorization Response
```
{
    "message": "You are not authorized to manage user roles",
    "status_code": 401,
}
```

## Testing
- [ ] Write unit test to cover various scenarios.
- [ ] Write integration test to cover various scenarios.

## Documentation
The endpoint should be documented containing use cases with accurate response and error messages

## Expected Outcome
- Admins in an organisation can securely update members and other admin roles
- Clear and appropriate responses for all requests

**Comment by markessien** [comment]
duplicate

**Comment by olamstevy** [comment]
Hello @markessien, this issue is the result of a edited split endpoint from [[FEAT]: API ENDPOINT TO ASSIGN USER'S ROLE IN ANORGANISATION](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/246). My team would need a second approval on the second issue as it was approved by the same mentor twice.
