### ISSUE TITLE
[FEAT] Implement Language Selection

### ISSUE THREAD

**Issue by SamixYasuke** [hngprojects/hng_boilerplate_nestjs#28]
To convert this task description into a GitHub issue ticket, you would typically structure it with clear headings and bullet points. Here's how you might format it:

---

**Description**

Implement a language selection page in the user settings where users can choose from major languages supported by the application. This page should be designed according to the Figma design specifications.

**Acceptance Criteria**
- [ ] UI component for language selection implemented according to Figma design.
- [ ] Display a list of major languages supported by the application.
- [ ] Users can select ONLY one language.
- [ ] Selected language preferences are fetched from the server and stored locally on the browser.
- [ ] Provide user feedback upon language selection (e.g., toast notifications).
- [ ] Ensure selected language is applied consistently across the application.
- [ ] Test functionality across different browsers and devices.

**Purpose**
To allow users to set and update their preferred language for a personalized experience across the application.

**Requirements**
- **Responsive Layout**: Ensure the page is mobile-friendly and maintains responsiveness.
- **Data Retrieval**: Integrate with backend API to save and retrieve language preferences.
  - Example API Endpoint:
    ```
    POST /api/user/settings/language
    {
      "userId": "string",
      "language": "string"
    }
    ```
    Response:
    ```
    {
      "message": "Language preference updated successfully",
      "data": {
        "userId": "string",
        "language": "string"
      }
    }
    ```
- **Expected Outcome**: Develop a fully functional language selection page that allows users to select and update their preferred language, with consistent application across the site.

**Checklist**
- [ ] **Frontend Development**:
  - [ ] Implement design and layout based on Figma specifications.
  - [ ] Create reusable components for language selection.
- [ ] **API Integration**:
  - [ ] Save language preference via API request.
  - [ ] Fetch selected language from backend and handle state updates.
- [ ] **Language Selection Functionality**:
  - [ ] Implement language selection feature.
  - [ ] Store language preferences locally or using browser storage.
  - [ ] Update UI according to selected language.
- [ ] **User Feedback**:
  - [ ] Provide feedback on successful language selection (e.g., toast notifications).
- [ ] **Testing**:
  - [ ] Test across different browsers and devices for functionality and responsiveness.

**Comment by markessien** [comment]
This is a BE repo

**Comment by SamixYasuke** [comment]
Noted sir, I'll make the necessary corrections right now.

**Comment by SamixYasuke** [comment]
I've made the necessary corrections sir
