### ISSUE TITLE
[FEAT] Endpoints for Fetch Product Stock management

### ISSUE THREAD

**Issue by JumongComputers** [hngprojects/hng_boilerplate_nestjs#284]
## Description
Develop new API endpoints for managing product stock within the application. These endpoints will allow for retrieving current stock levels. This will provide flexibility and control over product inventory directly through the API.

## Acceptance Criteria

- GET `/api/v1/products/:productId/stock` endpoint is created.
-  The `GET` endpoint returns a JSON response with `productId`, `currentStock`, and `lastUpdated`.
- Proper error handling is implemented for validation errors, database connection issues, and insufficient permissions.

### Requirements	

-Create three API endpoints:
--GET `/api/v1/products/:productId/stock`: Fetch the current stock level for a specific product.
-The GET endpoint should return the following fields in JSON format:
-productId (string): The ID of the product.
-currentStock (number): The current stock level of the product.
-lastUpdated (string, date-time): The last time the stock level was updated.
-Implement proper error handling for potential issues such as database connection errors, validation errors, and insufficient permissions.

### Expected Outcome

-Functional and reliable GET `/api/v1/products/:productId/stock`,
-The endpoints return the required fields in JSON format.
-Proper error handling mechanisms are in place.

### Endpoints

GET /api/v1/products/stock

**- Success Response**
- Status: ` 200 Ok`
- Body:
```json
{
  "productId": "12345",
  "currentStock": 100,
  "lastUpdated": "2024-07-18T10:00:00Z"
}

```
**- Failure Response**
- Status: ` 400 Bad`
- Body:
```json
{
"statusCode": 400,
"message": "Bad Request"

}
```

**Comment by highb33kay** [comment]
This is too many endpoints in one ticket. You need to pick one and check for duplicate

**Comment by JumongComputers** [comment]
The last ticket that ended up  being a duplicate had similar issue.i choose just the PUT but the other teams implemented the full CRUD and it was accepted i had to close it for them since they covered what i was implementing, however i will pick one
