### ISSUE TITLE
[FEAT]: Implement Backend Support for Region Selection 

### ISSUE THREAD

**Issue by kennie-larkson** [hngprojects/hng_boilerplate_nestjs#30]
## Description

Implement backend functionality to support the region selection feature

## Acceptance Criteria
1. Create a database schema to accommodate country preferences
2. Design and implement API endpoints for country selection
3. Implement validation and error handling for country-related inputs

## Purpose

Provide backend infrastructure to manage and utilize user-selected country preferences within the application.

## Requirements	

1. Database Changes:

- Create a _*`regions`*_ table to store available regions with fields such as `region_id`, 
    `region_name`, `country_code`, `user_id` and other relevant details.

2. API Endpoints:

- GET `/api/v1/regions/`: Fetch all available regions.
          Successful Response
    ```        
              [
                    {  
                        region_id: Int,
                        region_name: String,
                        country_code: String
                     }
               ]
    ```

- POST `/api/v1/regions`: Assign a region to a user.
          Request Payload
    ```        
              
                    {  
                        user_id: String(uuid)
                        region_name: String,
                        country_code: String
                     }
               
    ```

              
- GET `/api/v1/regions/:user_id:` Retrieve the user's selected region.
         Successful Response
```
               { 
                 region_id: Int,
                 user_id: String(uuid)
                 region_name: String,
                 country_code: String
              }
```

- PUT `/api/v1/regions/:user_id:` Update the user's selected region.
   Request Payload
    ```
               { 
                 region_name: String,
                 country_code: String
              }
    ```

  Failure Response
    ```
               { 
                 status_code: String,
                 message: String
              }
    ```

4. Business Logic:
- Ensure the user's selected region is validated against the available regions.

5. Authentication and Authorization:
- Ensure that only authenticated users can update their region preferences.
- Implement necessary checks to ensure users can only update their own region.

6. Validation:
- Validate region selections to ensure they are within the predefined list of regions.

7. Error Handling:
- Handle scenarios where the region ID provided does not exist.
- Provide appropriate error messages for invalid region selections.

## Expected Outcome

- API endpoint allows users to select and update their preffered region
     - [ ] Users can successfully select and update their preferred region
     - [ ] The application can retrieve and utilize user-selected region preferences for personalized 
     experiences.
   

## Database Model
  regions
    ```
             { 
                id: Int,
                user_id: String(uuid),
                region_name: String,
                region_code: String
            }
    ```

**Comment by buka4rill** [comment]
Do something like this
![CleanShot 2024-07-17 at 18 10 59](https://github.com/user-attachments/assets/44874446-b3ec-4968-9466-2b6c264f4eba)

**Comment by buka4rill** [comment]
version the endpoints

**Comment by kennie-larkson** [comment]
- The endpoint has been versioned `/api/v1/regions`
- The Expected Outcome list has been structured as advised.
