### ISSUE TITLE
[FEAT] Email Verification Endpoint

### ISSUE THREAD

**Issue by timiajayi** [hngprojects/hng_boilerplate_nestjs#39]
## Description
Develop an endpoint to send a verification email to new users upon successful registration. This email will contain a link for users to verify their email addresses.

## Acceptance Criteria
Verification Email Endpoint [POST] /api/v1/auth/verification-email
- When a valid request is made to send a verification email, the system should send an email containing a verification link.
- The email should be sent in a timely manner.

### Purpose
To ensure that new users verify their email addresses by sending them a verification email upon successful registration.

### Requirements	
- [ ] Create an endpoint [POST] /api/v1/auth/verification-email to handle verification email requests.
- [ ] Design and implement the logic to generate a verification link and send it to the user's email.
- [ ] Ensure the verification email is sent in a timely manner upon receiving a valid request.
- [ ] Implement an email template for the verification email, including placeholders for dynamic content such as the user's name and the verification link.
- [ ] Handle any errors that occur during the email sending process and provide appropriate error messages.
- [ ] Store verification tokens securely in the database and associate them with the corresponding user.
- [ ] Update the user's verification status upon successful verification.

### Expected Outcome
- The system should send a verification email containing a verification link in a timely manner upon receiving a valid request.

**Request:**
```https
[POST] /api/v1/auth/verification-email
```
```
{
  "userId": "String",
  "email": "String"
}
```

**Successful Response:**
```
{
  "message": "Verification email sent successfully."
}
```

**Error Response:**
```
{
  "message": "Failed to send verification email.",
  "error": "String",
  "statusCode": "Int"
}
```

### Database Design
- Store verification tokens securely in the database and associate them with the corresponding user.
- Update the user's verification status upon successful verification.
- 
![email verification db](https://github.com/user-attachments/assets/40236649-7d22-455a-9211-701e77810e71)

**Comment by markessien** [comment]
emails are in one service
