### ISSUE TITLE
[FEAT] Change Plans

### ISSUE THREAD

**Issue by Shabzynana** [hngprojects/hng_boilerplate_nestjs#40]
### Description
Develop the functionality to allow users to change their subscription plans seamlessly. This feature should enable users to upgrade, downgrade, or switch plans with minimal effort.

###  Acceptance Criteria

1. **Backend API Implementation:**
   - Create API endpoints or functions to handle plan changes:
   - Implement authentication and authorisation checks to secure these endpoints.

2. **Error Handling:**
   - Implement error handling mechanisms:
   - Handle scenarios like server errors, or invalid user inputs.

### Purpose
Allow users to change their subscription plans seamlessly, enabling them to upgrade, downgrade, or switch plans with ease.

### Requirement
- **Api Implementation:** Implement endpoint to allow user change their plan
- **Secure Authentication:** Implement secure authentication mechanisms to verify user identities before allowing plan changes.
- **Error Handling:** Handle errors such as network failures, server errors, or invalid inputs gracefully to maintain system reliability.

**API Endpoints:**
   - `POST /api/change-plan`: Upgrade or downgrade a user's plan.

### Expected Outcome 
- [ ] Users can successfully upgrade, downgrade, or switch their subscription plans.
- [ ] Changes are reflected accurately across the application.
- [ ] The system handles errors and provides informative feedback to users.

**Comment by markessien** [comment]
Too broad and unclear how payments factor in
