### ISSUE TITLE
[FEAT] Implement Backend Support for Calendar Filter

### ISSUE THREAD

**Issue by Ibrahim4Grace** [hngprojects/hng_boilerplate_nestjs#41]
## Description
Implement backend support to display the current date on the dashboard calendar feature.

## Acceptance Criteria
1. Backend provides the current date in a standardized format.
2. API endpoint to fetch the current date is designed and implemented.
3. Date handling logic is implemented.
4.  API endpoint is tested to ensure reliability.
5. Documentation for API usage is provided.

### Purpose
Enable users to view the current date on the dashboard calendar component.

### Requirements	
1. API Endpoint Implementation:
  *Design and implement an endpoint, such as /api/v1/current-date, that returns the current date.
  *Ensure the API provides the date in a standardized format (e.g., YYYY-MM-DD).

2.Date Handling Logic:
*Implement logic to fetch the current date accurately.

3.Testing:
*Test the API endpoint to ensure it reliably provides the current date.

4.Documentation:
*Provide documentation for the new API endpoint.
*Include example requests and responses.

### Expected Outcome
The backend will provide the current date, which will be displayed on the dashboard calendar component, enhancing user experience by showing the accurate current date.

### Tasks
1.Design and implement an API endpoint to fetch the current date.
2.Implement date handling logic.
3.Test the API endpoint for reliability.
4.Document the API usage with examples.

**Comment by markessien** [comment]
it's unclear what is being filterd

**Comment by buka4rill** [comment]
This issue wasn't properly specified

**Comment by Ibrahim4Grace** [comment]
@buka4rill Updated

**Comment by Ibrahim4Grace** [comment]
@buka4rill @markessien @prondubuisi updated
