### ISSUE TITLE
[FEAT] New Feature Announcement By Email

### ISSUE THREAD

**Issue by yungstarry** [hngprojects/hng_boilerplate_nestjs#43]
## Description
Implementing a feature that sends an email to users to announce a new feature introduced on the platform.

## Acceptance Criteria
- [ ] Verified that the user has signed up to receive emails.
- [ ] The email is categorized under the 'new-feature' category.

### Purpose
To ensure that users are promptly informed about new features, enhancing user engagement and keeping them updated with the latest developments on the platform.

### Requirem#ents	
- [ ]  Endpoint to handle new feature announcements.
- [ ]  Validation to ensure the user email exists and is signed up.
- [ ]  Ensure emails are categorized under 'new-feature'.
- [ ]  Log email dispatches for monitoring and troubleshooting.
- [ ]  New Feature Announcement Email [POST] /api/v1/email/new-feature
- [ ]  New Feature Announcement Email Endpoint
- [ ]  Given a request with valid details (i.e., user email and feature details), when the API endpoint is called, the system should send an email announcing the new feature to the user provided, with a 200 status code.

### Expected Outcome
Users should receive an email announcing the new feature once the API endpoint is called with valid details.

### Request:
Http
POST /api/v1/email/new-feature
json
{
  "userEmail": "String",
  "featureDetails": "String"
}

Successful Response
json
{
  "message": "New feature announcement email sent successfully.",
  "emailDetails": {
    "to": "user@example.com",
    "subject": "New Feature Announcement",
    "body": "We are excited to introduce a new feature: Amazing new feature description"
  }
}

Error Response
json
{
  "message": "Invalid request: userEmail and featureDetails are required.",
  "error": "Bad Request",
  "statusCode": 400
}
or
json

{
  "message": "Internal Server Error",
  "error": "Failed to send email.",
  "statusCode": 500
}

**Comment by markessien** [comment]
emails will be in one service, and this is not a standalone featue
