### ISSUE TITLE
[FEAT] Email Notifications - Welcome Email After User Registration

### ISSUE THREAD

**Issue by donfortune** [hngprojects/hng_boilerplate_nestjs#45]
## Description
Implement a feature to send a personalized welcome email to new users upon successful registration. This email should offer a warm introduction and essential information for using the platform effectively.

## Acceptance Criteria
**Welcome Email Endpoint [POST] /api/v1/welcome-email**

**Welcome Email:**
- Given a request to send a welcome email, when the request contains valid user details, the system should send a personalized welcome email.
- The email should be sent immediately after the user's registration is successful.

### Purpose
The purpose of this feature is to enhance user engagement and satisfaction by providing new users with a welcoming and informative introduction to the platform immediately after they register.

### Requirements	
- Integrate an email service to handle the dispatch of welcome emails.
- Develop an endpoint to trigger the welcome email functionality.
- Ensure the email content is personalized based on the user’s details.

### Expected Outcome
The system should dispatch a personalized welcome email promptly upon receiving a valid request, ensuring that new users are welcomed and informed about the platform.

### Request

**[POST] /api/v1/welcome-email**

**Request Body:**
```json
{
 "userId": "String",
 "email": "String"
}


## successful response
{
 "message": "Welcome email sent successfully."
}

## error response
{
 "message": "Failed to send welcome email.",
 "error": "String",
 "statusCode": "Int"
}



###

**Comment by markessien** [comment]
email service is centralised

**Comment by Popsicool** [comment]
This will be handled by email service
