### ISSUE TITLE
[FEAT]: Blog - Creating a Blog Post

### ISSUE THREAD

**Issue by Timmy-id** [hngprojects/hng_boilerplate_nestjs#46]
## Description
- Develop an API endpoint that allows only a super admin to create a blog post.

## Purpose
- The purpose of the endpoint is for a super admin to be able to create a blog post.

## The Blog Schema

![blog drawio](https://github.com/user-attachments/assets/e48e4938-1c09-4d44-b442-a28d72d2e380)

## Acceptance Criteria
1. The endpoint allows only a super admin to create a blog post.
2. A valid token with the super admin role is supplied to the Authorization header.
3. If no Authorization header is supplied or an invalid token is supplied, the error should return a status code of 401.
4. If the token does not have the admin role, the error should return a status code of 403.
5. Returns a 200 OK status code and the correct response body when the blog is created successfully.

### Create Blog [POST] ```/api/v1/blogs```

1. A valid token is supplied to the Authorization header
    - If no Authorization header is supplied or an invalid token is supplied, the error should return a status code of 401
  
  **Request Header**
      ```
        {
            "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR..."
        }
         ```
   
2. A valid request body with correct validation is supplied:
   - The title field cannot be empty
   - The content field cannot be empty and should be rich text
   - The error should return a status code of 400 if the required fields are missing

 **Request Body**
 ```
        {
            "title": "Blog Title",     // required
            "content": "<p>First paragraph.</p><p>Second paragraph.</p>",     // required, rich text
            "tags": ["tag1", "tag2", ...],    //optional
            "image_urls": ["Image URL 1", "Image URL 2", ...]    // optional, can be inserted in the content
        }
   ```

#### Successful Response
**Status Code 201**
```
   {
       "status_code": 201,
       "message": String,
       "data": {
             "blog_id": String,
             "title": String,
             "content": Text,
             "image_urls": [String],
             "tags": [String],
             "author": String,
             "created_at": Date 
       }
   }
```
#### Error Responses
**Status Code 400**
```
   {
       "message": String,
       "status_code": 400
   }
```

**Status Code 401**
```
   {
       "message": String,
       "status_code": 401
   }
```

**Status Code 403**
```
   {
       "message": String,
       "status_code": 403
   }
```

**Status Code 500**
```
   {
       "message": String,
       "status_code": 500
   }
```

## Testing
1. Unit tests
  - Test for valid authorization token in the header
  - Test for invalid authorization token
  - Test for authorization token expiry time
  - Test that the invalid requests body, e.g. test for each required field, returns the appropriate status codes and data
  - Test that the valid request body returns the valid status code and data

**Comment by markessien** [comment]
blog posts are by super amdin

**Comment by Timmy-id** [comment]
Kindly check for the proposed changes.

**Comment by NdubuisiJr** [comment]
@Timmy-id Will a blog post have a single text and image?
Your database schema doesn't show how multiple paragraphs and image inserts can be achieved.

Work on that

**Comment by Timmy-id** [comment]
According to the Figma design, it only requires a single image to store its URL in the database.
The blog content will be stored as text @NdubuisiJr
