### ISSUE TITLE
[FEAT]: get email template by name

### ISSUE THREAD

**Issue by trevorjob** [hngprojects/hng_boilerplate_nestjs#464]
## Description

Develop an API endpoint to retrieve a specific email template by its name.

## Acceptance Criteria

- The endpoint should be accessible at ``` api/v1/email/templates/:templateName ```

- The endpoint should accept HTTP GET requests.

- The endpoint should be secured to ensure that only authenticated users can retrieve an email template.

- Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.

- Requests to the endpoint must include a valid authentication token in the Authorization header: Authorization: Bearer <token>

- The endpoint should return the content of the specified email template if it exists.

## Request

- HTTP Method: GET

- Endpoint: ``` /api/v1/email/templates/:templateName ```

- **Request Headers:**
```python
{
  "Authorization": "Bearer <token>"
}
```
- **Response**

- On Successful Retrieval

- Status Code: 200

- **Response Body:**
```python
{
{
  "status_code": 200,
  "data": {
    "template": {
      "name": "templateName.hbs",
      "content": "{{!-- Handlebars template content --}}"
     }
  }
}
```

- If the User is Not Authenticated

- Status Code: 401 Unauthorized

- **Response Body:**
```python
{
  "success": false,
  "status_code": 401,
  "message": "Not authenticated"
}
```
## Purpose

- Provides a backend service for users to retrieve a specific email template by its name from Handlebars (.hbs) files.
## Requirements

- Develop server-side logic to retrieve an email template by its name from the filesystem.

- Ensure that only authenticated users can access this endpoint.

## Expected Outcome

- The API endpoint allows authenticated users to retrieve a specific email template with appropriate validation and authentication.

**Comment by ezeanyimhenry** [comment]
https://github.com/hngprojects/hng_boilerplate_nestjs/issues/273
