### ISSUE TITLE
[FEAT]: Admin Profile Information Retrieval

### ISSUE THREAD

**Issue by Skibo555** [hngprojects/hng_boilerplate_nestjs#47]
## Description
Retrieve admin profile information

## Acceptance Criteria 

- [ ] Endpoint to display admin profile data.

- [ ] Handle success and error responses. 

- [ ] Write unit test for accurate retrieval of admin data.

### Purpose
Provide endpoint for admin to view profile

### Requirements	
 - [ ] Admin must be authenticated and authorised.

### Expected Outcome
Secure endpoint to allow admin view profile information

### 
**Fetch Plans:**

Description: API endpoint to retrieve admin profile information
Endpoint: GET /api/v1/admin/{admin_id}
Response (Success): json
```
{
  "status": "success",
  "message": "Admin profile information retrieved successfully",
  "data": {
      "user_id": "String",
      "first_name": "String",
      "last_name": "String",
      "email": "String"
    }
}
```
Response (Error): json
```
{
  "status": "error",
  "message": "Authentication failed",
  "status_code": 401
}
```
### Testing

- [ ] Write a unit test to fetch a user's details if the user exists and is authenticated.

**Comment by markessien** [comment]
unclear what this is, and is likely not a real ting

**Comment by markessien** [comment]
Closing it permanently as the person cannot figure it out.
