### ISSUE TITLE
[FEAT] Password Change Confirmation Email

### ISSUE THREAD

**Issue by AdelakunShola** [hngprojects/hng_boilerplate_nestjs#48]
## Description
The Password Change Confirmation feature allows users to reset their passwords securely by verifying a reset token. All email-related functionalities are managed by a centralized email service for consistency.

### Purpose
To provide a secure mechanism for users to reset their passwords by verifying the reset token. the feature enhances the overall security of user accounts.

### Requirements	
- [ ] User Information:
The request must include the user's first name, last name, and the new password.

- [ ] Secure Token:
A valid reset token must be provided to confirm the password reset.
The token must be validated for authenticity and expiry.

- [ ] Endpoint:
An API endpoint (POST /api/v1/auth/confirm-password-reset) to handle the password reset confirmation.

- [ ] Error Handling:
Appropriate error responses for invalid token, expired token, and weak password scenarios.
If the reset token is invalid, the system should respond with an appropriate error message.
If the reset token has expired, the system should respond with an appropriate error message.

### Expected Outcome
The system should successfully update the user's password if the reset token is valid.
Appropriate error messages should be provided for invalid token, expired token.

### 
## Request Formats

- **Request:**

  - Method: POST
  - URL: `/api/v1/auth/confirm-password-reset`

    ```json
    
        {
            "token": "String",
            "newPassword": "String",
            "firstName": "String",
            "lastName": "String"
       }

    
    ```

- **Successful Response:**
  - Status Code: 201 OK
  - Response Body (JSON):

    ```json
    
        {
            "message": "String"
       }

    ```

- **Error Handling:**

  - Status Code: 400 Bad Request
  - Error Responses (JSON):

    ```json
    
       {
            "message": "string",
             "status_code": 500
        }

    ```

**Comment by markessien** [comment]
emails are centralised

**Comment by markessien** [comment]
does not make sense

**Comment by AdelakunShola** [comment]
I have made some changes sir, please review
