### ISSUE TITLE
[FEAT] Pricing  Page - Implement API Endpoint for Creating Subscription Payments

### ISSUE THREAD

**Issue by dorisjenny27** [hngprojects/hng_boilerplate_nestjs#53]
## Description
Develop an API endpoint to create new subscriptions through the payment gateway for the pricing page.

## Acceptance Criteria

1. API Endpoint Implementation:
   * Create an API endpoint to receive subscription creation requests.
   * The endpoint should handle the creation of new subscriptions efficiently.

2. Input Validation:
   * Implement robust validation for input data, including plan ID and user details.
   * Ensure all necessary data is present and in the correct format before processing.

3. Payment Gateway Integration:
   * Integrate with the chosen payment gateway API to create subscriptions.
   * Handle various response scenarios from the payment gateway.

4. Error Handling:
   * Implement comprehensive error handling for various scenarios.
   * Provide appropriate and informative error responses.

### Purpose
To enable the creation of new subscriptions by integrating with a payment gateway API.

### Requirements	
* Design RESTful API endpoint for subscription creation.
* Implement validation middleware for input parameters.
* Integrate with the payment gateway API for subscription creation.
* Develop error handling strategies and meaningful error messages.

### Expected Outcome
A functional API endpoint that can create new subscriptions with robust error handling.

### Create Subscription
Description: Create a new subscription through the payment gateway.

```
POST /api/subscriptions
```

```JSON
{
"planId": "String",
"userId": "String",
"paymentDetails": {
}
}
```

Response (Success)

```JSON
{
"message": "Subscription created successfully",
"subscriptionId": "String",
"status": "active"
}
```

Response (Error)

```JSON
{
"message": "Failed to create subscription",
"error": "Detailed error message",
"statusCode": 400
}
```

## Testing
* Write unit tests for the subscription creation endpoint.
* Test various scenarios including successful creation, validation errors, and payment gateway errors.
* Ensure proper error handling and appropriate responses for different scenarios.
* Test the integration with the payment gateway using mock data.

**Comment by markessien** [comment]
Not correct

**Comment by dorisjenny27** [comment]
closed
