### ISSUE TITLE
[FEAT] Implement Email-Based Support Ticket Submission

### ISSUE THREAD

**Issue by Oluwaseg** [hngprojects/hng_boilerplate_nestjs#57]
### Title

**[FEAT] Backend API Template for Support Management (v1)**

---

### Description

This boilerplate outlines a backend API structure for managing support requests, designed to handle creation, retrieval, updating, and deletion of support inquiries via email integration.

---

### Purpose

To provide a foundational backend API framework for efficiently managing support requests via email communication, ensuring organized tracking and resolution of user-reported issues.

---

### Requirements

- **Email Integration (optional):** Support requests are initiated via email, with inbound emails processed and converted into support tickets within the application.

- **CRUD Operations:** The API must handle creation, retrieval, updating, and deletion of support requests.

- **Error Handling:** Proper validation and feedback for invalid requests.

- **Database:** A database schema to store support requests with fields such as *id*, *subject*, *body*, *senderEmail*, *status*, *createdAt*, and *updatedAt*.

- **Security:** Implementation of security measures to protect sensitive user data (e.g., encryption of emails and user information).

---

### Expected Outcome

- A backend API that provides endpoints for CRUD operations for support requests.

- A database schema that supports the storage and management of support requests.

- Robust error handling that ensures proper validation and user feedback.

- Secure handling of sensitive data throughout the application.

---

### Email Integration

- Support requests are initiated via email, with inbound emails processed and converted into support tickets within the application.

### Backend API Endpoints

- [ ] **Create Support Request (POST /v1/support)**
  - **Request Body (JSON)**:

     ```json
     {
       "subject": "string",
       "body": "string",
       "senderEmail": "string",
       "status": "string"
     }
     ```

  - **Success Response**:
    - Status: 201 Created
    - Body (JSON): `{"message": "Support request created successfully."}`
  - **Error Response**:
    - Status: 400 Bad Request
    - Body (JSON): `{"error": "Invalid request format."}`

- [ ] **Read Support Request (GET /v1/support/:id)**
  - **Success Response**:
    - Status: 200 OK
    - Body (JSON):

       ```json
       {
         "id": "string",
         "subject": "string",
         "body": "string",
         "senderEmail": "string",
         "status": "string",
         "createdAt": "string",
         "updatedAt": "string"
       }
       ```

  - **Error Response**:
    - Status: 404 Not Found
    - Body (JSON): `{"error": "Support request not found."}`

- [ ] **Update Support Request (PUT /v1/support/:id)**
  - **Request Body (JSON)**:

     ```json
     {
       "subject": "string",
       "body": "string",
       "status": "string"
     }
     ```

  - **Success Response**:
    - Status: 200 OK
    - Body (JSON): `{"message": "Support request updated successfully."}`
  - **Error Response**:
    - Status: 400 Bad Request
    - Body (JSON): `{"error": "Invalid request format."}`

- [ ] **Delete Support Request (DELETE /v1/support/:id)**
  - **Success Response**:
    - Status: 204 No Content
    - Body: No content
  - **Error Response**:
    - Status: 404 Not Found
    - Body (JSON): `{"error": "Support request not found."}`

### Database Schema

![Untitled (1)](https://github.com/user-attachments/assets/2b4da8f0-0608-43cf-bdd5-7c4fc09806c4)

- **SupportRequests** table schema:
  - Define according to chosen database system. Example for MySQL:

    ```sql
    CREATE TABLE SupportRequests (
      id INT AUTO_INCREMENT PRIMARY KEY,
      subject VARCHAR(255) NOT NULL,
      body TEXT,
      senderEmail VARCHAR(255) NOT NULL,
      status VARCHAR(20) DEFAULT 'open',
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    ```

---

### Checklist / Acceptance Criteria

- [ ] Incoming emails are parsed and converted into support requests.
- [ ] API endpoints handle CRUD operations effectively with appropriate status codes.
- [ ] Error handling ensures proper validation and feedback for invalid requests.
- [ ] Integration with email service provider ensures reliable email processing.
- [ ] Data integrity and consistency are maintained through database transactions.
- [ ] Security measures are implemented to protect sensitive user data (e.g., encryption of emails and user information).

**Comment by markessien** [comment]
We are not doing ticketing in this app

**Comment by Oluwaseg** [comment]
> We are not doing ticketing in this app

It's been revised now, please take a look at it

**Comment by Oluwaseg** [comment]
Creating another ticket
