### ISSUE TITLE
[FEAT] Implement Multi-Lingual Support

### ISSUE THREAD

**Issue by adara-code** [hngprojects/hng_boilerplate_nestjs#59]
## Description
Integrate external language support libraries to enable seamless multilingual functionality in the application's frontend.

### Multi-language
1. Incorporate a front-end library to manage support for multiple languages.
2. Add a language switcher component which allows users to choose their preferred language.
3. Implement UI components that change content according to the language selected by the user.

### Responsiveness
1. Ensure the feature is responsive and compatible across different devices and screen size.

### Testing
1. Test the endpoint to ensure that a specific language is returned.
2. Perform unit testing to verify language support across popular browsers and devices.

### Purpose
Enhance user experience by enabling users to interact with the application in their preferred languages.

### Requirements	
- [ ] Implement a front-end library which handles the multi-lingual feature.
- [ ] Add UI components that dynamically render content according to the language that the user has chosen
- [ ] Test the multi-lingual feature across browsers and devices for compatibility and responsiveness.

### Expected Outcome
Users should be able to have  a smooth and intuitive multilingual experience, by seamlessly navigating and interacting with content in their chosen languages.

### Endpoints
GET  /api/dashboard/en

Successful Response
`
    { "success" : true, 
      "payload" : {
               "userId" : 1,
               "language" : "en"
           }
    }
`

Unsuccessful Response
`
    { "success" : false, 
      "payload" : {
               "Page not found"
         },
       "error" : {
               "No matches found to the specified language"
        }
    }
`

**Comment by markessien** [comment]
Duplicate

**Comment by adara-code** [comment]
Closed the feature because it's marked as duplicate.
