### ISSUE TITLE
[FEAT]: Squeeze Page Implementation - BACKEND

### ISSUE THREAD

**Issue by Solomonuche** [hngprojects/hng_boilerplate_nestjs#69]
## Description

*Develop a backend endpoint to handle requests for users who want a copy of the boilerplate. The endpoint will accept an email address, validate, sanitize it, and handle both successful and failed validations appropriately. If the email passes validation, it will be stored in the database and a success response is sent to the client. If validation fails, an error message will be returned.*

## Acceptance Criteria
- Accepts and validates User's email.
- Persist the data to the database.
- Return the appropriate response and status code

### Purpose
To grant the user access to the boilerplate in exchange for their email

### Requirements	
- [ ] A valid email address
- [ ] An API endpoint with data validation and sanitization
- [ ] Set up database integration and secure storage
- [ ] Add rate limiting and CSRF protection measures
- [ ] Integrate email service for confirmation messages
- [ ] Conduct security testing and performance optimization

### Expected Outcome
- The user input data should be successfully sent to the backend, or the user will receive an error message if unsuccessful

**Status code**
- **201**: Email was successfully stored.
- **400**: Invalid email address.
- **401**: Email already exist.
- **500**: A server error occurred.

### Endpoint
**[POST] /api/v1/pages/squeeze**

**Requests:**

*headers:*
- content-type: application/json

```json
{
    "email": "string"
}
```
**Responses:**

*Successful response*
```json
{
    "message": "string",
    "success": true,
    "status code": int
}
```

*Error response*
```json
{
    "message": "string",
    "success": false,
    "status code": int
}
```

## Database design
**schema**

**Table name: squeeze_table**

*id:*
- constraints: string(uuid), unique, primary-key, not null

*email:*
- constraints: string, unique, not null, length(150)

*createdAt:*
- constraints: string, date timestamp

## Testing

1. Unit Tests

The systems should have unit tests covering:
- [ ] Validates User's email and check for duplicate emails.
- [ ] Ensure data is saved correctly to the database.
- [ ] Test that the appropriate response and status code is returned

**Comment by markessien** [comment]
Squeeze page is far more than this

**Comment by Fifetoyi** [comment]
Hi @Solomonuche can you confirm if you're still working on this? I have a duplicate ticket, though I have noticed you are now working on something else. Thanks

**Comment by Solomonuche** [comment]
I will reach out to the team in charge and revert back.

**Comment by Fifetoyi** [comment]
Thanks

**Comment by phurhard** [comment]
@Solomonuche you can close this issue if you're not working on it again, I'll do that now self
 @Fifetoyi already working on an approved version of it

**Comment by coderoyalty** [comment]
@phurhard 
Issue #80 was approved before this. As of now, this issue is yet to be approved.

**Comment by coderoyalty** [comment]
@phurhard the approved version isn't yours. Find another issue, and don't work out the approved one
.

**Comment by phurhard** [comment]
> @phurhard Issue #80 was approved before this. As of now, this issue is yet to be approved.

Ehh, what are you saying exactly

**Comment by coderoyalty** [comment]
Sorry, I misunderstood. I thought I saw a pull request closing #80, but never mind.0.

**Comment by Solomonuche** [comment]
I made this issue for my team mates since I was the team Lead and had access to the repo. I have reached out to the team but no feedback
