### ISSUE TITLE
[FEAT] Support Ticket Acknowledgment (resolved)

### ISSUE THREAD

**Issue by emarc99** [hngprojects/hng_boilerplate_nestjs#70]
## Description

When a support ticket that is already opened and acknowledged on the website is resolved, the user should be informed.

### Support Ticket Acknowledgment:

+ A user opens a support ticket on the website.
+ The ticket is acknowledged by the support team.

### Ticket Resolution:

+ The support team resolves the ticket.
+ The user is informed about the resolution.

### Notifications:

+ Users are notified when their support ticket has been resolved.
+ Users are informed if there are any issues with their ticket resolution.

### Purpose

The purpose of the support ticket resolution notification feature is to:

+ Ensure users are informed about the status of their support tickets.
+ Enhance user satisfaction by providing timely updates on ticket resolution.

### Ticket Model:

+ user_id: Integer, required
+ ticket_id: Integer, required, unique
+ status: String, required (open, acknowledged, resolved)
+ description: Text, required

### Database:

+ Store ticket data including user ID, ticket ID, status, and description.

### Expected Outcome

- [ ] Users receive a notification email upon ticket resolution.
- [ ] Users can view the status of their ticket on the website.
- [ ] The system handles unresolved tickets gracefully.
- [ ] Users receive appropriate notifications regarding the status of their support ticket.

### Status code: 200 OK

``` json
{
  "message": "Support ticket resolved successfully."
}
```

### Status code: 400 Bad Request

``` json
{
  "error": "Invalid or unresolved ticket."
}
```

### Status Code: 409 Conflict

``` json
{
  "error": "Ticket already resolved."
}
```

**Comment by markessien** [comment]
We are not building a ticketing system
