### ISSUE TITLE
[FEAT] Implement Notification Data Model- Backend

### ISSUE THREAD

**Issue by joboy-dev** [hngprojects/hng_boilerplate_nestjs#71]
## Description

To define and implement a database schema for storing and managing notifications.

### Define database schema for user profile settings.

* Define a table called **`notifications`**
* The table should contain the following fields:
    - `id` (integer, primary key)
    - `unique_id` (string, unique)
    - `sender_user_id` (integer, foreign key to the `users` table, not null)
    - `receiver_user_id` (integer, foreign key to the `users` table, not null)
    - `content` (string, not null)- This is the message in the notification.
    - `type` (string, not null)- The type of the notification.
    - `status` (string, 20, not null, default is `unread`)- Could be one of `read` and `unread`
    - `created_at` (timestamp, default current timestamp)
    - `updated_at` (timestamp, default current timestamp, auto-update on modification)
* Ensure the schema follows best practices for data normalization and indexing.

### Implement necessary database migrations

* Use a database migration tool to automatically generate database migration scripts after all relevant fields have been defined in the `notifications` schema.
* Run the migration scripts to ensure that the database has accepted all changes and has been correctly modified.

## Purpose

Define and implement the data structure to efficiently manage notifications.

## Requirements

- [ ] Design a table named `notifications` to store all notifications.
- [ ] Add all relevant fields to the table.
- [ ] Use the database migration tool to generate migration scripts for the new schema.
- [ ] Run database migration scripts.

## Expected Outcome

* A new `notifications` table is created with fields for user preferences.
* The table schema is well-defined, indexed appropriately, and follows best practices.
* The database migrations are implemented and tested successfully, with clear documentation for future reference.
![HNG Sub task DB](https://github.com/user-attachments/assets/ab9e64ef-79d4-4951-884d-2eccd726cd8c)

**Comment by markessien** [comment]
DB design is not a ticket
