### ISSUE TITLE
[FEAT] :Endpoint to Add Job Application -BE

### ISSUE THREAD

**Issue by oderahub** [hngprojects/hng_boilerplate_nestjs#73]
### Description

Develop backend logic to handle job applications, including validation, storage, and management.

### Acceptance Criteria

API Endpoint Implementation:

1. The endpoint should be accessible at ` /api/v1/jobs/{job-id}/applications`

2. The endpoint should accept HTTP `POST` requests.

Data Validation and Management:
1. Implement server-side logic to handle job applications.
2. Validate applications against job requirements stored in the database.
3. Prevent duplicate applications from the same candidate for the same job.

### Purpose

To streamline the job application process on the careers page, ensuring efficient handling, validation, and management of job applications.

### Requirements

-  Develop server-side logic to handle job applications.

-  Securely store application details in the database.

-  Ensure compliance with security standards for handling applicant information.

### Expected Outcome

- Backend handles job applications efficiently.
- Applications are validated and stored correctly.

### Endpoints:
Submit Job Application

Description: Submit a job application for a specific job.
Endpoint:         `POST  /api/v1/jobs/{job-id}/applications`
Request Body

```
{
  "applicant_name": "John Doe",
  "email": "johndoe@example.com",
  "resume": "https://example.com/resume.pdf",
  "cover_letter": "Cover letter text here"
}

```

- Response 

- On a successful addition of a new Application to the Database, the API should return a 201 Created status_code.

- The response body should contain the newly created application details, including the  ID.

```
{
  "status": "success",
  "message": "Application submitted successfully",
  "status_code": 200
}
```

- Validation

- If any required field is missing or invalid, the API should return a 400 Bad Request status code with appropriate validation error messages.

```

{
  "error": "Bad Request"
  "message": ["applicant_name is required", "email is required", "cv is required",  "cover_later is required"],
  "status_code": 400
}
  
```

- Response (Duplicate Application)

- If the same applicant tries to apply for the same job more than once, the API should return a 409 Conflict status code with a duplicate application message.

```
{

  
  "message": "Duplicate application.",
   "status_code": 409
 
}
```
Tasks

- [ ] Validate the input data for required fields.

- [ ] Check for duplicate applications based on applicant email and job ID.

- [ ] Store the application details in the database securely.

- [ ] Ensure applicant details are encrypted.

- [ ] Implement logic to prevent the same applicant from applying more than once to the same job.

Testing

1. Write unit tests for backend validation and transaction handling.

2. Perform security testing to ensure data protection and compliance.

3. Test various scenarios for submitting job applications.

**Comment by markessien** [comment]
This is not a single ticket

**Comment by oderahub** [comment]
modified .. i require access to label and I need to be assigned to me ..

**Comment by highb33kay** [comment]
```
{ 
 "status_code": 201
  "application_id": Id,
  "message": "Application submitted successfully.",
 
}
```

Please check other approved tickets formatting

**Comment by bamo100** [comment]
@highb33kay kindly grant permission to work on the ticket

**Comment by highb33kay** [comment]
Approved. Check for duplicates and proceed please. Thank you!!
