### ISSUE TITLE
[FEAT]: Help Center - Get All Articles

### ISSUE THREAD

**Issue by Solomonuche** [hngprojects/hng_boilerplate_nestjs#76]
## Description
This page serves as the central hub for our help center, providing users with access to a wealth of informative articles.
## Acceptance Criteria
- Articles are being sent on page load.
### Purpose
This displays articles that are guides for users and FAQs.
### Requirements
- [ ] List all articles
### [GET] /api/v1/topics
**Description**
- Get all available help Topics

  **Successful Response**
  Status code: 200
```  
{
  "success": true,
  "message": String,
  "topics": [
        {
            "article_id": Int,
            "title": String,
            "content": String,
        }
        ...
    ]
  }
```

**Error Response**
Status code: 500
```
{
  "success": false,
  "message": String,
  "statusCode": 500
}
```
## Database Schema
_Table name: articles_table_
_article_id:_
- constraints: string(uuid), unique, primary-key, not null
  title:
- constraints: string, unique, not null, text
  content:
- constraints: string, not null, text
  createdAt:
- constraints: datetime
  updatedAt:
- constraints: datetime
### Database diagram
[Database](https://drive.google.com/file/d/17Qnkk9A0kxLiUxMQhnd124vFaaewh76a/view?usp=sharing)

### Testing
1. Unit Tests
- The return data for the /api/v1/topics matches the documentation.

**Comment by buka4rill** [comment]
please change `statusCode` to `status_code`

**Comment by NdubuisiJr** [comment]
@Solomonuche Implement pagination. All `FetchAll` endpoints should include pagination support. The response should also include pagination meta data
```js
{
   ...
   meta: {
     has_next: boolean,
     total: number,
     next_page: number | null,
     prev_page: number | null
  }
}
```

**Comment by highb33kay** [comment]
@Solomonuche No interest in this ticket anymore?

**Comment by highb33kay** [comment]
Can we reassign?

**Comment by CFCIfe** [comment]
Please take note about the updated route - https://github.com/hngprojects/hng_boilerplate_nestjs/issues/111#issuecomment-2235907567

**Comment by Solomonuche** [comment]
If no one from my team has claimed this ticket upto now, you can reassign it pls
