### ISSUE TITLE
[FEAT] : Delete product API - Backend

### ISSUE THREAD

**Issue by covenant123456** [hngprojects/hng_boilerplate_nestjs#77]
### Description: 
Develop a secure backend API endpoint that allows for the deletion of a product by its ID. This service will enable authenticated users to remove specific products from the database. The endpoint should handle scenarios where the product does not exist and return appropriate error messages.

### Purpose: 
Provide a reliable and secure backend service for deleting products, ensuring efficient management and cleanup of product data.

### Requirements:
1. **Implement Endpoint**:
    - Develop an endpoint to delete a product by its ID.
    - Endpoint should be accessible via a DELETE request.
2. **Ensure Endpoint Security**:
    - Secure the endpoint to ensure only authenticated users can delete products.
    - Implement authentication checks.
3. **Handle Non-existent Products**:
    - Implement error handling for cases where the requested product ID does not exist in the database.
    - Return a meaningful error message when a product is not found.

### Acceptance Criteria:
- Endpoint successfully deletes the product when a valid product ID is provided and the user is authenticated.
- Returns a confirmation message upon successful deletion.
- Proper error handling is in place for non-existent product IDs, with clear and user-friendly error messages.
- API documentation is updated to include endpoint details and usage examples.

### Checklist:
- [ ] Develop API endpoint to delete a product.
- [ ] Implement authentication checks to secure the endpoint.
- [ ] Ensure the endpoint deletes the product and returns a confirmation message.
- [ ] Implement error handling for non-existent products.
- [ ] Test endpoint with valid and invalid product IDs.
- [ ] Update API documentation with endpoint details and examples.

### Endpoint:

**API Request: Delete Product**
```
DELETE /api/v1/products/{productId}
Headers:
  Authorization: Bearer <token>
```

**API Response: Success (200)**
```json
{
    "message": "Product deleted successfully."
}
```

**API Response: Product Not Found (404)**
```json
{
    "error": "Product not found",
    "message": "The product with ID 999 does not exist."
}
```

**API Response: Unauthorized (401)**
```json
{
    "error": "Unauthorized",
    "message": "You must be authenticated to delete a product."
}
```

### Dependencies:
- Ensure the database contains product data for testing.
- Coordinate with the frontend team to ensure they understand the response format.
- Implement an authentication mechanism if not already in place.

**Comment by markessien** [comment]
Split these into one ticket per operation

**Comment by markessien** [comment]
Also, this seems to be a duplicate

**Comment by covenant123456** [comment]
@Synth
@Deola Deosun
@Covenant12 4️⃣

**Comment by NdubuisiJr** [comment]
@covenant123456 Indicate the status code the endpoint will return and following the route versioning pattern.

**Comment by covenant123456** [comment]
the status code has been included and the route is following the versioning pattern
