### ISSUE TITLE
[FEAT] Implement a Waitlist Page - FRONTEND

### ISSUE THREAD

**Issue by Nifilat** [hngprojects/hng_boilerplate_nestjs#78]
## Description
Develop a waitlist page that effectively communicates the product's benefits, and features, and includes a form for visitors to join the waitlist.

## Acceptance Criteria
1. Compelling Headline:
   - When a visitor lands on the waitlist page, a headline should capture their attention and convey the product's main benefit.
2. Product Description Section:
   - Given the waitlist page loads, a brief description of the product highlighting its unique aspects should be displayed.
   - At least three key benefits or features of the product should be listed.
   - Supporting icons or images should be included to enhance the description visually.
3. Waitlist Form:
   - Given a visitor views the waitlist page, an input field for collecting the user's name and emails should be present.
   - When the visitor submits a valid email, the email should be sent to the backend for storage.
   - If an invalid email format is entered, an error message should be displayed prompting the user to enter a valid email.
4. Form Submission Feedback:
   - When a visitor submits their email, a confirmation message should appear, indicating successful sign-up.
   - If the submission fails, an appropriate error message should be displayed.
  

### Purpose
Create a waitlist page showcasing the product and benefits to encourage user sign-ups.

### Requirements	
- [ ] Compelling headline created.
- [ ] Brief and impactful product description written.
- [ ] At least three key benefits or features are listed.
- [ ] Supporting icons or images included.
- [ ] Input field for user name and email added.
- [ ] Emails collected are sent to the backend.
- [ ] Form validation for email format implemented.
- [ ] Confirmation message upon successful submission.
- [ ] Error message for invalid email format.
- [ ] Text reviewed for clarity and conciseness.

### Expected Outcome
Visitors should quickly understand the product's value proposition and be motivated to join the waitlist by entering their email and clicking the submit button.

###  Testing
1. Headline and Content Display:
   - Verify that the headline, product description, and benefits/features are displayed correctly on the waitlist page.
2. Email Input Validation and Submission:
   - Verify that the input field accepts valid email formats and displays an error message for invalid formats.
   - Verify that submitting a valid email triggers a confirmation message and sends the email to the backend.
3. Form Submission Error Handling:
   - Verify that submitting an invalid email format triggers an appropriate error message.

**Comment by markessien** [comment]
this is laabelled as FE. This is a BE repo
