### ISSUE TITLE
[FEAT] Fetch all Users of an Organisation API - BACKEND 

### ISSUE THREAD

**Issue by scottandee** [hngprojects/hng_boilerplate_nestjs#79]
## Description
Develop API endpoint to fetch the list of all the users in a single organization

## Acceptance Criteria
- The endpoint should be accessible at `api/v1/organization/<orgId>/users`
- The endpoint should accept HTTP `GET` requests.
- The endpoint should be secured to ensure that only authenticated users can fetch users in the organization
- The endpoint should check that the user is a member of the organization
- The endpoint should check that the organisation Id in the url path is an existing organization
- Requests to the endpoint must include a valid authentication token in the Authorization header. `Authorization: Bearer <token>`

### Request	
GET `/api/v1/organization/:orgId/users`

- **Parameters**:
    - orgId - `string` - The id of the organisation whose users are to be retrieved
- **Query Parameters**:
    -  `page`: integer (optional) defaults to `1` - Pagination parameter specifying the page number to be retrieved
    - `page_size`: integer (optional) defaults to `10` - Pagination parameter specifying the number of users retrieved per page

### Expected Outcome
- Successful Response
    - On success, the list of users in the organisation should be sent with a `200` status code
    - The response body should contain a list of users, including the userId.
      ```json
      {
         "status": "success",
         "message": "Users retrieved successfully",
         "users": [
           {
             "id": "String",
             "email": "String",
             "phone_number": "String",
             "name": "String"
           },
         ],
         "status_code": 200
      }
      ```
- Server Error Response
  - Status: `500 Internal Server Error`
  - Body:
    ``` json
    {
      "error": "Internal server error"
      "status_code": 500
    }
    ```

- Unauthenticated User Error
  - Status: `401 Unauthorized`
  - Description: This error is returned when a user tries to access this endpoint while not logged in
  - Body:
    ``` json
    {
      "error": "User not logged in"
      "status_code": 401
    }
    ```
- Forbidden User Error
  - Status: `403 Forbidden`
  - Description: This error is returned when a user tries to retrieve the list of users of an organization they are not a part of
  - Body:
    ``` json
    {
      "error": "User does not have access to the organization"
      "status_code": 403
    }
    ```

#### Purpose
Provides a backend service which allows users to fetch all users in their organization

#### Requirements
- Develop server-side logic to fetch all users of a single organisation
- Ensure compliance with security standards for handling user information.

#### Unittests:
1. Successful users retrieval with a valid token and User ID.
2. Test for unauthorized access without a valid token.
3. Test for forbidden access when the user lacks appropriate permissions.
4. Perform security testing to ensure data protection and compliance.

**Comment by markessien** [comment]
Superadmin does not retrieve in a different way

**Comment by Armolas** [comment]
Team Members slack IDs:
@Dayo A
@Omozua Jonah

**Comment by markessien** [comment]
This appears duplicated

**Comment by Armolas** [comment]
This retrieves all the users of a single organisation while that retrieves all the organisation of a single user

**Comment by markessien** [comment]
this appears duplicated still, but we will find out when the PR enters
