### ISSUE TITLE
[FEAT] Fetch single user API 

### ISSUE THREAD

**Issue by scottandee** [hngprojects/hng_boilerplate_nestjs#81]
## Description
Develop API endpoint to fetch a single user

## Acceptance Criteria
- The endpoint should be accessible at `api/v1/users/:userId`
- The endpoint should accept HTTP `GET` requests.
- The endpoint should be secured to ensure that only authenticated users can fetch all users
- The endpoint should check that the user has the appropriate permissions
- Requests to the endpoint must include a valid authentication token in the Authorization header. `Authorization: Bearer <token>`
- Given a request with a valid user ID, when the user is authenticated and authorized, the system should retrieve the user's information with a status code of 200.
- Given a request with an invalid or non-existent user ID, when the user is authenticated and authorized, the system should return a 404 Not Found status.

#### Endpoint	
GET `/api/v1/users/:userId`

#### Parameters:
- `userId`: string

### Expected Outcome
- **Successful Response**
```bash
{
  "status": "success",
  "message": "User retrieved successfully",
  "user": {
    "id": "String",
    "name": "String",
    "email": "String",
    "phoneNumber": "String"
  }
}
```

- **Error Response**:

```bash
{
  "status":string,
  "message": string,
  "status_code":int
}
```

### Purpose
Provides a backend service which allows users to fetch a single user

### Requirements

- [ ]  Develop server-side logic to fetch a single user
- [ ] Ensure compliance with security standards for handling user information.

### Create User Fetching Logic

- [ ]  Implement the GET /api/users/:userId endpoint.
- [ ]  Query the database to retrieve user details by user ID.
- [ ]  Handle errors and return appropriate responses when the user is not found.

### Authorization Checks

- [ ]  Ensure that only authorized users (e.g., the user themselves or administrators) can access this endpoint.
- [ ] Implement middleware to check if the requester is authorized to fetch user details.

### Database Operations:

- [ ]  Create a schema for storing user details if not already existing.
- [ ]  Securely retrieve user details from the database.
- [ ]  Ensure compliance with data protection standards.

### Error Handling and Logging:

- [ ] Implement comprehensive error handling for different failure scenarios (e.g., user not found, unauthorized access).
- [ ]  Log errors and access attempts for monitoring and troubleshooting.

### Tests

1. Write unit tests for the GET /api/users/:userId endpoint.
2. Write unit tests for validation and error handling logic.
3. Write integration tests for the end-to-end user fetching process.
4. Test the full flow from requesting user details to receiving the response.
5. Ensure the system handles successful and failed requests appropriately.

**Comment by markessien** [comment]
Retrieval by superadmin is not different from standard retrieval

**Comment by King-Mikaelson** [comment]
### Team Members working on this issue include:

- [Essd]https://github.com/essd23 - Python - Slack_Id - Essd
- [Heisienberg](https://github.com/Jayyp1234) - PHP - Slack_Id - Heisienberg

I couldn't assign them directly to the repo since they don't have access to the repo

**Comment by buka4rill** [comment]
change `statusCode` to `status_code`

**Comment by King-Mikaelson** [comment]
> change `statusCode` to `status_code`

Done thank you
