### ISSUE TITLE
[BUG] (BE PYTHON)  Deactivate or Correct Non-Functional Payment Gateways

### ISSUE THREAD

**Issue by Kah-keh** [hngprojects/hng_boilerplate_nestjs#815]
## Description
The current payment gateway options (credit card, PayPal, Stripe) on Anchor python boilerplate, do not function correctly, yet the process shows a successful transaction. This should be corrected or the options should be deactivated or not clickable until they are fully integrated.

## Acceptance Criteria

- The payment gateway options should be either fully functional or deactivated/ not clickable if integration is incomplete.

### Purpose
To prevent misleading users with a false success notification when they go through the payment gate way process.

### Requirements	

- Fix the integration for all payment gateway options.
- Implement error messages for cases where the payment gateway is not available or the transaction fails.

### Expected Outcome
Only fully integrated and functional payment gateway options are available to users, with accurate error handling and feedback.

**Comment by MikeSoft007** [comment]
HI @Kah-keh please confirm that the issue reproduction is on Anchor python boilerplate
The interface you are reproducing from is different
See image below
![image](https://github.com/user-attachments/assets/2037f9d4-df16-4831-8467-45d9afa469e5)

**Comment by Kah-keh** [comment]
> HI @Kah-keh please confirm that the issue reproduction is on Anchor python boilerplate The interface you are reproducing from is different See image below ![image](https://private-user-images.githubusercontent.com/54174323/360343555-2037f9d4-df16-4831-8467-45d9afa469e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTY2ODcsIm5iZiI6MTcyNDMxNjM4NywicGF0aCI6Ii81NDE3NDMyMy8zNjAzNDM1NTUtMjAzN2Y5ZDQtZGYxNi00ODMxLTg0NjctNDVkOWFmYTQ2OWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA4NDYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMTk3NWJlNmI0ZTFhYWEzZTgyMzQ5ODEzYWNmZTdlODk5OTUyOGI2OGFkZTAyMzM5ZjE0NDZkMWU5ZWJlYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sZTpjBVwjAh0RsLgJShJi465G1snx5HiPiPRYj9-39Y)

Hi Mike, kindly send the URL link of your attached image because going the the flow of this page: https://anchor-python.teams.hng.tech/dashboard/admin/settings/payment-information
The stated issue is what I get.
