### ISSUE TITLE
[FEAT]: Develop API Endpoints for Profile Settings

### ISSUE THREAD

**Issue by LivingHopeDev** [hngprojects/hng_boilerplate_nestjs#83]
## Description
 Create an API endpoint to allow users to view their profile settings. The user must be signed in to view their details.

## Acceptance Criteria
- Authentication

   - The user must be signed in to access the view and update endpoints.
   - If a user is not authenticated, the API should return a 401 Unauthorized error.
- View Profile

    - The API should return a JSON object with the current user's profile settings.
    - The response should include the following fields:
         - id
         - first_name
         - last_name
         - phone
         - avatarUrl
       
   - If the profile settings are retrieved successfully, the API should return a 200 OK status.

- Response Formats
   - Successful View Profile Response
```
{
  "id": "string",
  "first_name": "string",
  "last_name": "string",
  "phone": "string",
  "avatarUrl": "string"
  
}

```
 

- Error Handling

   - Unauthorized Access

```
{
  "status": "string",
  "message": "string",
  "statusCode": 401
}

```
## Purpose
Provide an endpoint for users to view their profile settings.

## Requirements
- [ ] Implement an endpoint to retrieve user profile settings.
  - [ ] `GET /api/v1/profile` to retrieve the current user's profile settings.
- [ ] Ensure the endpoint handles authentication securely.
  - [ ] Require users to be signed in to access the endpoint.
  - [ ] Return `401 Unauthorized` if the user is not authenticated.
- [ ] Handle responses and errors appropriately.
  - [ ] Return `200 OK` with the user's profile settings on successful retrieval.
  - [ ] Return all error responses in JSON format with an `error` field containing a descriptive message.

## Unit test

 - GET /api/v1/profile Endpoint:

    - Test that the endpoint returns the user's profile settings correctly.
    - Mock the data access layer to simulate different scenarios.
    - Verify that the response includes all expected fields (profile picture, username, pronouns, job title, etc.).
    
## End-to-End Tests
- Authenticated User:

   - Setup: Authenticate a test user.
   - Action: Send a GET request to /api/v1/profile.
   - Assertions: Verify 200 OK status.
   - Verify the response includes all expected fields.
   
- Unauthenticated User:

  - Setup: Ensure no user is authenticated.
  - Action: Send a GET request to /api/v1/profile.
  - Assertions: Verify 401 Unauthorized status.
  - Verify the response contains the correct error message.
  
- Profile Data Integrity:

  - Setup: Create and authenticate a test user.
  - Action: Send a GET request to /api/v1/profile.
  - Assertions: Verify 200 OK status.
  - Verify the response data matches the stored profile data.
  
## Expected Outcome
A set of API endpoints that enable users to manage their profile settings seamlessly.

###

**Comment by markessien** [comment]
Split Write from Read as tickets, and split the updating of the users profile picture into another ticket

**Comment by LivingHopeDev** [comment]
This issue has been split as instructed. I am working on #122 . This issue will be closed.

**Comment by LivingHopeDev** [comment]
This issue has been split as instructed. I am working on #122 . This issue will be closed.

**Comment by LivingHopeDev** [comment]
I am reopening this issue because I haven't been able to get my team lead for #122 to attend to the comment made by the mentor. I have tried to reach him severally but no response from him for the last 24 hours.
 
 The mentor's comment "Success Response formatting is not standard". I have updated it.
.
