### ISSUE TITLE
[FIX] Implement Squeeze Pages Design

### ISSUE THREAD

**Issue by Dharah15** [hngprojects/hng_boilerplate_nestjs#849]
## Description
The backend endpoints for the squeeze pages have been created, but the frontend implementation is missing, causing a 404 error when users attempt to access the pages

## Acceptance Criteria
Squeeze pages load without a 404 error and display the appropriate content from the backend.
Routing is correctly set up, and API integration with the backend is seamless.
Proper error handling is in place for API failures.

### Purpose
To ensure that users can access the squeeze pages without encountering a 404 error and that the pages display the correct content fetched from the backend.
### Requirements	
Set up proper routing to direct the frontend to the correct backend endpoints for the squeeze pages.
Create the necessary frontend components to display the squeeze pages.
Implement API calls to retrieve content from the backend and display it on the squeeze pages.
### Design Link
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=41-125959&t=kWPINewc8fj2DAd5-0

**Comment by Dharah15** [comment]
##Video of the Issue
[https://www.loom.com/share/2dce12b1d4264f21beab0832b27c89a4?sid=ab1cb61b-310b-42e4-95b8-dacce1541254](url)

**Comment by johnson-oragui** [comment]
If this is an issue meant for frontend, it should be on the https://github.com/hngprojects/hng_boilerplate_nextjs repository.

and kindly add the team name the fix is meant for.
