### ISSUE TITLE
[FEAT] View Single Product Page

### ISSUE THREAD

**Issue by F0laf0lu** [hngprojects/hng_boilerplate_nestjs#89]
## Description

Create a page to view detailed information about a single product, allowing a user to get more details about the selected product.

## Acceptance Criteria

- A user should be able to easily view details of a product on a single page.
- The page should display all relevant product information correctly.
- The design should be consistent with the overall application.
- The page should handle errors gracefully and display appropriate messages to the user.
- The page should be fully responsive and work well on various devices.

### Purpose

Creating a single product page in the frontend, displaying the detailed information about a selected product by sending a get request to the backend API and rendering the response data

### Requirements	

- [ ] API Integration:
    - Fetch product information from the backend API using the product ID
    - Implement error handling for scenarios where the API call fails or returns an error
    - Display a loading indicator while the data is being fetched.

 - [ ] Page Layout and Design:
   - Product Information Display
   - Ensure the page design is consistent with the overall application design.

- [ ] User Experience:
   - Users should easily navigate to the single product page from the product listing or any other relevant page
   - Ensure the page is fully responsive and works well on various devices 

- [ ] Functionality
   - Include any interactive elements like add to cart, add to Wishlist, if applicable.
   - provide a way for users to navigate back to the product listing or previous page.

### Testing
- Write unit tests for the API call and data rendering functions.
- Ensure the UI displays the product information correctly and handles different scenarios (e.g., product not found, API error).

### Expected Outcome
- Users can navigate to the single product page from the product listing or other relevant sections.
- The single product page accurately displays all relevant product information (name, images, price, description, availability, etc.).
- The page is visually consistent with the rest of the application, providing a seamless user experience.
- Loading indicators are displayed while data is being fetched, and appropriate error messages are shown in case of any issues.
- The page is fully responsive, providing a good user experience across different devices and screen sizes.
- Any interactive elements (e.g., add to cart) work correctly.
- Back navigation allows users to return to the previous page or product listing easily.
- All specified tests (unit and UI) pass successfully, ensuring the reliability and quality of the implementation.

**Comment by markessien** [comment]
This is a frontend ticket
