### ISSUE TITLE
[FEAT]: Fetch Customer List Endpoint - Backend

### ISSUE THREAD

**Issue by EmmanuelOmoiya** [hngprojects/hng_boilerplate_nestjs#91]
## Description
Develop an API endpoint to fetch a list of customers.

## Acceptance Criteria
- The endpoint should be accessible at `api/v1/customers?limit=10&page=1`.
- The endpoint should return a paginated response with an `array` of customer objects each containing `firstName`, `lastName`, `email`, `phoneNumber` and `organisations` array containing the organisations uuid.
- The endpoint should accept HTTP `GET` requests.
- The endpoint should be secured to ensure that only a user with an admin role can fetch the list of customers.
- Proper authentication mechanisms (e.g., JWT, OAuth2, SAML) should be implemented.
- Requests to the endpoint must include a valid authentication token in the Authorization header. `Authorization: Bearer <token>`
- Response (Success)
```sh
{
"statusCode": 200,
"currentPage": 1,
"totalPages": 20,
"limit": 10,
"totalItems": 202,
"data":
[
  {
     "firstName": "Emmanuel",
     "lastName": "xxxxxxxxxxx",
     "phoneNumber": "xxxxxxxxxxx",
     "organisations": ["xxxxxxxxxxxx", "xxxxxxxxxxx", "xxxxxxxxxxxx"]
  }
  ...
]
}
```

- Response (Error)
```sh
{
  "statusCode": 401,
  "message": "Unauthorized",
  "error": "Bad Request"
}
```

Internal Sever Error
```sh
{
  "error": Bad Request,
  "message": "Internal server error",
  "statusCode": 500
}
```

### Purpose
To fetch the list of customers in the Database

### Requirements	
- [ ] User must be authenticated thereby having a `Authorization: Bearer <token>` header in the request body
- [ ] User must have the role of an admin
- [ ] User account must be active
- [ ] User must indicate the limit number and page number 

### Expected Outcome
- [ ] A paginated response with array of customers object where each customer object contains `firstName`, `lastName`, `email`, `phoneNumber` and `organisations` array containing the organisations uuid.

### Testing
1. Unit Tests
The systems should have unit tests covering:

 - [ ] Ensure data is fetched correctly from the database.
 - [ ] Test that the appropriate response and status code is returned

**Comment by markessien** [comment]
Requires pagination

**Comment by EmmanuelOmoiya** [comment]
Added pagination. Kindly revise for approval.
