### ISSUE TITLE
[FEAT]: Order Invoice API Endpoint - Backend

### ISSUE THREAD

**Issue by legacywebhub** [hngprojects/hng_boilerplate_nestjs#92]
## Description

Implement a feature to send an invoice email after successful order payment/purchase or when user access a completed order (history)

## Acceptance Criteria

- User must have successfully paid for an order to receive an invoice

## Expected Outcome

Users should be able to access payment information of an order and order-related information

## Purpose

To ensure order and payment preview to users via invoice

## Requirements

- Specific order page/view
- Successful order completion via payment

## Invoice Email

Invoice Email Endpoint [GET] /api/v1/order/{orderID}/invoice

## Request

**Successful Response**

* status code - 200 Ok

```json
[
   "invoiceDetails": {
        "invoiceNumber": "string",
        "dateOfIssue": "date",
        "dueDate": "date"
    },
    "orderSummary": {
        "items": [
            {
                "item": "string",
                "price": "float"
            },
            {
                "item": "string",
                "price": "float"
            }
        ],
        "vat": {
            "percentage": "int",
            "amount": "float"
        },
        "total": {
            "percentage": 100,
            "amount": "float"
        }

    },
    "paymentDetails": {
        "amount": "float",
        "paymentMethod": "string",
        "bankName": "string",
        "accountNumber": "string",
        "accountName": "string"
    }
]
```

**Error Response**

* status code - 404 Not Found

```json
{
    "message": "string",
    "error": "string",
    "statusCode": "int"
}
```

## Datebase Schema

![Database Schema](https://drive.google.com/file/d/10nm36gZfRdagUsUpGbd8MoROiL3wDMgz/view?usp=drive_link)

**Comment by markessien** [comment]
this is not in the scope of this project
