### ISSUE TITLE
[FEAT] Create Backend API Endpoint for Password Recovery

### ISSUE THREAD

**Issue by Takinnuoye5** [hngprojects/hng_boilerplate_nestjs#93]
Description:
Develop a new API endpoint to handle password recovery requests. The endpoint should securely process password recovery requests and send password reset emails to users. The endpoint should accept the user's email in the request body and return appropriate responses.

Requirements:

- Endpoint: /api/v1/password-recovery

- HTTP Method: POST

- Headers:

      - Content-Type: application/json

- Request Body:

```
json

{
  "email": "user@example.com"
}
```

- Success Response (200):

```
json

{
  "message": "Password recovery email sent."
}

```
- Error Responses:

- 400 (Invalid Request Parameters):

```
json

{
  "error": "Invalid request parameters",
  "message": "Email is required."
}

```

- 404 (User Not Found):
```
json

{
  "error": "User not found",
  "message": "No user found with the provided email."
}

```

Testing:

- Unit Tests:

- Valid Email:
     - Ensure that a valid email returns a 200 status and a success message.
- Invalid Email:
     - Ensure that an invalid email format returns a 400 status and an appropriate error message.
- Missing Email:
    - Ensure that a missing email in the request body returns a 400 status and an appropriate error message.
- User Not Found:
    - Ensure that a non-existent email returns a 404 status and an appropriate error message.
 

- Integration Tests:
   - Database Connection:
        - Verify that the endpoint correctly interfaces with the database to check for the user's email.
    - Email Sending:
        - Ensure that a password recovery email is correctly sent using the configured email service.
        
Acceptance Criteria:

- The endpoint must securely accept email for password recovery.
- The endpoint must return appropriate responses for success and errors.
- The database should securely handle password recovery requests and send recovery emails.

 Expected Outcome:
A functional API endpoint that processes password recovery requests and sends password reset emails to users securely.

Database Design for Password Recovery
To support the password recovery functionality, you need to extend the existing user database schema to store password recovery tokens. These tokens will be used to validate password reset requests. Here’s a proposed design:

Users Table
The users table will remain mostly unchanged. Ensure it includes an email field for identifying users.

```
sql

CREATE TABLE users (
  id UUID PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
```

Password Recovery Tokens Table
A new table, password_recovery_tokens, will store the tokens used for password recovery. This table will link to the users table via the user_id.

```
sql
Copy code
CREATE TABLE password_recovery_tokens (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL,
  token VARCHAR(255) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

```

Explanation of Fields

- id: A unique identifier for each password recovery request.

- user_id: A reference to the user in the users table who requested the password recovery.

- token: A unique token that will be sent to the user's email and used to verify the password recovery request.

- expires_at: A timestamp indicating when the token expires. Typically, password recovery tokens should have a short validity period (e.g., 1 hour).

- created_at: The timestamp when the password recovery token was created.

Example SQL Commands
Here’s how you can create the tables using SQL:

Create Users Table
```
sql

CREATE TABLE users (
  id UUID PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
```

Create Password Recovery Tokens Table
```
sql

CREATE TABLE password_recovery_tokens (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL,
  token VARCHAR(255) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
```

Password Recovery Workflow

- Request Password Recovery:

-  User submits their email to the /api/v1/password-recovery endpoint.

- The system checks if the email exists in the users table.

- If the email exists, generate a unique token and store it in the password_recovery_tokens table with the user_id and expires_at timestamp.

- Send a password recovery email to the user with a link containing the token.

Password Reset:

- User clicks on the link in the email, which takes them to a password reset page.

- User submits a new password along with the token.

- The system validates the token by checking the password_recovery_tokens table.

- If the token is valid and not expired, update the user's password in the users table and delete the token from the password_recovery_tokens table.

This design ensures secure handling of password recovery requests, with tokens stored separately and linked to users.

**Comment by buka4rill** [comment]
This is not properly specified

**Comment by Takinnuoye5** [comment]
@markessien @buka4rill i have updated the issue with database design and request body

**Comment by phurhard** [comment]
Checkout #12
