### ISSUE TITLE
[FEAT] Blog Post Listing Endpoint - Backend

### ISSUE THREAD

**Issue by Pythonian** [hngprojects/hng_boilerplate_nestjs#94]
## Description

_Develop an endpoint to handle requests to fetch and return all blog post data. If the data is fetched successfully, it will be returned to the client with a `200 OK` status. If an error occurs, an appropriate error status will be returned._

### Acceptance Criteria

- The endpoint fetches and returns blog post data including title, excerpt, publish date, and author.
- Supports pagination through query parameters `page` and `page_size`.
- Returns a `200 OK` status code and the correct response body when data is fetched successfully.
- Returns an appropriate error message when an error occurs.
- Filters out soft-deleted blog posts for users.
- The endpoint does not require authentication.
- Fetches blog post data ordered by the created date in descending order.

### Requirements

- [ ] Implement API endpoint for fetching paginated blog post summaries.
- [ ] Fetch and return blog post data including: Title, Excerpt, Publish Date, Author.
- [ ] Implement pagination with query parameters `page` and `page_size`.
- [ ] Handle unexpected errors and return the appropriate status code.
- [ ] Ensure soft-deleted blog posts are not returned for users.
- [ ] Ensure the endpoint does not require authentication.
- [ ] Order blog post data by the created date in descending order.

### Expected Outcome

- Visitors should be able to send a request to the backend to retrieve a paginated list of all blog post summaries.
- Visitors should receive appropriate status codes and responses based on the outcome of the request.
- Blog posts should be retrieved and returned in order of most recently created first.

### Endpoints

[GET] /api/v1/blogs

- **Description**: Fetches a paginated list of blog post summaries.
- **Query Parameters**:
  - `page`: The page number to retrieve. Default is `1`.
  - `page_size`: The number of blog posts per page. Default is `10`.
- **Success Response**:
  - Status: `200 OK`
  - Body:

    ```json
    {
      "count": 100,
      "next": "http://example.com/api/v1/blogs?page=2&page_size=10",
      "previous": null,
      "results": [
        {
          "id": "uuid",
          "title": "My First Blog",
          "excerpt": "This is an excerpt from my first blog.",
          "image_url": "https://example.com/image1.jpg",
          "tags": [
            "python",
            "coding"
          ],
          "created_at": "datetime"
        },
      ]
    }
    ```

- **Error Response**:
  - Status: `500 Internal Server Error`
  - Body:

    ```json
    {
        "error": "Internal server error."
    }
    ```

- **Invalid Method Response**:
  - Status: `405 Method Not Allowed`
  - Body:

    ```json
    {
        "error": "This method is not allowed."
    }
    ```

- **Bad Request Response**:
  - Status: `400 Bad Request`
  - Body:

    ```json
    {
        "error": "An invalid request was sent."
    }
    ```

### Testing

**Test Scenarios**

1. **Successful Retrieval of Paginated Blog Posts**
   - Ensure that the endpoint successfully retrieves a paginated list of blog posts.
   - Verify that the response includes the total count, next and previous page URLs, and the results with title, excerpt, publish date, and author for each blog post.
   - Confirm that the status code is `200 OK`.
   - Confirm that the blog posts are ordered by the created date in descending order.

2. **No Blog Posts Present**
   - Simulate a scenario where no blog posts are present in the database.
   - Confirm that the response body contains an empty list.

3. **Internal Server Error**
   - Simulate an internal server error to raise an exception.
   - Verify that the endpoint returns a `500 Internal Server Error` status code.
   - Confirm that the response body contains an appropriate error message.

4. **Invalid Page or Page Size Parameters**
   - Send requests with invalid `page` or `page_size` parameters (e.g., negative numbers, non-integer values).
   - Verify that the endpoint returns a `400 Bad Request` status code and an appropriate error message.

5. **Invalid Method**
   - Send a request using an invalid HTTP method (e.g., POST) to the endpoint.
   - Verify that the endpoint returns a `405 Method Not Allowed` status code.

6. **Soft-Deleted Blog Post Access Control**
   - Ensure that soft-deleted blog posts are filtered out for users.

**Comment by Pythonian** [comment]
Hi @buka4rill @markessien 

There is an issue here. I created this ticket which got first approval, and while still trying to raise a complete team of 6, someone who successfully did has now gone to get this assigned to himself.

How do i proceed now?

**Comment by Pythonian** [comment]
Team members Slack ID

1. Sapagrammer
2. Salem 
3. Anetor Oselumese

**Comment by buka4rill** [comment]
@Pythonian include their github usernames

**Comment by Pythonian** [comment]
> @Pythonian include their github usernames

@buka4rill I have updated it, but the third guy hasn't responded since I asked him for his. So whenever he responds, i will update it with his github username.

https://github.com/hngprojects/hng_boilerplate_nestjs/issues/94#issuecomment-2233630997
