### ISSUE TITLE
[FEAT] API Endpoint to Create Comment to Blog Post - BACKEND

### ISSUE THREAD

**Issue by IsraelBO17** [hngprojects/hng_boilerplate_nestjs#96]
## Description
This endpoint creates a comment and attach it to a blog post.

#### Purpose
- Given a request with valid details to create a comment (the user must have been authenticated to be able to post a comment, so that the Authorization Header holds the access token of the user in which the user details can be obtained from), and the comment body itself, the system should create a new comment under the specific blog with a `201` created status code.

### Requirements	
- Request Header: The user must have been authenticated.
```
{
    "Authorization": "Bearer eyJhbGciOiJIUzI1N...."
}
```
- Request Body: The comment body.
```
{
    "body": "<comment body>"
}
```

### Expected Outcome
- Successful response: status code: `201`
```
{
    "message": "<success message>",
    "data": {
        "comment": {
            "id": "string",
            "body": "string",
            "date_created": "timestamp",
            "user": "string<user-id>",
            "upvote": int,
            "downvote": int
        }
    }
}
```

- Error response:
```
{
    "message": "string",
    "status_code": int
}
```

**Comment by markessien** [comment]
Comments are a generic, standalone feature, and can be attached to anything. They are not specific to blogs

**Comment by IsraelBO17** [comment]
> Comments are a generic, standalone feature, and can be attached to anything. They are not specific to blogs

I have removed the 'blogId' attachment
