### ISSUE TITLE
[FEAT] List products

### ISSUE THREAD

**Issue by EAZYLINK** [hngprojects/hng_boilerplate_nestjs#97]
## Description
Develop an API endpoint to list products with pagination support. The endpoint should return basic information about each product, including the product name, price, and category.

## Acceptance Criteria

1. API Endpoint: Create an endpoint /api/products.
2. Response Structure: The response should include:

- Product name
- Product price
- Product category
3. Pagination Support: Include pagination parameters in the request:

- page: Current page number (default is 1)
- limit: Number of products per page (default is 10)

6. Response Pagination Info: Include pagination information in the response:

- totalItems: Total number of products
- totalPages: Total number of pages
- currentPage: Current page number

### Purpose
To provide a means for clients to retrieve a paginated list of products with essential details, enhancing the user experience by allowing them to browse products efficiently.

### Requirements	

- Database Integration: Ensure the endpoint queries the database to fetch product details.
- Pagination Logic: Implement logic to handle pagination, calculating the appropriate offset and limit based on the request parameters.
- Error Handling: Include proper error handling for scenarios such as invalid page/limit values and database connectivity issues.
- Testing: Write unit and integration tests to ensure the endpoint works as expected.

### Expected Outcome

- Response(success):

```
{
  "success": true,
  "message": "Product retrieved successfully",
  "products": [
    {
      "name": "Product 1",
      "price": 29.99,
      "category": "Electronics"
    },
    {
      "name": "Product 2",
      "price": 19.99,
      "category": "Books"
    },
    ...
  ],
  "pagination": {
    "totalItems": 100,
    "totalPages": 10,
    "currentPage": 1
  },
"status_code": 200
}
```

- Response(bad request):
```
{
  "status": "bad request",
  "message": "Invalid query params passed",
  "status_code": 400
}
```

- Response(Error):

```
{
  "status": "error",
  "message": "Internal server error",
  "status_code": 500
}
```
### Additional Notes:

- The endpoint should be secured and require appropriate authentication/authorization.
- Ensure the API follows RESTful conventions.
- Use appropriate HTTP status codes for success and error scenarios.
### Testing

- Test that the endpoint returns a 200 on successful product retrieval.
- Test that invalid data triggers a 400 Bad Request response with an appropriate error message.
- Test that the returned product lists are within specified page and limits.
- Test that the endpoint triggers a 500 Internal server error on failed attempt to access the database

**Comment by nedssoft** [comment]
@EAZYLINK update the Expected Outcome object to follow the accepted conventions

**Comment by EAZYLINK** [comment]
@nedssoft Updated

**Comment by nedssoft** [comment]
@EAZYLINK I didn't say you should remove the technical specs, take it back to what it was and read the slack message about conventions to understand what I meant

**Comment by EAZYLINK** [comment]
@nedssoft I have made the changes

**Comment by buka4rill** [comment]
Make this codeblock instead of code lines
![CleanShot 2024-07-17 at 18 10 14](https://github.com/user-attachments/assets/1b939fa1-5ead-4f89-b819-b5ac54873fce)

**Comment by buka4rill** [comment]
You also need something like this
![CleanShot 2024-07-17 at 18 10 59](https://github.com/user-attachments/assets/16b06c59-ce3e-457a-8d68-ff8a2ff12656)

**Comment by nedssoft** [comment]
@EAZYLINK prepend `v1` to your API endpoint e.g  `v1/api/products`

**Comment by EAZYLINK** [comment]
@markessien @nedssoft I have limited access to this ticket

**Comment by nedssoft** [comment]
What access do you want?

**Comment by EAZYLINK** [comment]
> What access do you want?

assign
